### ISSUE TITLE
cant browse site

### ISSUE THREAD

**Issue by dndndn77** [unosquare/passcore#1]
hi
i download the files and installed and when i try to browse the site my browser is write loading..with
red icon and nothing hapend.
please your help
thanks
dan

**Comment by mariodivece** [comment]
Did you follow the Installation Instructions on IIS located in the README.md file? If so, did you try to troubleshoot the issue with the recommended reading: http://www.strathweb.com/2015/12/running-asp-net-5-website-on-iis/
Go to the section "Resolving Errors". What version of Windows Server/IIS are you using?

**Comment by dndndn77** [comment]
hello
i have IIS 8.5 and server 2012.
i follow the instructions several times and i have the same behavier all
the time.
which version i need to download? i tried the original and after that i
download the latest and still cant get the site.
thanks
dan


2016-01-26 5:13 GMT+02:00 Mario Di Vece <notifications@github.com>:

**Comment by mariodivece** [comment]
Did you try the suggestions on issue #2 ?

**Comment by jwhipp** [comment]
Same issue here, tried suggestions of issue 2.  Installs a bunch of stuff but connecting to the site just times out.   It's like it's not firing up.

Same configuration, IIS on 2012 R2

**Comment by mariodivece** [comment]
did you try adding an http binding on localhost, port 9696 and opening up a web browser on the same server and navigating to http://localhost:9696 ?
You guys may have your Windows Firewall blocking traffic or an external firewall may not be allowing traffic through. Can you give it a try and let me know?

**Comment by Abyssar** [comment]
i had the same issue (Server 2012 / IIS 8.5).. so i enabled logging in the web.config file and fired up the website.

I noticed the following entry in the logs:

> Error: Unable to load application or execute command 'Microsoft.AspNet.Server.Kestrel'. Available commands: web.
> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
>    at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
>    at System.Reflection.Assembly.LoadFile(String path)
>    at Microsoft.Dnx.Runtime.Loader.LoadContext.LoadFile(String assemblyPath)
>    at Microsoft.Dnx.Runtime.Loader.PackageAssemblyLoader.Load(AssemblyName assemblyName, IAssemblyLoadContext loadContext)
>    at Microsoft.Dnx.Runtime.Loader.PackageAssemblyLoader.Load(AssemblyName assemblyName)
>    at Microsoft.Dnx.Host.LoaderContainer.Load(AssemblyName assemblyName)
>    at Microsoft.Dnx.Host.DefaultLoadContext.LoadAssembly(AssemblyName assemblyName)
>    at Microsoft.Dnx.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(AssemblyName name, Func`2 factory)
>    at Microsoft.Dnx.Runtime.Loader.LoadContext.LoadAssemblyImpl(AssemblyName assemblyName)
>    at Microsoft.Dnx.Runtime.Loader.LoadContext.ResolveAssembly(Object sender, ResolveEventArgs args)
>    at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)

So I removed the Zone.Identifier which can be found in the ntfs alternate stream from all files so the server thinks that these files were created locally.. et voila.. the site runs fine.

**Comment by dndndn77** [comment]
hello
can you please explain what i need to do exactaly ?
thanks

2016-02-03 13:29 GMT+02:00 Abyssar <notifications@github.com>:

**Comment by benclaussen** [comment]
@dndndn77 I resolved the same issue by doing the following (Windows Server 2012R2, sourced from [http://blogs.msdn.com/b/sujitdmello/archive/2015/04/23/step-by-step-installation-instructions-for-getting-dnx-on-your-laptop.aspx](url))

1. Ensured .NET 4.5.2 was installed from [http://www.microsoft.com/en-us/download/details.aspx?id=42643](url)
2. Ensured Powershell v4 was installed by checking `$PSVersionTable.PSVersion` for `4.0`
3. Installed Visual C++ 2013 Redistributable from [http://www.microsoft.com/en-us/download/details.aspx?id=40784](url)
4. Ran the following in elevated Powershell (sets branch to dev, then downloads and installs DNVM)
`$Branch='dev'; 
iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))`

Once I finished that, I followed the comments from [https://github.com/unosquare/passcore/issues/2#issuecomment-174886322](url) by running `dnu restore` from a command prompt in the directory `passcore\approot\src\Unosquare.PassCore.Web`

It completed telling me there were 97 packages restored to `passcore\approot\packages`

Everything worked after these steps.

**Comment by mariodivece** [comment]
Looks like @benclaussen has provided detailed instructions on how to make it work when you run into issues. I'll add a link to this post on the main REDME file.

**Comment by ralphcostatan** [comment]
Where can I find an uninfected zip copy of PassCode 2 that's not infected with malware? 

The flavor available at https://github.com/unosquare/passcore/releases/download/v2.0.0/passcore-2.0-2016-01-24.zip ix is infected (see www.virustotal.com, SHA256: 	892f4574ea0001ae49fb9dc01cbf174d315979b6dbe3a06c434cde725e38d710,  	passcore-2.0-2016-01-24.zip, Detection ratio: 	2 / 54.

passcore-master.zip, source code, is not reported as infected.

Regards,

**Comment by crathermel** [comment]
:+1:  @benclaussen - There are no steps about installing dnx, or any other dependancies.  Looks like this was key to getting it to actually load.

**Comment by tbusche** [comment]
I have PassCode installed and the page comes up, but when I try to change a password, I get the error, "There was an error changing your password
Error Information: The specified directory service attribute or value does not exist. "  

Any ideas?

**Comment by masanarchy** [comment]
Getting the following error when trying to download and install DNVM. Appreciate the help.

![error](https://cloud.githubusercontent.com/assets/22618851/19078721/179938ee-8a1f-11e6-8b2e-ee15e7b72efe.JPG)

**Comment by mariodivece** [comment]
@masanarchy Unfortunately, this has nothing to do with PassCore itself. Try:
https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1
Note the 1 (NOT l as you seem to have specified) in the ps1 extension
Additionally, please refer to:
https://blogs.msdn.microsoft.com/sujitdmello/2015/04/23/step-by-step-installation-instructions-for-getting-dnx-on-your-windows-machine/

**Comment by masanarchy** [comment]
That did. Stupid mistake. Thanks @mariodivece
