### ISSUE TITLE
Stuck on 'Loading Passcore...'

### ISSUE THREAD

**Issue by tsauni** [unosquare/passcore#100]
Hi there,

A little while back I tried an earlier version of PassCore and got it running successfully and still have it running on a dev machine.

Today I came back to re-look at setting this up for use in our Production environment and saw a newer version which I have tried to get running but have been unsuccessful in doing so.

I downloaded the passcore-3.0.1.zip and followed the instructions in the README.md (the **Important** & **Note** details listed under Step 8 don't seem to apply to this version. Couldn't find any wwwroot folder nor the web.config file that contains the stdoutLogEnabled value to enable logging).

I have an IIS site running over https, when I try to load the website in IE or Chrome (on a box running Windows Server 2012 R2) it comes up with the "Loading Passcore..." screen and stays on that and never gets any further. This was the same over http.

After going over all the steps to ensure I haven't missed anything and checking on config files to see if anything there may need to be tweaked and not having luck, I removed it all and started over again (removed the IIS site, app pool & passcore folder contents). However even after running through it fresh all over again I still ended up with the same issue - stuck on "Loading Passcore..." screen.

I set up a new site & app pool on the dev machine where the previous version of PassCore is currently running (successfully) and ended up with the same result.

Can anyone confirm what the size of the .zip or it's contents when extracted should be? After extracting the passcore-3.0.1.zip, the extracted folder passcore-3.0.1 is 419KB - is this right?

Let me know what else you may want to know or need from me to assist with troubleshooting, thank you.

**Comment by jpalcala** [comment]
Hi @tsauni.
After downloading passcore-3.0.1.zip we realized that it was not a binary release but the source code, that's why you couldn't find any wwwroot folder. We have already updated the README.md with the correct [link](https://github.com/unosquare/passcore/releases/download/3.0.1/Passcore-3.0.1.zip). Please try to set up Passcore again and if it does not work let us know.

**Comment by tsauni** [comment]
Hi @jpalcala, 

Thank you for getting back so quickly and with the correct link.

I have managed now to get a web page loading but there are no field labels (username, old password, new password etc). I have attached a screenshot of this. I get the same in Firefox & Chrome.

![missing_labels](https://user-images.githubusercontent.com/35356337/34925164-75eeb4ba-fa0c-11e7-8e3d-afc3c1bdbcfc.png)

**Comment by jpalcala** [comment]
Hey @tsauni,  I tested pasccore using the link provided above and everything worked fine for me. Could you please  access passcore using Chrome, open the developer tools with F12 and show us the console output?

**Comment by tsauni** [comment]
Hi @jpalcala,

Here's what I got from the console output:

> portal.web.prod.work/:82 GET https://portal.web.prod.work/assets/fonts/Roboto/latin.woff2 net::ERR_ABORTED
polyfills.bundle.js:78 GET https://portal.web.prod.work/api/password 404 (Not Found)
l @ polyfills.bundle.js:78
e.scheduleTask @ polyfills.bundle.js:43
onScheduleTask @ polyfills.bundle.js:43
e.scheduleTask @ polyfills.bundle.js:43
t.scheduleTask @ polyfills.bundle.js:43
t.scheduleMacroTask @ polyfills.bundle.js:43
(anonymous) @ polyfills.bundle.js:78
t.(anonymous function) @ polyfills.bundle.js:8
(anonymous) @ vendor.bundle.js:795
t._trySubscribe @ vendor.bundle.js:929
t.subscribe @ vendor.bundle.js:929
t.GetData @ vendor.bundle.js:1
t.ngOnInit @ vendor.bundle.js:1
wn @ vendor.bundle.js:478
dr @ vendor.bundle.js:513
lr @ vendor.bundle.js:513
Fr @ vendor.bundle.js:513
(anonymous) @ t_Host.ngfactory.js:8
updateDirectives @ vendor.bundle.js:513
ur @ vendor.bundle.js:513
t.detectChanges @ vendor.bundle.js:590
(anonymous) @ vendor.bundle.js:569
e.tick @ vendor.bundle.js:569
e._loadComponent @ vendor.bundle.js:569
e.bootstrap @ vendor.bundle.js:569
(anonymous) @ vendor.bundle.js:569
e._moduleDoBootstrap @ vendor.bundle.js:569
(anonymous) @ vendor.bundle.js:569
e.invoke @ polyfills.bundle.js:43
onInvoke @ vendor.bundle.js:422
e.invoke @ polyfills.bundle.js:43
t.run @ polyfills.bundle.js:43
(anonymous) @ polyfills.bundle.js:50
e.invokeTask @ polyfills.bundle.js:43
onInvokeTask @ vendor.bundle.js:422
e.invokeTask @ polyfills.bundle.js:43
t.runTask @ polyfills.bundle.js:43
n @ polyfills.bundle.js:43
Promise resolved (async)
t @ polyfills.bundle.js:43
e.scheduleTask @ polyfills.bundle.js:43
t.scheduleTask @ polyfills.bundle.js:43
t.scheduleMicroTask @ polyfills.bundle.js:43
i @ polyfills.bundle.js:50
e.then @ polyfills.bundle.js:50
e._bootstrapModuleWithZone @ vendor.bundle.js:569
e.bootstrapModule @ vendor.bundle.js:569
./ClientApp/main.ts @ vendor.bundle.js:1
n @ inline.bundle.js:1
0 @ main.bundle.js:1
n @ inline.bundle.js:1
window.webpackJsonp @ inline.bundle.js:1
(anonymous) @ main.bundle.js:1
vendor.bundle.js:394 ERROR e {_body: "<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Stric…>
↵ </fieldset></div>
↵</div>
↵</body>
↵</html>
↵", status: 404, ok: false, statusText: "Not Found", headers: t, …}headers: t_headers: Map(4) {"date" => Array(1), "x-powered-by" => Array(1), "content-length" => Array(1), "content-type" => Array(1)}_normalizedNames: Map(4) {"date" => "date", "x-powered-by" => "x-powered-by", "content-length" => "content-length", "content-type" => "content-type"}__proto__: Objectok: falsestatus: 404statusText: "Not Found"type: 2url: "https://portal.web.prod.work/api/password"_body: "<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
↵<html xmlns="http://www.w3.org/1999/xhtml">
↵<head>
↵<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
↵<title>404 - File or directory not found.</title>
↵<style type="text/css">
↵
↵</style>
↵</head>
↵<body>
↵<div id="header"><h1>Server Error</h1></div>
↵<div id="content">
↵ <div class="content-container"><fieldset>
↵  <h2>404 - File or directory not found.</h2>
↵  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
↵ </fieldset></div>
↵</div>
↵</body>
↵</html>
↵"__proto__: t
b @ vendor.bundle.js:394
t.handleError @ vendor.bundle.js:555
next @ vendor.bundle.js:569
e.object.i @ vendor.bundle.js:569
e.__tryOrUnsub @ vendor.bundle.js:929
e.next @ vendor.bundle.js:929
e._next @ vendor.bundle.js:929
e.next @ vendor.bundle.js:929
e.next @ vendor.bundle.js:929
e.emit @ vendor.bundle.js:569
(anonymous) @ vendor.bundle.js:422
e.invoke @ polyfills.bundle.js:43
t.run @ polyfills.bundle.js:43
t.runOutsideAngular @ vendor.bundle.js:569
onHandleError @ vendor.bundle.js:422
e.handleError @ polyfills.bundle.js:43
t.runTask @ polyfills.bundle.js:43
o.invokeTask @ polyfills.bundle.js:43
j @ polyfills.bundle.js:8
_ @ polyfills.bundle.js:8
XMLHttpRequest.send (async)
l @ polyfills.bundle.js:78
e.scheduleTask @ polyfills.bundle.js:43
onScheduleTask @ polyfills.bundle.js:43
e.scheduleTask @ polyfills.bundle.js:43
t.scheduleTask @ polyfills.bundle.js:43
t.scheduleMacroTask @ polyfills.bundle.js:43
(anonymous) @ polyfills.bundle.js:78
t.(anonymous function) @ polyfills.bundle.js:8
(anonymous) @ vendor.bundle.js:795
t._trySubscribe @ vendor.bundle.js:929
t.subscribe @ vendor.bundle.js:929
t.GetData @ vendor.bundle.js:1
t.ngOnInit @ vendor.bundle.js:1
wn @ vendor.bundle.js:478
dr @ vendor.bundle.js:513
lr @ vendor.bundle.js:513
Fr @ vendor.bundle.js:513
(anonymous) @ t_Host.ngfactory.js:8
updateDirectives @ vendor.bundle.js:513
ur @ vendor.bundle.js:513
t.detectChanges @ vendor.bundle.js:590
(anonymous) @ vendor.bundle.js:569
e.tick @ vendor.bundle.js:569
e._loadComponent @ vendor.bundle.js:569
e.bootstrap @ vendor.bundle.js:569
(anonymous) @ vendor.bundle.js:569
e._moduleDoBootstrap @ vendor.bundle.js:569
(anonymous) @ vendor.bundle.js:569
e.invoke @ polyfills.bundle.js:43
onInvoke @ vendor.bundle.js:422
e.invoke @ polyfills.bundle.js:43
t.run @ polyfills.bundle.js:43
(anonymous) @ polyfills.bundle.js:50
e.invokeTask @ polyfills.bundle.js:43
onInvokeTask @ vendor.bundle.js:422
e.invokeTask @ polyfills.bundle.js:43
t.runTask @ polyfills.bundle.js:43
n @ polyfills.bundle.js:43
Promise resolved (async)
t @ polyfills.bundle.js:43
e.scheduleTask @ polyfills.bundle.js:43
t.scheduleTask @ polyfills.bundle.js:43
t.scheduleMicroTask @ polyfills.bundle.js:43
i @ polyfills.bundle.js:50
e.then @ polyfills.bundle.js:50
e._bootstrapModuleWithZone @ vendor.bundle.js:569
e.bootstrapModule @ vendor.bundle.js:569
./ClientApp/main.ts @ vendor.bundle.js:1
n @ inline.bundle.js:1
0 @ main.bundle.js:1
n @ inline.bundle.js:1
window.webpackJsonp @ inline.bundle.js:1
(anonymous) @ main.bundle.js:1

**Comment by marubadi** [comment]
I have downloaded the latest source source code and still the same no progress

**Comment by Israel-94** [comment]
Hi @tsauni and @marubadi, I tested the latest binaries and everything works fine, so I have just one question, Are you sure you are reference the right folder?
The parent folder should be passcore, that folder should contain the web.config file, appseting file, wwwroot folder, etc.

**Comment by tsauni** [comment]
@Israel-94,

Thanks, that was my issue I was referencing the wrong parent folder. I was referencing the wwwroot folder. I have updated this to the passcore folder and the page is displaying correctly now - sorry guys this was my bad, should've gone back over the readme/instructions. 

Thank you for your help!

**Comment by DirectXGuy** [comment]
using passcore363 im stuck on the loading page

**Comment by DirectXGuy** [comment]
I have this from the consol. I'm not a web developer and have very little experince with IIS
[Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: http://localhost/assets/fonts/Roboto/latin.woff2
/api/password:1 Failed to load resource: the server responded with a status of 404 (Not Found)
polyfills.bundle.js:36 Unhandled Promise rejection: Unexpected token < in JSON at position 0 ; Zone: <root> ; Task: Promise.then ; Value: SyntaxError: Unexpected token < in JSON at position 0
    at main.bundle.js:97
    at t.invoke (polyfills.bundle.js:36)
    at r.run (polyfills.bundle.js:36)
    at polyfills.bundle.js:36
    at t.invokeTask (polyfills.bundle.js:36)
    at r.runTask (polyfills.bundle.js:36)
    at o (polyfills.bundle.js:36) SyntaxError: Unexpected token < in JSON at position 0
    at http://localhost/main.bundle.js:97:151299
    at t.invoke (http://localhost/polyfills.bundle.js:36:7386)
    at r.run (http://localhost/polyfills.bundle.js:36:2585)
    at http://localhost/polyfills.bundle.js:36:12789
    at t.invokeTask (http://localhost/polyfills.bundle.js:36:8070)
    at r.runTask (http://localhost/polyfills.bundle.js:36:3248)
    at o (http://localhost/polyfills.bundle.js:36:340)
e.onUnhandledError @ polyfills.bundle.js:36
