### ISSUE TITLE
How do I upgrade to latest version?

### ISSUE THREAD

**Issue by AnonSS** [unosquare/passcore#101]
I have installed and configured Passcore version 3.0.0 and works fine.  I now need to upgade to version 3.0.1 to fix the IE issue.  How can I do this without losing all the customization I have already done?
Thank you

**Comment by geoperez** [comment]
What kind of customizations do you have?

**Comment by AnonSS** [comment]
Customizations are Changing of the UI texts in appsettings.json and logo names in vendor.bundle.js and index.html.

**Comment by geoperez** [comment]
The issue is vendor.bundle.js, because it changed. You will need to download the source code and build with your customizations.

**Comment by AnonSS** [comment]
Thank you geoperez for your response and the great project you've made available.
