### ISSUE TITLE
Passcore Insallation Issues

### ISSUE THREAD

**Issue by marubadi** [unosquare/passcore#102]
Hi, I am writing this expecting some one would help me with the Passcore installation and configuration. Please see the screenshot for your better understanding on the issues I am current facing.  Your help would be appreciated.  Thanks
![capture](https://user-images.githubusercontent.com/35490562/34987976-23eefb9e-face-11e7-8f44-bf589538b77a.PNG)

**Comment by geoperez** [comment]
Duplicated. Issue #100

**Comment by tablaty** [comment]
I'm having the same trouble and I found these issue, but don't know how to fix them. 
1. Failed to load resource: the server responded with a status of 404 (Not Found) **(when trying to load the latin.woff2 - from fronts)**
2. Failed to load resource: the server responded with a status of 404 (Not Found) **(something about api/password)**
3. **error loading vendor.bundle.js:394**
I welcome any help. 

thanks,

**Comment by geoperez** [comment]
What physical folder are you using in IIS?

**Comment by tablaty** [comment]
I'm using the Passcore folder (c:\inetpub\passcore). I tried going directly to wwwroot under the passcore folder, but still not lock. 

thanks, 
Dillon
