### ISSUE TITLE
Username instead of email

### ISSUE THREAD

**Issue by AnonSS** [unosquare/passcore#103]
Is there a way to automatically append domain suffix to username so users will only type their username?  There is reference in #44 and #86 but seems like it does not apply to the latest version.

**Comment by veinom** [comment]
The solution in #86 still works, you would just put it before line 114 now in PasswordController.cs (just look for "var userPrincipal = Acquire etc." and put it on the line before that)

model.Username += "@yourdomain.com";

**Comment by AnonSS** [comment]
Apparently there are two types of downloads.  I have downloaded and installed passcore3.0.1.  There is no PasswordController.cs in this download package.  Should I have installed the passcore-master instead?  Not sure what the difference is.

**Comment by veinom** [comment]
Make sure you're downloading the source and not the binary - you will have to recompile after making the change.

One other thing you'll have to do to disable the email validator - in ClientApp\app\change-password\app.change-password.ts change
`username: new FormControl('', [Validators.required, Validators.pattern(emailRegex)]),`
to
`username: new FormControl('', [Validators.required]),`

**Comment by geoperez** [comment]
A pull request allowing to change between username or email is welcomed.
