### ISSUE TITLE
Page loading incorrectly - Passcore-3.0.1

### ISSUE THREAD

**Issue by B0bz1** [unosquare/passcore#106]
I have followed all the instructions and get get the page to load but all I get is 4 un-titled lines horizontally down the page. No other text appears on the page. The top blue bar, and logos load correctly, please see attachment. I have tried multiple browsers, Chrome, Firebox, IE.
![image](https://user-images.githubusercontent.com/35751469/35311050-6a472296-0119-11e8-995b-59fd9232550c.png)
Please help if you know what I have missed.

**Comment by geoperez** [comment]
Please refer to Issue #100

**Comment by B0bz1** [comment]
Thank you, I was referencing the wwwroot folder. Now I have the page loading correctly I seem to be missing the change password button at the bottom. Any ideas.

**Comment by B0bz1** [comment]
Thanks for your help. Can I suggest an edit in the documentation to specify the site root folder is the one above wwwroot.
Also you are not able to use old appsettings.json from a previous versions or you will loose the change password button. 
Great project - Thanks

**Comment by geoperez** [comment]
You don't need the source code. Please try to use the powershell script.
