### ISSUE TITLE
Log of password changes?

### ISSUE THREAD

**Issue by veinom** [unosquare/passcore#107]
I enabled the log in web.config but it only seems to show information related to the pages that IIS is serving - is there any way to view who it is that used the site to reset a password?  It would be nice if we could have a log of who changed their password, if they were successful, and what IP address the request came from.

**Comment by geoperez** [comment]
You can edit the [following line](https://github.com/unosquare/passcore/blob/master/src/Unosquare.PassCore.Web/Controllers/PasswordController.cs#L158) to before returning the success result add a log entry with the information.

You need to add the `ILogger` class in the `PasswordController `constructor. Check official [documentation](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?tabs=aspnetcore2x).

**Comment by veinom** [comment]
I apologize for having to ask this considering it's a basic coding question and probably not something related to this project - but as soon as I change 

> public PasswordController(`IOptions<AppSettings> optionsAccessor`)
>         {
>             _options = optionsAccessor.Value;
>         }

 to 

> public PasswordController(`IOptions<AppSettings> optionsAccessor, ILogger<PasswordController>` logger)
>         {
>             _options = optionsAccessor.Value;
> 			_logger = logger;
>         }

 the page will no longer run - visiting the site results in "Loading" with the 4 blank lines that should be for User Name, Current Password, New Password, Re-enter new password - but even those labels don't show up.  It compiles fine, but hangs when visiting the page. Any suggestions?

**Comment by geoperez** [comment]
@jpalcala can you help?

**Comment by jpalcala** [comment]
Hi @veinom  your code snippet was fine. The problem was the `LogLevel`, which was renamed from `Verbose` to `Trace` as explained [here](https://github.com/aspnet/Announcements/issues/124). We're currenlty fixing this, you just simply have to change the default `LogLevel `to `Debug`  inside `appsettings.json`.
