### ISSUE TITLE
3.0.x broken binary installation

### ISSUE THREAD

**Issue by rcmcdonald91** [unosquare/passcore#109]
Installation of 3.0.x using the instructions in the read me does not work. Folder structure is totally different (approot and logs folder are completely missing).

**Comment by geoperez** [comment]
Yes, it's different from version 2.0. The log folder should be manually created and the approot is no longer a folder.

Did you perform a clean install?

**Comment by rcmcdonald91** [comment]
I did not perform a clean install.

This fixed it!

Thanks!
