### ISSUE TITLE
Compiling source code does not work

### ISSUE THREAD

**Issue by AnonSS** [unosquare/passcore#110]
I have downloaded the source code (not the binary), unzipped it and placed it in IIS.  I then run dotnet publish --framework net461 --output C:\inetpub\passcore-master\  --configuration Release.  I get the following error:
C:\Windows\system32>dotnet publish --framework net461 --output C:\inetpub\wwwroo
t\Passcore-master --configuration Release
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1003: Specify a project or solution file. The current working
 directory does not contain a project or solution file.

Am I missing something?

**Comment by geoperez** [comment]
Yeah, you need to run the command at your PassCore folder. You are running at `system32`:

`C:\Windows\system32>dotnet publish --framework net461 --output C:\inetpub\wwwroo
t\Passcore-master --configuration Release`

**Comment by AnonSS** [comment]
Thank you sir, that worked.
