### ISSUE TITLE
Null error upon clicking change password

### ISSUE THREAD

**Issue by whickwire** [unosquare/passcore#111]
I'm having trouble digging into this error. I have installed Passcore 3.0.1 and have done all the prerequisite things mentioned.

Upon clicking change password it simply says "null". I have enabled logging and can't find much to look for a place to go forward. I have full connectivity and can connect to the ldap server using the RSAT tools so I'm getting a little frustrated.

Wondering what the recommended next steps would be as we have a fairly large user base and would like ot get this into production. Any help would be greatly appreciated.

**Comment by wag285uqfmau2vvp2c87** [comment]
Windows Firewall is disabled on the PassCore server and Domain Controller. There's no firewall between them and both on the same subnet on premises.

Thanks for the response.

**Comment by wag285uqfmau2vvp2c87** [comment]
After setting everything up again from scratch, I discovered that it broke as soon as I changed the RecaptchaPrivateKey field in the appsettings.json. So if someone else comes across the issue of Null as an error response, there could be something wrong with your appsettings.json file.

**Comment by whickwire** [comment]
Since I made it in a AWS every time something wasn't working I nuked it and started over lol

Glad to hear you got things working though. In the future for debugging if you find something won't start, open Unosquare.PassCore.Web.exe in the extracted folder. It will generally tell you why, forgot to mention that.
