### ISSUE TITLE
Chrome browser ERR_CONNECTION_RESET, But works fine in IE and Firefox

### ISSUE THREAD

**Issue by coot402** [unosquare/passcore#112]
I have successfully installed passcore on a secured domain. We use VPN to connect to this secured domain. Passcore works great under FF and IE, but when you try to connect with chrome, you get the "ERR_CONNECTION_RESET".
Running a netstat on the server, you don't even see a connection from my workstation. 
Looking at the fire walls, I see "Built inbound TCP" and then "Teardown TCP connection" with a"TCP Reset-I" which means that the server is sending a reset back.
Also nothing gets logged when in the IIS logs, or the PassCore logs when the connection attempt from chrome is made.
Does PassCore have issues with chrome?
I opened the developer tools with F12 and the console output was blank?
![chrome](https://user-images.githubusercontent.com/29930022/36326483-1ec2cd6c-1310-11e8-8e13-d7cebe261a77.PNG)

**Comment by geoperez** [comment]
Are you still having this issue?
