### ISSUE TITLE
Would it be possible to add params to the URL for automatically inserting a login username? (Idea)

### ISSUE THREAD

**Issue by Jrsnow8921** [unosquare/passcore#115]
Would it be possible to add optional params to the URL for automatically inserting a login username?

I would like to have a link to this app to update or change passwords from another app that the user is all ready signed into. Instead of reentering their username could I just pass a param to fill in the username text box for them. Could someone point me in the right direction on how to go about this approach? 

Example: URL(http://localhost:7000/?emp=justin)

Example Screenshot.

![image](https://user-images.githubusercontent.com/7851585/36603747-c98cba72-1889-11e8-9b5c-c780641079d7.png)

Thank you!

**Comment by geoperez** [comment]
You need to edit the main component (https://github.com/unosquare/passcore/tree/master/src/Unosquare.PassCore.Web/ClientApp/app/change-password). 

Pull request welcome.

**Comment by Jrsnow8921** [comment]
Any suggestions on how to implement this? @geoperez

**Comment by Jrsnow8921** [comment]
I created a pull request #116

**Comment by Jrsnow8921** [comment]
Pull request #116 merged to enable this.
