### ISSUE TITLE
username issues

### ISSUE THREAD

**Issue by vkobsc** [unosquare/passcore#117]
Dear Team
Can we change so that username is just username with no suffix like @domain.name?

Problem with current setup is that "username or password incorrect"
Did changed the, PasswordChangeOptions- included ldapusername and ldappassword details with domain admin details.
Still same issue.

Please assist me.
regards
Vinay

**Comment by geoperez** [comment]
Another user create a similar solution, you need to modify the front end to remove the email field validator and modify the WebAPI module to append the domain in the user request model.

We are not supporting this, but pull request is always welcome.

**Comment by geoperez** [comment]
Related issue #103
