### ISSUE TITLE
problem with dotnet command

### ISSUE THREAD

**Issue by ArmandoChupa** [unosquare/passcore#118]
Where can i download the correct dotnet command?
Impossible for me to compile the source code with the command at step 2.

Thanks for issue.

**Comment by ArmandoChupa** [comment]
I've this error message : "C:\Program Files\dotnet\sdk\2.0.3\Microsoft.Common.CurrentVersion.targets(1122,5
): error MSB3644: Les assemblys de référence pour le Framework ".NETFramework,Ve
rsion=v4.6.1" sont introuvables. Pour résoudre ce problème, installez le SDK ou
le Targeting Pack pour cette version de Framework, ou reciblez votre application
 vers une version du Framework pour laquelle le SDK ou le Targeting Pack est ins
tallé. Les assemblys seront résolus à partir du Global Assembly Cache (GAC) et s
eront utilisés à la place des assemblys de référence. C'est pourquoi votre assem
bly peut ne pas cibler correctement le Framework souhaité. [C:\passcore-master\p
asscore-master\src\Unosquare.PassCore.Web\Unosquare.PassCore.Web.csproj]"

Windows 7 Pro SP1 64 bits
Can you help me?

Thanks

**Comment by geoperez** [comment]
Did you install the . Net framework too?

**Comment by ArmandoChupa** [comment]
Yes.
 .Net Framework 4.6.1

but it seems like no detected correctly.

Which version of .Net framework & dotnet have i to download, to compile source?

Thanks for help.

**Comment by geoperez** [comment]
You need install the following software:

**Comment by ArmandoChupa** [comment]
I had to uninstall all framework versions, and re install your links.
I had to add node js too from https://nodejs.org/en/download/

And all runs fine.

Thanks a lot for your help.

Best regards from France.
