### ISSUE TITLE
Where to locate uninfected copy v2.0?

### ISSUE THREAD

**Issue by ralphcostatan** [unosquare/passcore#12]
Where can I find an uninfected zip copy of PassCode 2 that's not infected with malware?

The flavor available at https://github.com/unosquare/passcore/releases/download/v2.0.0/passcore-2.0-2016-01-24.zip  is infected (see www.virustotal.com, SHA256: 892f4574ea0001ae49fb9dc01cbf174d315979b6dbe3a06c434cde725e38d710, passcore-2.0-2016-01-24.zip, Detection ratio: 2 / 54.

( https://www.virustotal.com/en/file/892f4574ea0001ae49fb9dc01cbf174d315979b6dbe3a06c434cde725e38d710/analysis/ )

passcore-master.zip, source code ??, is not reported as infected.

Regards,

**Comment by mariodivece** [comment]
2 out of the 52 scanners claim that the release is a dropper. I think it's just a false positive. I am rejecting this issue because it is common for scanners to report inaccurately which I believe to be the case in this instance. In any case you also have the option to build the package yourself.
