### ISSUE TITLE
Found a bug, regarding "base href"

### ISSUE THREAD

**Issue by unquietwiki** [unosquare/passcore#124]
Some of the JS files + index.html have **../../assets/images/** hardcoded; rather relative paths without the "../../" in them. So if you don't use the standard base path, you'll end up with missing items.

**Comment by unquietwiki** [comment]
It looks like 3.0.2 attempted to fix this. @geoperez  @Israel-94  , since where I work finds this app potentially useful; and I've been getting rather lost in assorted C# and JS app stuff the past few months; I was allowed to take a look at adding an option to this. Our users seem to get stuck on entering the proper local domain name: something we'd rather not broadcast online, but also don't want to confuse with our e-mail address. In trying to make that work, I think I got the app converted over to using .NET Core 2.0. However, there seems to be something going on with Typescript / Angular, not communicating with the .NET password code. I'm using VS Code + a number of extensions for development + code cleanup.

https://github.com/unquietwiki/passcore

**Comment by geoperez** [comment]
@unquietwiki how do you change to .NET Core 2.0 if the `System.DirectoryServices.AccountManagement` is not available?

**Comment by Israel-94** [comment]
@geoperez There is a new version of [System.DirectoryServices.AccountManagement](https://www.nuget.org/packages/System.DirectoryServices.AccountManagement/4.5.0-preview2-26406-04) for .NET Core 2.0 but it is a preview, maybe something change

**Comment by unquietwiki** [comment]
@geoperez @Israel-94 I was able to use https://www.nuget.org/packages/Microsoft.Windows.Compatibility , and that appeared to deal with the .NET 4.6.1 dependency requirement. I didn't originally set out to do this migration; the dependencies & stuff I had left over from an internal project led me that way.

**Comment by geoperez** [comment]
So what error are you getting from server-side?

**Comment by unquietwiki** [comment]
![changepassword_js_errors](https://user-images.githubusercontent.com/1007551/38576380-d0a0c040-3cb2-11e8-806f-f47f68770838.png)

ERROR TypeError: Cannot read property 'changePasswordForm' of null
    at Object.eval [as updateDirectives] (VM37 t.ngfactory.js:783)
    at Object.updateDirectives (vendor.bundle.js:566)
    at ur (vendor.bundle.js:566)
    at wr (vendor.bundle.js:566)
    at br (vendor.bundle.js:566)
    at Object.ur [as checkAndUpdateView] (vendor.bundle.js:566)
    at t.detectChanges (vendor.bundle.js:643)
    at vendor.bundle.js:622
    at Array.forEach (<anonymous>)
    at e.tick (vendor.bundle.js:622)
b @ vendor.bundle.js:447
vendor.bundle.js:447 ERROR TypeError: Cannot read property 'changePasswordTitle' of null
    at e._next (vendor.bundle.js:4)
    at e.__tryOrUnsub (vendor.bundle.js:1059)
    at e.next (vendor.bundle.js:1059)
    at e._next (vendor.bundle.js:1059)
    at e.next (vendor.bundle.js:1059)
    at XMLHttpRequest.a (vendor.bundle.js:856)
    at e.invokeTask (polyfills.bundle.js:43)
    at Object.onInvokeTask (vendor.bundle.js:475)
    at e.invokeTask (polyfills.bundle.js:43)
    at t.runTask (polyfills.bundle.js:43)

**Comment by Israel-94** [comment]
@unquietwiki try using the parent folder of `wwwroot` to run the application

**Comment by unquietwiki** [comment]
@Israel-94 That part's fine. I was checking over the JS debugger + source some more. webpack.config.js has two unused constants; one of which involves "ClientApp" (which I believe this all runs under). There's also an excessive repeat of the Google Angular license in the final output.

```
const realNodeModules = fs.realpathSync(nodeModules)
const genDirNodeModules = path.join(process.cwd(), 'ClientApp', '$$_gendir', 'node_modules')
```

**Comment by unquietwiki** [comment]
@geoperez @Israel-94 it looks like you more or less fixed this original bug; and my attempt to help fix the compiling issue has turned into its own thing. It also looks like you're working on that angle as well, so I've opened up #134 , and will close this issue. Thank you. 👍
