### ISSUE TITLE
Separate logic from PasswordController

### ISSUE THREAD

**Issue by geoperez** [unosquare/passcore#131]
Create a new class to provide basic change password logic, and inject it directly to the PasswordController.

**Comment by geoperez** [comment]
Create interface `IPasswordChangeProvider` and register your implementation as singleton with options.

Reference: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-2.0

**Comment by unquietwiki** [comment]
For issue #134 , I ended up merging in the password validator logic, to deal with some Angular 5 requirement. I also noticed that will null checking on, there were complaints about the HTML file having possible nulls. Apparently, the new Angular is supposed to fix that, but I wasn't prepared to attempt a fix.

http://blog.ninja-squad.com/2018/01/11/what-is-new-angular-5.2/
