### ISSUE TITLE
User with Roaming Profile

### ISSUE THREAD

**Issue by SK2500** [unosquare/passcore#14]
after passwort change the Roaming Profile was created on the webserver. Its possible to change password without create roaming profile on web server.

**Comment by mariodivece** [comment]
Maybe try disabling the automatic context strategy? Please read the section on Troubleshooting in the README file. Let me know if this works.
![image](https://cloud.githubusercontent.com/assets/351978/14062714/de1c5d0e-f36e-11e5-9d66-27c7d640f9fa.png)

**Comment by mariodivece** [comment]
@SK2500 Did this work ok?

**Comment by SK2500** [comment]
Yes this work for me. Thank you. But in your readme file i couldn't assign my problem to your description.
