### ISSUE TITLE
Suggestion: Coverty Scan project support

### ISSUE THREAD

**Issue by unquietwiki** [unosquare/passcore#140]
@geoperez , since you're project lead on this, you might find this useful in maintaining this and your other code bases.

https://scan.coverity.com/

**Comment by geoperez** [comment]
https://travis-ci.org/unosquare/passcore/builds/373472863

**Comment by geoperez** [comment]
I don't know if you can navigate this link: https://scan.coverity.com/projects/unosquare-passcore

**Comment by geoperez** [comment]
```
Tarring Coverity Scan Analysis results...
Uploading Coverity Scan Analysis results...
Coverity Scan upload failed: Build successfully submitted..
travis_time:end
```

Something is failing...

**Comment by unquietwiki** [comment]
@geoperez I can't seem to access the Coverity page for the project.

Related, when I was reviewing code analyzers, someone on Reddit suggested https://github.com/JosefPihrt/Roslynator as a useful tool.
