### ISSUE TITLE
Requires email address format for username

### ISSUE THREAD

**Issue by hkelley** [unosquare/passcore#142]
Not all user IDs will have email.   Perhaps this section in  passcore/src/Unosquare.PassCore.Web/ClientApp/app/change-password/app.change-password.ts   could be made optional.

const emailRegex = /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/;
 . . . .
 // Form Controls
  FormGroup = new FormGroup({
    username: new FormControl('', [Validators.required, Validators.pattern(emailRegex)]),
    currentPassword: new FormControl('', [Validators.required]),
    newPassword: new FormControl('', [Validators.required]),
    newPasswordVerify: new FormControl('', [Validators.required])
}, PasswordValidator.MatchPassword);

**Comment by geoperez** [comment]
We are addressing this issue in issue #134
