### ISSUE TITLE
Suggestion: attempt to reduce the amount of DLLs & cruft output

### ISSUE THREAD

**Issue by unquietwiki** [unosquare/passcore#143]
In the builds per work on #139 , it seems like a lot of the DLLs would never be used by the application. Apparently MS / Mono-team has a method for doing this.

- https://www.hanselman.com/blog/ExperimentalReducingTheSizeOfNETCoreApplicationsWithMonosLinker.aspx
- https://github.com/dotnet/core/blob/master/samples/linker-instructions.md

**Comment by geoperez** [comment]
Out of scope.
