### ISSUE TITLE
Page never loads beyond "Loading Pass core "

### ISSUE THREAD

**Issue by hkelley** [unosquare/passcore#144]
I don't see any errors in the event viewer and I don't see any log data being written.   Where else can I look for clues?   The worker process and application process seem to be running normally.

Name	PID	Status	User name	CPU	Memory (private working set)	Description
Unosquare.PassCore.Web.exe	5796	Running	Passcore	00 	17,412 K	Unosquare.PassCore.Web
w3wp.exe	2076	Running	Passcore	00 	4,404 K	IIS Worker Process

**Comment by geoperez** [comment]
Try to open Chrome Debugger and check what network error are you receiving.
