### ISSUE TITLE
compatible with IIS 7 ?

### ISSUE THREAD

**Issue by pinoyoutdoor** [unosquare/passcore#145]
i have a problem with web.config file, is it compatible with IIS7.5?

in browser is HTTP Error 500.19 - Internal Server Error (This error occurs when there is a problem reading the configuration file for the Web server or Web application.)

in IIS Manager Configuration Editor = The data is invalid

pls. help me...

**Comment by stevenmcastano** [comment]
I'm having the exact same problem as well.

**Comment by geoperez** [comment]
I don't have access to an IIS7, so I can't tell you if it can work or not.

**Comment by stevenmcastano** [comment]
I've gotten it to load by pointing the web site config to c:\passcore\wwwroot, now that site starts to load, but it can't find latin.woff2 and one other file so I basically get an outline of the screen with no content.

**Comment by geoperez** [comment]
You need to use the parent folder because wwwroot is just a subfolder in the website.

**Comment by stevenmcastano** [comment]
If I switch to the root directory, I got back to the error screens @pinoyoutdoor listed above. Also, my older passcore 2 site is working with the root pointed to wwwroot

**Comment by avm5689** [comment]
+1 on this, too. Having the same issue as @stevenmcastano

**Comment by avm5689** [comment]
Figured out my issue, might help yours. Had to download this specific ASP.NET Hosting Core package: https://aka.ms/dotnetcore-2-windowshosting

**Comment by unquietwiki** [comment]
@stevenmcastano @avm5689 @pinoyoutdoor Are all of you using the new build yet? That, with the .NET Core hosting install; should work out.

**Comment by pinoyoutdoor** [comment]
@avm5689 thanks...working ok now as of initial test after install...

**Comment by JoeArcher007** [comment]
I know this is a closed request, but I ran into this issue as well. It's a Windows Server 2008 R2. I followed the instructions on the main page but was getting the same issue with the 500.19. Using the suggestion from @avm5689 to download the specific version of .NET Core 2.0.8 worked and I'm now able to see the webpage.
