### ISSUE TITLE
update of ng-recaptcha for angular 6

### ISSUE THREAD

**Issue by Israel-94** [unosquare/passcore#146]
* ng-recaptcha need to be updated to use in angular 6
* meanwhile rxjs-compat is going to be used

**Comment by geoperez** [comment]
Add reference to the external issue please

**Comment by unquietwiki** [comment]
Also found this. https://github.com/DethAriel/ng-recaptcha/issues/107

**Comment by geoperez** [comment]
@Israel-94 you can continue with this issue please.
