### ISSUE TITLE
Stuck at Performing first-run npm install

### ISSUE THREAD

**Issue by VTEC17** [unosquare/passcore#148]
Hi, 

I downloaded the source code for 3.0.2 and I'm trying to run this command: dotnet publish --framework net461 --output "<path>" --configuration Release but it hangs at "Performing first-run npm install". Is this normal? Should I just wait? Or are there other things to check.

Thanks

**Comment by VTEC17** [comment]
Ok so I figured out that proxy settings were stopping it from downloading dependencies which is what is stopping it from compiling. I've tried modifying them but I'm still not getting anywhere.

Is it possible to append the domain without modifying the passwordcontrol.cs file? If not, is it possible to compile this on another device and then copy that back to the server that this is running on?

Thanks

**Comment by VTEC17** [comment]
Awesome. Just installed and tested it and it works. Thanks for your work on this.

**Comment by unquietwiki** [comment]
@VTEC17 @geoperez Good to hear! Closing ticket.
