### ISSUE TITLE
Configuration issue with Windows Server 2016 and iis 10 ?

### ISSUE THREAD

**Issue by digrouz** [unosquare/passcore#152]
Hello,

I did follow the README instruction with the last release 3.1 on Windows Server 2016 which comes with IIS 10 if i'm correct. 

I extracted the release to **C:\inetpub\PassCore** and I made point the physical path of the ISS web app point there and then I get an *500 http error*. 

I thought It might be logic to make point the physical path of the ISS web app **C:\inetpub\PassCore\wwwroot** so I tried and got a page with the block of the app but without any text.

Are the instructions up-to-date ? Can you point me where I'm wrong?

Note that I'm not an IIS administrator and I did follow blindly your instructions :)

**Comment by kenzoawa** [comment]
Did you download the source code or the compiled code ? 
If you have the compiled code you need to point to the pass-core master folder, the parent folder of the wwroot folder.

**Comment by digrouz** [comment]
I did download https://github.com/unosquare/passcore/releases/download/3.1.0/Passcore310.zip

**Comment by kenzoawa** [comment]
> If you have the compiled code you need to point to the pass-core master folder, the parent folder of the wwroot folder.

**Comment by digrouz** [comment]
but if I do that I get a 500

**Comment by kenzoawa** [comment]
If you find an HTTP Error 502.5, ensure you have installed .NET Core Runtime 2.0.6 / SDK 2.1.2, or better.
    If you find an HTTP Error 500 you can try
        Press Win Key+R to Open Run Window
        in the Run Window, enter "OptionalFeatures.exe"
        in the features window, Click: "Internet Information Services"
        Click: "World Wide Web Services"
        Click: "Application Development Features"
        Check the features.
    If you / your user's current password never seems to be accepted for reset; the affected person may need to use a domain-connected PC to login and reset their password on it first. Updated group policy settings could be blocking user changes, until a local login is completed.

**Comment by geoperez** [comment]
@digrouz any update?

**Comment by korolevgena** [comment]
The same story. I`ve downloaded the compiled code and get the 500 error

**Comment by Override92** [comment]
The same issue for me. It says HTTP-Error 500.19 - Internal Server Error. 

- Module IIS Web Core
- Handler undefined
- Errorcode 0x8007000d
- Configurationfile \\?\C:\inetpub\wwwroot\Passcore\web.config
- Configurationsource: -1: 0:

**Comment by unquietwiki** [comment]
Did you guys create a non .NET AppPool to run the app in? It seems counter-intuitive: but the app is more or less self-hosted via a Kestrel instance. And you do need the hosting instance.

- https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.1&tabs=aspnetcore2x
- https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.1.0-download.md

**Comment by Override92** [comment]
@unquietwiki 
I created an AppPool for Passcore and selected "no managed code".
I also installed the latest version of .NET Core SDK 2.1.300 x64.

**Comment by unquietwiki** [comment]
@Override92 Hmmm... one other thing you can try doing, is edit the index.html file, and have it match the target URL of your install; that especially helps in re-write situations.

**Comment by narmoucha** [comment]
Please I don't know what to download and where to put , which version
I need detailed guide , if any one can teamview my pc and show me how to do it ?

**Comment by Override92** [comment]
I solved the problem for me. Somewhere I read that the Hosting Bundle is included in the SDK. But it obviously is not. So after I installed the Hosting [Bundle](https://www.microsoft.com/net/download/thank-you/dotnet-runtime-2.1.0-windows-hosting-bundle-installer) it worked.

**Comment by Marvo2011** [comment]
I have the same issue.

`Protokollname: Application
Quelle:        IIS AspNetCore Module
Datum:         15.06.2018 10:35:02
Ereignis-ID:   1000
Aufgabenkategorie:Keine
Ebene:         Fehler
Schlüsselwörter:Klassisch
Benutzer:      Nicht zutreffend
Computer:     #############
Beschreibung:
Application 'MACHINE/WEBROOT/APPHOST/PASSCORE WEBSITE' with physical root 'C:\WWW\PassCore321\' failed to start process with commandline 'dotnet .\Unosquare.PassCore.Web.dll', ErrorCode = '0x80070002 : 0.`

**Comment by digrouz** [comment]
Adding the hosting bundle solved my issue.
