### ISSUE TITLE
Capital letters not allowed in USERNAME field

### ISSUE THREAD

**Issue by chrisb7710** [unosquare/passcore#154]
The RegEx doesn't contain any capital letters..
File: app.change-password.ts
Line: 18

What's written:
const usernameRegex = /^[a-z0-9._-]{3,40}$/; // Maybe find a better regex

This needs to be:
const usernameRegex = /^[a-zA-Z0-9._-]{3,40}$/; // Maybe find a better regex

**Comment by Israel-94** [comment]
There is already capital letters on the regex
https://github.com/unosquare/passcore/blob/master/src/Unosquare.PassCore.Web/ClientApp/app/change-password/app.change-password.ts#L18
