### ISSUE TITLE
Update to ASP.NET Core 2.1

### ISSUE THREAD

**Issue by Israel-94** [unosquare/passcore#155]
**Is your feature request related to a problem? Please describe.**
None, just update to ASP.NET Core 2.1

**Describe the solution you'd like**
Update to ASP.NET Core 2.1

**Comment by unquietwiki** [comment]
@Israel-94 https://docs.microsoft.com/en-us/aspnet/core/migration/20_21?view=aspnetcore-2.1 might be useful.
