### ISSUE TITLE
Support AUTH_USER (REMOTE_USER) to prefill/restrict username

### ISSUE THREAD

**Issue by finalbeta** [unosquare/passcore#157]
Hello, I have a usibility (security) request. 

Use case: Protect the loginform using basic auth. Have a proxy (loadbalancer) that send the users domain credentials in the HTTP header (Basic auth as most know it) for authentication. 

It would be nice if the config had an option to allow the user credentials to be filled in by (and restricted to) the USER_AUTH global IIS variable ( https://msdn.microsoft.com/en-us/library/ms524602%28v=vs.90%29.aspx?f=255&MSPPError=-2147217396 )

**Comment by geoperez** [comment]
I understand what you need, but we can't give you support. We are trying to remove the dependency of IIS and make PassCore self-contained, so there won't be support for Windows Authentication.
