### ISSUE TITLE
Passcore API

### ISSUE THREAD

**Issue by finalbeta** [unosquare/passcore#158]
Hi, passcore solves an important problem by providing a web interface to change users password. 
It also does some effort integrating into 3th party applications by allowing to set the user inside the URL. 
My question may be out of scope (but still serves the same goal). 

I would like to request to be able to change the password of the user using a single HTTP(s) POST call to the service. One could integrate the application directly into a 3th party application using a standard JSON to provide the username/previous password/new password.

**Comment by geoperez** [comment]
Yes, you can. You can check the HTTP Post [here](https://github.com/unosquare/passcore/blob/master/src/Unosquare.PassCore.Web/Controllers/PasswordController.cs#L49). You only need serialize with JSON a [ChangePasswordModel](https://github.com/unosquare/passcore/blob/master/src/Unosquare.PassCore.Web/Models/ChangePasswordModel.cs) to use it.

The only downside is that you have to disable Recaptcha.

Usually, you will send the following HTTP Post request to `/api/password`:

```json
{
	"username": "",
	"currentPassword": "",
	"newPassword": "",
	"newPasswordVerify": ""
}
```
