### ISSUE TITLE
Validation on username is too strict

### ISSUE THREAD

**Issue by finalbeta** [unosquare/passcore#159]
**Describe the bug**
In active directory there is no restriction to have a one or two letter username. We (really smal company) use our initials. The form doesn't let a user change his password if the username is not at least 3 characters long. 

**Expected behavior**
The form should allow one or two letter usernames

**Comment by geoperez** [comment]
Sure, we should move the email and username regex to a Setting.

**Comment by Israel-94** [comment]
@finalbeta there would a new version tomorrow where you can modify your own regex to adapt your needs, just change the regex field on the appsetings.json file

**Comment by finalbeta** [comment]
Hi Israel, 

I'm using the binary builds at the moment. You mean a bin will be released?

**Comment by geoperez** [comment]
Yes, a new binary version will be released today.
