### ISSUE TITLE
how to configure

### ISSUE THREAD

**Issue by narmoucha** [unosquare/passcore#162]
Please I don't know what to download and where to put , which version 
I need detailed guide , if any one can teamview my pc and show me how to do it ?

**Comment by geoperez** [comment]
![image](https://user-images.githubusercontent.com/1775792/41412617-3636cc76-6fa6-11e8-80d6-cf0ba7f8576f.png)

Some ground rules:

1 - Don't post your question in other threads.
2 - Read the entire [Installation guide](https://github.com/unosquare/passcore#installation-on-iis), then if you have a specific question reach us.
3 - Don't ask for tech support. This is an open source community.

**Comment by narmoucha** [comment]
cool pic and thank u for answering
but for the passcore_master there is no wwwroot in the zip and the guide tell to point to it 
I'm confused how u could run it 
can u help me

**Comment by narmoucha** [comment]
the guide says : Important: Make sure the Physical path points to the parent folder which is the one containing the files, logs and wwwroot folders.

where is it in the zip ?

**Comment by geoperez** [comment]
The zip url: https://github.com/unosquare/passcore/releases/download/3.2.1/PassCore321.zip

**Comment by narmoucha** [comment]
Thanks, i will try this version

**Comment by narmoucha** [comment]
it didn't work

**Comment by geoperez** [comment]
We released a PowerShell script, you can check the README file.

**Comment by unquietwiki** [comment]
@narmoucha if you are still having trouble, here is what @geoperez was talking about. https://github.com/unosquare/passcore#powershell-installer ; you'll need to delete your old install folder & IIS AppPool first. Thanks.

**Comment by unquietwiki** [comment]
Just realized #173 was also open. Closing this one.
