### ISSUE TITLE
Error when using "CheckRestrictedAdGroups":true,     "RestrictedADGroups": [..."

### ISSUE THREAD

**Issue by elblindo** [unosquare/passcore#163]
doing some changes in Unosquare.PassCore.PasswordProvider to Negoiate security settings instead of simplebind I'm able to connect to AD 2012 R2 with Ldap Port 636 instead of 389 and change passwords for users, as long as the option "CheckRestrictedAdGroups" is set to :false
After changing it to true and even set only one Group with "RestrictedADGroups": ["Domain Admins"] 
I got error "The server is not operational. Name: FQDN of one DC in Domain " or "
The specified directory service attribute or value does not exist."

**Expected behavior**
Would be able to use restricted groups as mentioned in description and readme

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Server 2012 R2 x64
 - Browser 
  chromium 62
  firefox 52.8 ESR
  Iexplorer 11

**Comment by geoperez** [comment]
Can you post your changes to PasswordProvider?

**Comment by elblindo** [comment]
I changed in passwordchangeprovider. cs to this
`            if (_options.UseAutomaticContext)
            {
                ContextOptions options = ContextOptions.Negotiate | ContextOptions.SecureSocketLayer;
                principalContext = new PrincipalContext(
                    ContextType.Domain,
                    null,
                    "dc=xxx,dc=xxxxxxxxm,dc=xx",
                    options);
            }
            else
            {
                ContextOptions options = ContextOptions.Negotiate | ContextOptions.SecureSocketLayer;
                principalContext = new PrincipalContext(
                    ContextType.Domain,
                    $"{_options.LdapHostname}:{_options.LdapPort}",
                    "dc=xxx,dc=xxxxx,dc=xx",
                    options,
                    _options.LdapUsername,
                    _options.LdapPassword);
            }
`

the line with dc=xxx,... is a dirty hack, caused by a ms artikel about errors when using  System.DirectoryServices.AccountManager, the other changes are according to the kb articles describing ldaps connect with  System.DirectoryServices.AccountManager 


regards

**Comment by elblindo** [comment]
Hi,

problem had bin fixed with these changes: https://github.com/elblindo/passcore/tree/elblindo-patch-1, it now runs as unprivileged user and can use allowed/forbidden groups 

Thanks for your advices
