### ISSUE TITLE
get a blank page with no writing/words

### ISSUE THREAD

**Issue by robina80** [unosquare/passcore#164]
hi all,

i have installed passcore on windows server 2012 R2 with IIS and on another machine when i access the webpage i get a blank page with no caption words/writing

https://s8.postimg.cc/5ssczuoyt/passcore.png

am i doing something wrong?

cheers,
rob

**Comment by geoperez** [comment]
Double check the installation guide, maybe you are not using the correct folder.

**Comment by robina80** [comment]
i have put the root passcore folder in the inetpub/wwwroot/PassCore321

do i need to do this command  -

dotnet publish --configuration Release --runtime win-x64 --output "<path>"

**Comment by geoperez** [comment]
If you downloaded the ZIP file with the compiled source code, you don't need to run dotnet publish.

**Comment by robina80** [comment]
Yes i did use the binary, i extracted the zip

**Comment by robina80** [comment]
Do i put passcore folder here-

inetpub/wwwroot/PassCore321

Or here-

inetpub/PassCore321

**Comment by robina80** [comment]
lol, i needed to install visual first then .net core and all is good
