### ISSUE TITLE
Error 502.5 - Process Failure. No logs

### ISSUE THREAD

**Issue by Plop** [unosquare/passcore#166]
Hi,

I've been trying to run PassCore for a few hours now, and I can't seem to make it work.
I'll try to put a maximum of details. Using PassCore 3.2.1On Windows Server 2012 R2 Standard.
I've installed .NET Core Runtime 2.1.0 AND SDK 2.1.300.

The Application Pool is configured as described in the installation steps, and the website too. The binding is done with the correct certificate.
I've changed stdoutLogEnabled to true in the web.config file : 

`    <aspNetCore processPath="dotnet" arguments=".\Unosquare.PassCore.Web.dll" stdoutLogEnabled="true" stdoutLogFile=".\logs\stdout" />`

For the appsettings.json file : 
```
"Logging": {
    "IncludeScopes": true,
    "LogLevel": {
      "Default": "Debug",
      "System": "Debug",
      "Microsoft": "Debug"
    }
  },
  "PasswordChangeOptions": {
    "UseAutomaticContext": false,
    "LdapHostname": "hostname",
    "LdapPort": 389,
    "LdapUsername": "username",
    "LdapPassword": "password",
    "CheckRestrictedAdGroups": true,
[...]
"AppSettings": {
    "EnableHttpsRedirect": false,
    "RecaptchaPrivateKey": "", // ReCAPTCHA private key: replace this!
[...]
      "Recaptcha": {
        "IsEnabled": false,
[...]
"DefaultDomain": "domain.tld"
[...]
```

Everything else is untouched.
The folders for PassCore and logs are not in read-only. But there is absolutely no logfile created.
The path for the PassCore folder is C:\inetpub\PassCore321
When I test the connection when I add the website, everything is fine, authentication and authorization are green.

I'm not sure what I'm missing now, and without the logs I can't diagnose the issue.

Thanks for your help

**Comment by geoperez** [comment]
Did you setup the application pool as No Managed Code?

**Comment by Plop** [comment]
Yes ! Here are some screenshots : 

Step 4 : 
![image](https://user-images.githubusercontent.com/876470/41645336-f65703bc-7470-11e8-9e7a-bc1cac3c2f3b.png)


Step 6 : ![image](https://user-images.githubusercontent.com/876470/41644379-27516924-746e-11e8-9d0b-f9d7a1869341.png)

Step 7 : 
![image](https://user-images.githubusercontent.com/876470/41644423-4a19ea76-746e-11e8-8583-9bb662557749.png)

Step 9 :
![image](https://user-images.githubusercontent.com/876470/41644733-41c539c4-746f-11e8-8bbc-b7322988648d.png)

Step 10 : ![image](https://user-images.githubusercontent.com/876470/41644783-6b93fa2e-746f-11e8-8de6-f8415e4bfb19.png)

Error : 
![image](https://user-images.githubusercontent.com/876470/41645281-cb121aa2-7470-11e8-9ebe-63bc81fede69.png)

**Comment by geoperez** [comment]
What do you get if you try to run the application from console?

`C: \inetpub\PassCore321\>dotnet Unosquare.PassCore.Web.dll`

**Comment by Plop** [comment]
It seems to be running fine, I got a "Application started", and no error.
I've done a full reboot of the server, and now I have the PassCore UI. I don't really get what happened. Still no logfile though.

And now I got this error "The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)"... I've never had this error with the older versions of PassCore, am I missing something ?
Thanks

**Comment by unquietwiki** [comment]
@Plop @geoperez There are a dozen different things about that error; all suggesting Windows Firewall. Maybe add exceptions for IIS and/or Unosquare.PassCore.Web.dll ?

**Comment by unquietwiki** [comment]
@Plop Please go over https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.1&tabs=aspnetcore2x if you haven't already: might help you out.

**Comment by Plop** [comment]
It seems that the WMI-In rule on the server was disabled. After enabling it, the RPC error disappeared.
But now I got a "Exception has been thrown by the target of an invocation." error... Even after a full server reboot.

I checked in the past issues (like this one https://github.com/unosquare/passcore/issues/77 ) for this error, but the server and the IIS only use one language, which is english. I still don't get any logs, and I have no clue of what could be wrong...

Thanks for your help

**Comment by unquietwiki** [comment]
No problem @Plop  . A Google search on your new error came up with https://blogs.msdn.microsoft.com/vsnetsetup/2016/04/13/exception-has-been-thrown-by-the-target-of-an-invocation/ & https://www.spiria.com/en/blog/desktop-software/exception-has-been-thrown-target-invocation-error ; see if those help!

**Comment by elblindo** [comment]
i had this error when something in appsettings.json was misconfigured (e. g. required quotation of group names, required "," at the end of all members of enumeration , but not the last or something similar.

**Comment by geoperez** [comment]
@Plop did you check your appsettings.json file?

**Comment by Plop** [comment]
Yes I did, but I haven't found any error.
I've tried to take a new one and change only the relevant settings, but it's the same. Here it is : https://gist.github.com/Plop/452276149d0e7831450bc207e27d5e9f

I've also checked the link unquietwiki provided, and done a few Google searches, but can't seem to find anything relevant...

**Comment by bringmeict** [comment]
Hi @Plop I've resolved the no log issue by giving the appropriate permissions on the stdout log folder.
![image](https://user-images.githubusercontent.com/40795361/42219947-cce3f302-7ecd-11e8-8ea7-a6645ecee65e.png)
by issuing this command:
icacls <your files folder path> /grant "IIS AppPool\<your application pool name>":M /T

**Comment by geoperez** [comment]
We should add this to the README file.

**Comment by Plop** [comment]
I've tried using the Powershell script, but I got some errors : 
![image](https://user-images.githubusercontent.com/876470/42221325-fc1950fa-7ed1-11e8-9d4c-4741139b14db.png)

I don't have any files in C:\passcore, except appsettings.json, but empty. I tried to put my json file, but it doesn't seem to be working.

For the permissions, I tried the following command, after using the Powershell script (which created an Application Pool called "Passcore Pool PS") : 
`icacls /grant "IIS AppPool Passcore Pool PS":M /T`
But I got this result : First parameter must be a file name pattern or "/?"

Did I miss something ?

Thanks for your help

**Comment by geoperez** [comment]
You need at least PowerShell v5 to run the script. I'll update the README file.

**Comment by bringmeict** [comment]
@plop: you need to pass a directory to icacls. So if you're passcore is served from c:\inetpub\Passcore321 you should use the following command
`icacls C:\inetpub\PassCore321\logs\stdout /grant "IIS AppPool\Passcore Application Pool":M /T`
note: you need to create the \log\stdout directory yourself and then assign permissions
note2: dont forget the backslash after IIS AppPool

**Comment by bringmeict** [comment]
I solved the 502.5 error by installing https://www.microsoft.com/net/download/thank-you/dotnet-runtime-2.1.1-windows-hosting-bundle-installer (2.1.1) over 2.1.0

**Comment by unquietwiki** [comment]
I'm going to go ahead and close this. @geoperez & I got the README updated with all the discoveries of these past few tickets. Thanks all!

**Comment by Plop** [comment]
Everything is working fine now ! With PowerShell 5, the script ran perfectly. I also have logfiles after the icacls command.

Thanks a lot for your help, and your work !
