### ISSUE TITLE
passcore to send out password reminders to users

### ISSUE THREAD

**Issue by robina80** [unosquare/passcore#167]
hi all,

passcore is awesome, hands down really easy to use

would it be possible or can you already set up passcore to send out emails to users to reset thier passwords as we do a 3 month policy and normally users forget to change their passwords as they dont get advanced warning to do so

cheers,
rob

**Comment by robina80** [comment]
for now im using "netwrix password expiration notifier"

**Comment by unquietwiki** [comment]
- https://dotnetcoretutorials.com/2017/11/02/using-mailkit-send-receive-email-asp-net-core/
- https://github.com/jstedfast/MailKit

@geoperez Apparently the SMTP library is deprecated, and "Mailkit" is considered a good replacement.

**Comment by robina80** [comment]
Can i install this on my windows server 2012 r2 where i have installed passcore on

**Comment by geoperez** [comment]
This feature is out of scope.
