### ISSUE TITLE
Post Installation Issue

### ISSUE THREAD

**Issue by MDrakes** [unosquare/passcore#169]
**Describe the bug**
Just installed followed the guide and that is what I am seeing on the browser, how to fix it?
I have no programing skills, and just tried to follow the tutorial.

**Screenshots**
![captura de tela 2018-06-21 as 14 33 54](https://user-images.githubusercontent.com/40471717/41735537-541e1f72-7560-11e8-8c0d-fde2ee30e0ce.png)

**Server (please complete the following information):**
 - Device: IIS 8
 - OS: Windows Server 2012 R2
 - Browser: All Browsers
 - Version 321

**Comment by unquietwiki** [comment]
@MDrakes https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-2.1&tabs=aspnetcore2x Give that a lookover please. Might not have the Hosting Core Bundle installed.

**Comment by MDrakes** [comment]
@unquietwiki 
Thanks for your reply.
There is any shorter guide to install it? I really got lost on it.

**Comment by unquietwiki** [comment]
@MDrakes https://www.microsoft.com/net/download/thank-you/dotnet-runtime-2.1.0-windows-hosting-bundle-installer

They don't make this easy. I'm presently unemployed as of the past Wednesday: might have a new job soon, but I may use some of the free-time to work on the self-hosting ticket. You're not the first to have this trouble.

**Comment by MDrakes** [comment]
@unquietwiki 

I have those installed:
dotnet-hosting-2.1.0-win
dotnet-runtime-2.1.0-win-x64
dotnet-sdk-2.1.300-win-x64

And the webpage still the same

**Comment by unquietwiki** [comment]
I'd check the application pool settings, and also edit the index.html file
to use the address of your website. F12 in the browser can show missing JS
calls.

**Comment by MDrakes** [comment]
That is my index.html:
`<!DOCTYPE html>
<html lang="en">

<head>
    
    <base href="/">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="unosquare, oss software, password change, active directory, mit license, password, account utilities, user account">
    <meta name="MobileOptimized" content="320">
    <meta name="description" content="PassCore is a self-service password change utility for Active Directory.">
    <meta name="author" content="Unosquare, LLC">
    <meta name="title" content="PassCore">
    <meta name="theme-color" content="#3f51b5">
    <meta name="msapplication-navbutton-color" content="#3f51b5">
    <meta name="apple-mobile-web-app-status-bar-style" content="#3f51b5">
    <meta property="og:image" content="assets/images/passcore-logo.png">
    <meta property="og:title" content="PassCore - Self-Service Password Change Utility">

    <link href="manifest.json" rel="manifest">

    <title>Loading . . .</title>
    <style>
        @font-face {
            font-family: 'Roboto';
            font-style: normal;
            font-weight: 400;
            src: local('Roboto'), local('Roboto-Regular'), url(assets/fonts/Roboto/latin.woff2) format('woff2'), url(assets/fonts/Roboto/Roboto-Regular.ttf) format('truetype');
            unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215;
        }

        body {
            font-family: 'Roboto', sans-serif;
            background-color: #fafafa;
            margin: 0;
            padding: 0;
        }
    </style>

    <link href="assets/styles/indigo-pink.css" rel="stylesheet" type="text/css">
    <link href="assets/favicon.ico" rel="shortcut icon">
</head>

<body>
    <app-root>
        <style>
            app-root {
                font-family: 'Roboto', sans-serif;
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100vh;
                font-size: 2em;
            }

            @keyframes dots {
                50% {
                    transform: translateY(-.4rem);
                }
                100% {
                    transform: translateY(0);
                }
            }

            .d {
                animation: dots 1.5s ease-out infinite;
            }

            .d-2 {
                animation-delay: .5s;
            }

            .d-3 {
                animation-delay: 1s;
            }
        </style>
        Loading Pass
        <strong class="core">core</strong>
        <span class="d">.</span>
        <span class="d d-2">.</span>
        <span class="d d-3">.</span>
    </app-root>
<script type="text/javascript" src="polyfills.bundle.js"></script><script type="text/javascript" src="vendor.bundle.js"></script><script type="text/javascript" src="main.bundle.js"></script></body>

</html>`

**Comment by unquietwiki** [comment]
Where you installed the program, look for the index file in a subdirectory,
and edit that. There's a comment where to make the change.

**Comment by MDrakes** [comment]
Its is under "C:\inetpub\PassCore\wwwroot"

**Comment by unquietwiki** [comment]
Yes. Edit that where it says to change the address to match your current
website. And please also verify you have an unmanaged appPool set to run in
that directory.

**Comment by MDrakes** [comment]
Do you mind to help me on Skype?
I am a bit lost to find it on the index.html

**Comment by MDrakes** [comment]
Well,
I have tried to edit the html file, but even so, still the same.

**Comment by MDrakes** [comment]
@unquietwiki,

I redid it from the start, and now it seems to be working, just testing if it will change the password now.

**Comment by MDrakes** [comment]
Well...

Now I managed to make it display the stuff.
Now I am trying to set the "appsettings.json" file, like the "DefaultDomain" and some translations.

But now when I try to change the password, I got this error:
![captura de tela 2018-06-21 as 18 02 13](https://user-images.githubusercontent.com/40471717/41745537-a0e7fcac-757d-11e8-8109-2a9fbf37aabb.png)
