### ISSUE TITLE
http redirect

### ISSUE THREAD

**Issue by reddare** [unosquare/passcore#17]
Hi! Is it possible to add http to https redirect in app?
I try all rewrite IIS rules but it have no effect, app did not load whis redirect rule.

**Comment by mariodivece** [comment]
I will implement this feature and add a setting in the next release based on this Stackoverflow.com answer: http://stackoverflow.com/questions/29477393/asp-net-5-dnx-redirect-to-https

**Comment by mariodivece** [comment]
The latest commit makes this possible. Closing issue. Feature will be available in next release.
