### ISSUE TITLE
can't make it work

### ISSUE THREAD

**Issue by narmoucha** [unosquare/passcore#173]
I get this image, any help !
![sans titre1](https://user-images.githubusercontent.com/22034834/41896402-cd33604e-7924-11e8-847b-9915f58892ea.png)

**Comment by geoperez** [comment]
We released a PowerShell script, you can check the README file.

**Comment by 0byt3** [comment]
Yeah, I got no luck on making it work either. Followed the README as far as I can tell, but not operational. Sad day.

**Comment by geoperez** [comment]
What issue did you get with the Powershell script?

**Comment by 0byt3** [comment]
I didn't use the script, I followed the Installation on IIS section and performed the manual steps.

**Comment by unquietwiki** [comment]
@0byt3 Can you verify that the appsettings.json file is set to use the correct "DefaultDomain" for your Active Directory? And did you install the [.NET 2.1 Web Hosting Bundle](https://www.microsoft.com/net/download/thank-you/dotnet-runtime-2.1.0-windows-hosting-bundle-installer) from Microsoft?

**Comment by unquietwiki** [comment]
Update on that last comment: some folks were saying you need the 2.1.1 update to resolve some issues.

https://www.microsoft.com/net/download/thank-you/dotnet-runtime-2.1.1-windows-hosting-bundle-installer

**Comment by geoperez** [comment]
Status?
