### ISSUE TITLE
We could not find your user account since v3.1

### ISSUE THREAD

**Issue by czKKill** [unosquare/passcore#174]
I've finally find some time to update this excellent tool to latest version from 3.0.2 (where it works fine). But since v3.1 (tried this and latest 3.2.1) I get every time "We could not find your user account error" with or without default domain set.
I've updated the .NET Core Hosting and Core to 2.1.1 and SDK to 2.1.301.
Running it on WS2016.

I've checked the stdout log but could not find any error there - please see here: [stdout_2740_2018738244.log](https://github.com/unosquare/passcore/files/2158380/stdout_2740_2018738244.log)

No errors in event log either. Is there any other log I could check? Any idea where could be the problem? As mentioned before - v3.0.2 is working fine (even with updated .NET).

**Comment by unquietwiki** [comment]
@czKKill Hey there. Did you recreate your appsettings.json file; and did you wipe & replace the contents of your old folder with the new version? You should backup your old .json file somewhere so you can copy back in stuff like your ReCaptcha codes.

**Comment by czKKill** [comment]
Hi @unquietwiki, I've copied over to the new file just the ReCaptha IDs and adjusted default domain. Please see old working config: [appsettings_302.json.txt](https://github.com/unosquare/passcore/files/2158550/appsettings_302.json.txt) and new: [appsettings_321.json.txt](https://github.com/unosquare/passcore/files/2158554/appsettings_321.json.txt)
Later I've commented out the default domain to try it with full username including domain.

**Comment by unquietwiki** [comment]
@czKKill Thank you for that. (ponders) I'm not sure the JSON will parse correctly with the DefaultDomain commented out. Try removing all the comments. Also, I would see the error you mention at the last place I worked: particularly on folks that haven't directly used the network since a Group Policy change. Might be related to #40 ; could also be related to #147 if user folders aren't permitted to be created on the server.

**Comment by czKKill** [comment]
@unquietwiki I've removed all comments, left the default domain enabled.
Regarding
- #40 I'm trying my own account what is not expired or set to force change
- #147 I'm able to login with this user locally on that server

I've done further debug and  found the problem - domain name. For some reason our primary domain name of something.domain.com doesn't work, but domain.com does. So I guess we can close this.

**Comment by bringmeict** [comment]
Can confirm, had the same issue. For me it was not clear from the documentation that you need to use your UPN domain instead of the Windows active directory domain, those two are totally different in our AD setup.

**Comment by unquietwiki** [comment]
Interesting that subdomains wouldn't work. But TBO I've never been given admin control of a mutli-level AD; so never would have caught that! I can try to update the JSON and/or README. Thank you @czKKill & @bringmeict
