### ISSUE TITLE
PassCore for AD Self-service Password Reset

### ISSUE THREAD

**Issue by maria-valen** [unosquare/passcore#177]
I am currently setting up Unosquare Passcore. I have extracted the Passcore.zip file and the Passcore-master. I have setup my site using IIS. Here's the problem, when I browse my site, it only shows like the image below: 

Here's what I'm running:
Windows Server 2012 R2 x64
IIS 8.5
Physical Path: C:\inetpub\passcore-master\src\Unosquare.PassCore.Web\wwwroot

Hoping for assistance. Thank you. 

![passcore d1](https://user-images.githubusercontent.com/41035416/42487809-408d4e90-8435-11e8-935c-c7057c9d866f.png)
![passcore d2](https://user-images.githubusercontent.com/41035416/42487810-40c70e8c-8435-11e8-9bb9-f92ea858e119.png)
![passcore site](https://user-images.githubusercontent.com/41035416/42487811-41445b62-8435-11e8-9fd1-31ff367fb2d7.png)

**Comment by Israel-94** [comment]
You downloaded the source code of the passcore, you need to download the binary release, you can follow the instructions on the README file.
