### ISSUE TITLE
Feature Request  - User can change / update their Information in selected fields.

### ISSUE THREAD

**Issue by wakhan007** [unosquare/passcore#18]
Thank a lot for making this application, This is exactly what I needed. 

Is it possible that you can add functionality that allows users to change/update their user fields in Active Directory on their own. For Example: telephone, department, title, manager etc. This will help us to keep the Active directory updated. There are no such application available in market for free. 

Regards,
Waqas Ahmed
waqas.ahmed@gmail.com

**Comment by mariodivece** [comment]
That's a good idea. I'll look into this.

**Comment by geoperez** [comment]
Out of scope.
