### ISSUE TITLE
Please enter a valid username

### ISSUE THREAD

**Issue by mishiago31** [unosquare/passcore#184]
Capital Letters are not allowed when typing the  Domain user?
"Please enter a valid username"

1. Just type the User with Capital Letter.

**Expected behavior**
Users always type their user with Capital Letter.

Passcore - 3.1.0.

Please Advise.

**Comment by Israel-94** [comment]
Hi @mishiago31, If you want to change this you need to download the source code and change on ClientApp/app/change-password/app.change-password.ts the line 18 from `const usernameRegex = /^[a-z0-9._-]{3,15}$/;`  to `const usernameRegex = /^[a-zA-Z0-9._-]{3,15}$/;` and then follow the "Installation on IIS" from step three if you want. Or you can try download the latest release, that have that configuration on the `appsettings.json` file

**Comment by stevenmcastano** [comment]
I'm running into a problem now myself... I have a few usernames that are over 15 characters long... do I still have to download the source code to change this? Or is it something there's a setting or some javascript I can easily change??

**Comment by geoperez** [comment]
Let's increment to 20. Is there any MSDN document related? @israel-94

**Comment by Israel-94** [comment]
@geoperez I found the [User Name Format](https://docs.microsoft.com/en-us/windows/desktop/secauthn/user-name-formats) and there is already incremented to 20 characters long in the recent versions.
@stevenmcastano for versions 3.2.1+ you can set your own regex for the username validation in the appsettings.json file
