### ISSUE TITLE
MSBUILD : error MSB1003: Specify a project or solution file.

### ISSUE THREAD

**Issue by elbrown99** [unosquare/passcore#189]
Hi,

I'm getting an error "MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file." when trying to do the dotnet publish command.

I'm not a developer but was excited to see the tool.  Unfortunately I can't get by this error.  I'm trying to install on Windows 2016.

Thanks for any help.
elbrown99

**Comment by geoperez** [comment]
Do you need to change the source code? If not, please try to download the binaries or use the PowerShell script to install.

If you still want to build the solution, you may need to download the source code from here: https://github.com/unosquare/passcore/archive/master.zip

You may need to install .NET Core SDK,

**Comment by elbrown99** [comment]
Really appriecate the quick feedback.  I don't need to change the code.  Like I said I'm not a developer, so I just need to copy the binaries to the wwwroot\passcore?

I did install the SDK.

**Comment by geoperez** [comment]
I suggest you use the guide [Installation on IIS](https://github.com/unosquare/passcore#installation-on-iis).

**Comment by geoperez** [comment]
Status?

**Comment by elbrown99** [comment]
Hi,

Thanks for the follow up.

I guess I ran into the situation of asking for help when I was desperate.
The clock ran out on me and I had to deliver the machine without a good
solution.

I was following the IIS instructions got tangled up with step 3, which I
now assume based on your response isn't required unless you modify the
code.  I hope to take another run at it when I'm back at the site in
several weeks.

Thanks

**Comment by geoperez** [comment]
Status?

**Comment by johnmelodyme** [comment]
According to Microsoft : 

```MSBuild Error MSB1003
12/01/2015
2 minutes to read
 

Specify a project or solution file. The current working directory does not contain a project or solution file.

If a project or solution file is not specified on the command line, MSBuild searches the current working directory for a file that has a file extension that ends in "proj" or "sln" and uses that file. The current working directory does not contain a file that has a file extension that ends in "proj" or "sln".

To correct this error
Go to the directory that contains the project file you want to build.

Specify either the full or relative path to the project file. For example, type msbuild c:\myapp\myapp.proj or msbuild ..\..\myapp\myapp.proj

If the project or solution file has a file extension that does not end in "proj", change the file extension so that it does end in "proj".```

**Comment by HessenL** [comment]
Hi, now i ran into the same issue. I downloaded the Passcore363 and installed the SDK. 
I wan´t to install the Passcore on C:\passcore\(*.json+ *.dll + wwwroot\...)

My Problem is the machine can´t access to the Internet. Is it Possible to change the Source into a local?

**Comment by geoperez** [comment]
You don't need internet to use dotnet sdk. Can you paste the command and output?

**Comment by mortezahaidari** [comment]
I had the same issue, i went to the directories through finder... double clicked the "filename.csproj" while having the IDE open. Built it, and it worked like a charm! :)
