### ISSUE TITLE
Complexity requirements

### ISSUE THREAD

**Issue by theofficefan** [unosquare/passcore#192]
No matter what user I try to change its password, I get the following error:

"The password does not meet the password policy requirements. Check the minimum password length, password complexity and password history requirements. (Exception from HRESULT: 0x800708C5)"

I am far exceeding the complexity requirements (as well as trying completely different passwords) so this makes no sense.

**Comment by nikichcom** [comment]
I've fixed the same issue by setting the "UseAutomaticContext" to "false" in appsetting.json file. Hope this will help you.

**Comment by aaloise** [comment]
@nikichcom when I set it to false, I get the "RPC Server Unavailable" error

**Comment by geoperez** [comment]
Status?

**Comment by thekeagy** [comment]
Hello any status? I am not seeing the UseAutomaticContext in the appsetting.json file. I am having same issue of password complexity

**Comment by geoperez** [comment]
Check #233

> If I logon to a local domain computer, and I try using PowerShell Set-ADAccountPassword, I get the same error. Group Policy is set to enforce only a 7 character length, complexity rules are otherwise disabled, and I verified this with Get-ADDefaultDomainPasswordPolicy.

> After a bit of troubleshooting, I found that the password history was set to 24, and it was simply that users were trying to reuse an old password, so the error was in fact correct.
