### ISSUE TITLE
Adding pure LDAP Password Provider -- support Linux hosting

### ISSUE THREAD

**Issue by ebekker** [unosquare/passcore#195]
I have implemented a [pure LDAP-based Password Change Provider](https://github.com/ebekker/passcore) using the [Novell LDAP port](https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard) to .NET Standard.

I've successfully deployed and tested it on both Windows and Linux hosts (CentOS7).

I did not want to disturb the existing code base too much so the current integration uses conditional compilation to produce a build of PassCore that is strictly LDAP.

If this is something others are interested in, I can submit a PR to integrate this back upstream but it might be useful to add some sort of multi-provider support (i.e. config-driven provider selection) so as not to produce multiple builds.

**Comment by geoperez** [comment]
That's great. Yes, you can add a new assembly using your provider. The current architecture allows having multiple providers.

You may need to create a similar assembly as `Unosquare.PassCore.PasswordProvider` and implement the interface `IPasswordChangeProvider.cs` from `Unosquare.PassCore.Common`. It's a single method interface very easy to implement with the following signature:

`ApiErrorItem PerformPasswordChange(string username, string currentPassword, string newPassword);`

Then the `Startup` object (from `Unosquare.PassCore.Web`) in need to change the following line:

`services.AddSingleton<IPasswordChangeProvider, PasswordChangeProvider>();`

To use your provider instead. I may need to add an application setting to change the provider by the JSON file.

**Comment by geoperez** [comment]
I didn't check your repo before to post the previous comment. Please submit the PR.
