### ISSUE TITLE
Server 2008 R2 / IIS 7.5 - Works as subdomain but not subfolder/app

### ISSUE THREAD

**Issue by syntax53** [unosquare/passcore#197]
**Describe the bug**
I want to setup it up as a subfolder / custom application.  I have made the change to the index.html as instructed (changing `<base href="/"> to <base href="/pass/">`) but the page just says on "Loading Passcore...".  The browser loads the index.html but gets 403 / forbidden codes on loading any of the java or css files.  I don't see any errors in the application log or in the logs/stdout (I did configure the logging and logs do get created there).

Making no other changes other then deleting the subfolder/app and creating it as a subdomain and it loads right up.  I have to put it on a different port though because IIS 7.5 doesn't support SNI and I already have an SSL site running on this.

**Comment by geoperez** [comment]
@unquietwiki did you install PassCore as subfolder?

**Comment by syntax53** [comment]
Just to add, "works" on the subdomain isn't completely working either.  As I'm trying to customize and test it, I cannot get it to change any passwords.  I've tried with and without the LDAP configuration.  

One odd thing is it will not accept ANY username that contains an @ symbol.  It always errors with "enter valid username" (note: NOT enter valid 'email address').  I'm very familiar with regex and tried changing the options in the config to no avail.

If I try it without LDAP config I get nothing but "username could not be found."  With LDAP config the best I've gotten is "server is unwilling to process the request."

**Comment by geoperez** [comment]
What version are you using?

**Comment by syntax53** [comment]
3.3.0

**Comment by geoperez** [comment]
Can you try 3.5?

**Comment by syntax53** [comment]
Sorry I've already moved on to a different solution (developed our own)
