### ISSUE TITLE
Feature Request  - Password Reset Option with Security Questions

### ISSUE THREAD

**Issue by wakhan007** [unosquare/passcore#20]
Please add Password Reset Option as well through which users can reset their forgotten passwords by answering security questions.

**Comment by justbustr** [comment]
I agree that this would be an outstanding feature for PassCore to adopt, and would make this a much more powerful self-service tool (and a lot fewer IT support calls!).

**Comment by savaticus** [comment]
I too would love this feature. Maybe do a 2FA via sms text. Have the phone number populated via AD.

**Comment by ZioGuillo** [comment]
I think associated the email to the AD account and with that information send the link to reset the password.

**Comment by geoperez** [comment]
Sorry, but we are not including that feature.
