### ISSUE TITLE
Stuck on Loading Passcore

### ISSUE THREAD

**Issue by avm5689** [unosquare/passcore#205]
When attempting to load upgraded version of Passcore (was originally installed on v3.0.0), stuck at "Loading" screen. Chrome Console displays error messages: Uncaught referenceError: webpackJsonp is not defined (polyfills.bundle.js:1). Message also applies for vendor.bundle.js and main.bundle.js

Screenshot:
[https://i.imgur.com/9rNloNs.png](url)

Recycling the IIS application pool and restarting the IIS site has no effect. Any help would be much appreciated!

**Comment by unquietwiki** [comment]
Please backup your .json file that has your config; delete the contents of
the current install folder; copy in the new version. Alternatively, save
the .json config; wipe out whole setup; and use the Powershell script to
reinstall.

**Comment by veinom** [comment]
I'm having the same exact error ... did you ever find a solution?

I deleted the old webapp and installed to a new directory and edited the new appsettings.json file to put in the correct information - but it remains stuck exactly like in your screenshot.

**Comment by geoperez** [comment]
Can I close this issue?

**Comment by Jatwas** [comment]
Also getting the same error, except I managed to find that it seems to be stuck on a GET request for a password file. No such file exists, so it returns a 404 error in the network tab on firefox's developer tools:

![passcore](https://user-images.githubusercontent.com/45875732/50004430-0a26d480-ff9f-11e8-8260-427fcd6bc138.PNG)

Does anyone know why it's looking to **domain/api/password** when there is no file like this? The admin credentials needed in appsettings.json are in place, so why is it getting caught looking for a non-existent file?

**Comment by geoperez** [comment]
There is not a /api/password file, that route connects to the WebAPI. If the WebAPI is not responding is probably because IIS has the static files folder as root path. You need to change the root path to the folder containing the web app.
