### ISSUE TITLE
How to disable the captcha?

### ISSUE THREAD

**Issue by robmorin** [unosquare/passcore#210]
How can i disable the captcha? I cannot seem to find how in app settings file?

Thanks...

**Comment by geoperez** [comment]
You need to set an empty string in the `RecaptchaPrivateKey` setting.

**Comment by robmorin** [comment]
Ok thanks that worked..
Have a good one!

**Comment by geoperez** [comment]
Closing.

⭐️Please star this project if you find it useful!
