### ISSUE TITLE
Cannot disable chapta

### ISSUE THREAD

**Issue by Emil8250** [unosquare/passcore#211]
Hi, 

I've tried to disable the chapta by editting the appsettings.json and changing the Recaptcha from IsEnabled: true to  IsEnabled: false

When I change the setting, the chapta disappears and everything looks good, until I try to change my password and I get an error saying that it cannot verify that I'm not a robot - exactly as it would if I hadn't filled in a chapta. 

Is there a way to fix this? I've only tried hosting it on a IIS so far.

**Comment by geoperez** [comment]
Related to issue #210. 

> You need to set an empty string in the RecaptchaPrivateKey setting.

**Comment by Emil8250** [comment]
Thanks, worked like a charm!
