### ISSUE TITLE
multiple domains and offline password change

### ISSUE THREAD

**Issue by lp2019** [unosquare/passcore#214]
Hello guys,

Everything works fine but recently a client asked me if it was possible to change password outside of their site and with another domain.

For example:

- I changed the domain for the correct domain --- works fine
- change password with another domain (since this client has multiple domains *.pt and *.local)
- offline password change, is it possible?

I just added 

"DefaultDomain": "domain1.pt", "domain2.pt", "domain.local",// Set your default AD

cheers

**Comment by geoperez** [comment]
I don't understand the question. 

You are trying to have a common PassCore to serve internal and different domains but you want to use the DefaultDomain setting?

**Comment by lp2019** [comment]
> 
> 
> I don't understand the question.
> 
> You are trying to have a common PassCore to serve internal and different domains but you want to use the DefaultDomain setting?

that is correct, adn how about offsite? need to publicate at IIS ?

**Comment by geoperez** [comment]
Keeping status at #219
