### ISSUE TITLE
Installation and configuration steps on Linux

### ISSUE THREAD

**Issue by CleanHit** [unosquare/passcore#215]
As of version 3.4.0 it is possible to install the service on a Linux machine. Unfortunately I couldn't find any installation (with configuration) steps or any software dependencies for using passcore on Linux with apache2.

To make this more clear. Does using the Linux version means that I can configure the passcore to work on my Linux-Server with apache2 or does passcore only work using Windows 10 Pro or WIndows Server with IIS?

**Comment by CleanHit** [comment]
@geoperez Thank you for the link. So basically I must install the dotnet core 2.1.X runtime (maybe build) on my Linux to be able to run the Releases. I saw some other `ASP.net` app tutorial that uses the `dotnet` command to start a .dll file that starts a localhost Server on some port, I guess that I have to do the same on my Linux. 

Could you please provide me with the command sequence that I need to use to start the passcore app locally?

**Comment by geoperez** [comment]
Yes, you need `dotnet` exe to run the PassCore Dll. If you check this part (https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-apache?view=aspnetcore-2.1&tabs=aspnetcore2x#monitoring-the-app)

You need to call like PassCore something like this:

```
[Unit]
Description=PassCore

[Service]
WorkingDirectory=/var/aspnetcore/passcore
ExecStart=/usr/local/bin/dotnet /var/aspnetcore/passcore/passcore.dll
Restart=always
# Restart service after 10 seconds if the dotnet service crashes:
RestartSec=10
KillSignal=SIGINT
SyslogIdentifier=dotnet-example
User=apache
Environment=ASPNETCORE_ENVIRONMENT=Production 

[Install]
WantedBy=multi-user.target
```

**Comment by CleanHit** [comment]
@geoperez Thanks for the support, it worked. Do I have to setup the appsettings.json to work with my Microsoft AD or is it similar to a Windows passcore installation? I mean if my Linux server is domain-joined then passcore works out of the box.

**Comment by geoperez** [comment]
Yes, you need to fill your AD/LDAP server settings in the appseting.json before to use PassCore.

**Comment by CleanHit** [comment]
@geoperez Thanks for the help

**Comment by crsleeth** [comment]
@CleanHit Which .dll are you pointing to to run PassCore on Linux? I am attempting on Ubuntu 18.04 but running dotnet Unosquare.PassCore.Web.dll gets me
`Error:
  An assembly specified in the application dependencies manifest (Unosquare.PassCore.Web.deps.json) was not found:
    package: 'Microsoft.AspNetCore.Antiforgery', version: '2.2.0'
    path: 'lib/netstandard2.0/Microsoft.AspNetCore.Antiforgery.dll'`

Dotnet is on version 2.2.4.
