### ISSUE TITLE
how to amend insert username instead email address ?

### ISSUE THREAD

**Issue by royfooklye** [unosquare/passcore#217]
Hi Guys

how to amend insert username instead email address ?

{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Verbose",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
  "AppSettings": {
    "EnableHttpsRedirect":  false,
    "RecaptchaPrivateKey": "",
    "PasswordChangeOptions": {
      "UseAutomaticContext": true,
      "LdapHostname": "",
      "LdapPort": 389,
      "LdapUsername": "",
      "LdapPassword": ""
    },
    "ClientSettings": {
      "ShowPasswordMeter": true,
      "Recaptcha": {
        "IsEnabled": true,
        "SiteKey": "6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI", // Only for testing purpose
        "LanguageCode": "en"
      },
      "ApplicationTitle": "Self-Service Account Management Tools",
      "ChangePasswordTitle": "Change Account Password",
      "ChangePasswordForm": {
        "HelpTitle": "Help and Support",
        "HelpText": "If you are having trouble with this tool, please contact IT Support",
        "UsernameLabel": "Username",
        "UsernamePlaceholder": "username",
        "UsernameHelpblock": "Your organization's username",
        "CurrentPasswordLabel": "Current Password",
        "CurrentPasswordPlaceholder": "",
        "CurrentPasswordHelpblock": "Enter your current password",
        "NewPasswordLabel": "New Password",
        "NewPasswordPlaceholder": "",
        "NewPasswordHelpblock": "Enter a strong password. You can use <a href='http://passwordsgenerator.net/' tabindex='-1' target='_blank'>this tool</a> to help you create one.",
        "NewPasswordVerifyLabel": "Re-enter New Password",
        "NewPasswordVerifyPlaceholder": "",
        "NewPasswordVerifyHelpblock": "Enter your new password again",
        "ChangePasswordButtonLabel": "Change Password"
      },
      "ErrorMessages": [
        "System Error",
        "Field is required",
        "Fields don't match",
        "We could not find your user account",
        "The username and current password you provided are invalid",
        "Could not verify you are not a robot"
      ],
      "Alerts": {
        "SuccessAlertTitle": "You have changed your password successfully.",
        "SuccessAlertBody": "Please note it may take a few hours for your new password to reach all domain controllers.",
        "ErrorAlertTitle": "There was an error changing your password",
        "ErrorAlertBody": "Error Information: ",
        "ErrorPasswordChangeNotAllowed": "You are not allowed to change your password. Please contact your system administrator.",
        "ErrorInvalidCredentials": "You need to provide the correct current password."
      }
    }
  }
}

**Comment by royfooklye** [comment]
![image](https://user-images.githubusercontent.com/24204789/46134130-c14f6180-c274-11e8-8eb9-0d1f11903bf6.png)

**Comment by geoperez** [comment]
You need to set up the DefaultDomain setting to use PassCore with usernames.

**Comment by geoperez** [comment]
Status?

**Comment by arielgeffen** [comment]
Hi @geoperez 

I have tried to update my default domain with the AD domain (its a subdomain) and it didn't work. I also tried changing it to my top-level domain and that also didn't work.

I make the change, save the file and restart the web service - but it still tells me to enter a valid email address?
