### ISSUE TITLE
Security question for password reset.

### ISSUE THREAD

**Issue by openmoto** [unosquare/passcore#218]
In my environment, users tend to get locked out because they don't remember their password.
Usually, they can wait 15 minutes and try again after getting locked out, but if they don't remember their password, how do they do a password reset then?

Is it possible to add a security questions feature and get users to register their security questions beforehand, that way if they forget their password, they can reset it using the security question...
Also possibly allow admin to clear the security questions in order to allow user re-register again in case they forget it.

**Comment by geoperez** [comment]
We are not going to support password reset. Right now, we have no plans to implement it but PR are welcome.
