### ISSUE TITLE
multiple domains

### ISSUE THREAD

**Issue by lp2019** [unosquare/passcore#219]
hello guys,

is it possible to have multiple domains inside the same server?

like:

domain1= app pool1 + site1 = http://passcore.domain1.com
domain2= app pool2 + site2 = http://passcore.domain2.com
domain3= app pool3 + site3 = http://passcore.domain3.com

I'm trying to have this working by creating a passcore folder for each domain and all configs needed.

cheers

**Comment by geoperez** [comment]
Yes, you can. As long you set up a different appsettings.json file in each folder.

**Comment by lp2019** [comment]
Ok I'm going to test that :) thank you so much for your help

**Comment by geoperez** [comment]
Can I close this?

**Comment by lp2019** [comment]
Yes please.

De: Geovanni Perez <notifications@github.com>
Enviada: 19 de outubro de 2018 16:18
Para: unosquare/passcore <passcore@noreply.github.com>
Cc: Luis Palma <luis.palma@platerit.pt>; Author <author@noreply.github.com>
Assunto: Re: [unosquare/passcore] multiple domains (#219)


Can I close this?
