### ISSUE TITLE
Want to translate

### ISSUE THREAD

**Issue by collegemathieu** [unosquare/passcore#22]
Good morning!
Awsome product and works pretty good so far! Thank you, you just saved me a awfull lot of work.
But, we are a french college, I want to translate the display text.  Could you give me a pointer of where to look? Also after it is translated, are you interested in having it?
Thank you.

**Comment by mariodivece** [comment]
All translation strings are located in the config file... Please refer to the readme. And yes! I'd love to host a French translation file :)
