### ISSUE TITLE
Wildcard Certificate

### ISSUE THREAD

**Issue by rrafluap** [unosquare/passcore#227]
Before I buy one, can PassCore be served with a wildcard SSL certificate? I seem to remember seeing that it couldn't so ended up buying one specific to the subdomain its on... (originally).

I now need another SSL certificate for another application and it works out cheaper for me to have one wildcard.

Thanks

**Comment by geoperez** [comment]
PassCore should be hosted in IIS, and this web server support wildcard
certificate.

PassCore, per se, have no limitations with SSL certificates.

**Comment by unquietwiki** [comment]
@rrafluap @geoperez https://letsencrypt.org/docs/client-options/ some of the ACMEv2 options may be good here.

**Comment by geoperez** [comment]
Status?
