### ISSUE TITLE
error on PS installer

### ISSUE THREAD

**Issue by piacas** [unosquare/passcore#228]
get this error using PS installer:
Invoke-WebRequest : Unable to connect to the remote server
At line:71 char:16
+ ...   $request = Invoke-WebRequest -Uri "http://localhost:$($iisAppPort)"
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

Everything else works ok and modify .json file. But after site restarts, can't connect. web browser on local IIS server using http://localhost:8080 get ERR_CONNECTION_REFUSED.

IIS site is up and running.....any ideas.

**Comment by geoperez** [comment]
The error with `Invoke-WebRequest` is because PassCore is not running. Try to enable the logging and check the log files, please.

**Comment by piacas** [comment]
stdout info:
warn: Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository[50]
      Using an in-memory repository. Keys will not be persisted to storage.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[59]
      Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[58]
      Creating key {09316a53-47d4-4c4d-b395-99cb88395ec1} with creation date 2018-11-07 17:26:34Z, activation date 2018-11-07 17:26:34Z, and expiration date 2019-02-05 17:26:34Z.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {09316a53-47d4-4c4d-b395-99cb88395ec1} may be persisted to storage in unencrypted form.
Hosting environment: Production
Content root path: C:\passcore
Now listening on: http://127.0.0.1:7299
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:8080/  
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://localhost:8080/  
info: Microsoft.AspNetCore.Rewrite.RewriteMiddleware[8]
      Request redirected to HTTPS
info: Microsoft.AspNetCore.Rewrite.RewriteMiddleware[8]
      Request redirected to HTTPS
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 80.7786ms 302 
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 80.7786ms 302 


IIS log:
2018-11-07 17:26:35 W3SVC2 test-dc-01 ::1 GET / - 8080 - ::1 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/70.0.3538.77+Safari/537.36 - 302 0 0 1249

**Comment by geoperez** [comment]
Do your IIS have an HTTPS bind?

**Comment by piacas** [comment]
It does not. Was never setup for one. Not even a cert on server. Whats causing the redirect to https? Can I disable it to test?

**Comment by geoperez** [comment]
For security reasons, we remove the option to ignore HTTPS. But you can try to use a self-signed certificate:

https://dontpaniclabs.com/blog/post/2017/01/11/creating-self-signed-ssl-certificate-developing-testing-iis/

**Comment by geoperez** [comment]
Status?

**Comment by geoperez** [comment]
Related #237 and #234
