### ISSUE TITLE
Wrong Exception-Message

### ISSUE THREAD

**Issue by diogenes25** [unosquare/passcore#229]
**PassCore Server**
- OS: [Windows | Linux | macOS]
- Provider: [Active Directory | LDAP]

**Describe the bug**
Wrong errormessage if Ldap-SearchFilter is not set.
https://github.com/unosquare/passcore/blob/03bde30d71525fbe2cbcc77b41ea2129621b2a21/src/Zyborg.PassCore.PasswordProvider.LDAP/LdapPasswordChangeProvider.cs#L275

**Expected behavior**
Just a wrong message

**Additional context**
same here
https://github.com/unosquare/passcore/blob/03bde30d71525fbe2cbcc77b41ea2129621b2a21/src/Zyborg.PassCore.PasswordProvider.LDAP/LdapPasswordChangeProvider.cs#L282

**Comment by geoperez** [comment]
Good catch! I'm going to fixed.

**Comment by geoperez** [comment]
Resolved.
