### ISSUE TITLE
Failed to update password

### ISSUE THREAD

**Issue by ps45** [unosquare/passcore#230]
**PassCore Server**
- OS: [Windows]
- Provider: [Active Directory]

**Describe the bug**
Installed version 3.5. 
I get failed to update password: does not meet the password policy requirements on testaccounts.

**To Reproduce**
When i go back to the old version (3.0), the passw change for the testaccounts do work.
I checked, it is not the password policy.

Can it be some setting in appsettings.json?

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/44430687/48415533-e7aa5d00-e74d-11e8-9402-4df1a7f27230.png)

**Comment by geoperez** [comment]
Can you post your settings without server names and password, please?

**Comment by ps45** [comment]
Hi Geovanni,
Thanks for the help..

this is my appsettings file

{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
  "PasswordChangeOptions": {
    "UseAutomaticContext": false, // Set true to allow PassCore to reset password using the same credentials, or false if you will fill the credentials below
    "RestrictedADGroups": [
      "Administrators",
      "Domain Admins",
      "Enterprise Admins"
    ], // Set the AD groups to restrict the use of PassCore 
    "AllowedADGroups": [], // Set the AD Groups to allow PassCore, if the array is empty all the groups no-restricted above are allowed
    "IdTypeForUser": "DN", // Possible values are "DN", "GUID", "Name", "SAM", "SID" and "UPN"
    "UpdateLastPassword":  true // Set true to allow PassCore to  update the last password timestamp
  },
  "LdapPasswordChangeOptions": {
    "LdapSearchBase": "DC=xxxx,DC=com",
    "LdapStartTls": false,
    "LdapChangePasswordWithDelAdd": true,
    "LdapSearchFilter": "(sAMAccountName={Username})" // Another value: "(&(objectClass=person)(cn={Username}))"
  },
  "AppSettings": {
    "LdapHostnames": [ "xxxx.com" ], // Set your hostname(s)
    "LdapPort": 389, // Default for AD is 389, for LDAPS 636
    "LdapUsername": "xxxx", // Set the username or distinguish name (DN) to bind the LDAP server
    "LdapPassword": "xxxx", // Set the password for the username
    "RecaptchaPrivateKey": "", // ReCAPTCHA private key: replace this! or leave empty if you don't need ReCAPTCHA
    "DefaultDomain": "xxxx.com" // Set your default AD domain here, or non "@" logins will not work! Use empty value to allow user to set the domain.
  },
  "ClientSettings": {
    "ValidationRegex": {
      "EmailRegex": "^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$",
      "UsernameRegex": "^[a-zA-Z0-9._-]{3,20}$"
    },
    "ShowPasswordMeter": true,
    "Recaptcha": {
      "SiteKey": "", // ReCAPTCHA public key: replace this! or leave empty if you don't need ReCAPTCHA
      "LanguageCode": "en"
    },
    "UseEmail": "true",
    "ApplicationTitle": "Self-Service Account Management Tools",
    "ChangePasswordTitle": "Change Account Password",
    "ChangePasswordForm": {
      "HelpTitle": "Help and Support",
      "HelpText": "If you are having trouble with this tool, please contact IT Support",
      "UsernameLabel": "Username",
      "UsernameHelpblock": "Your organization's email address",
      "UsernameDefaultDomainHelperBlock": "Your organization's username",
      "CurrentPasswordLabel": "Current Password",
      "CurrentPasswordHelpblock": "Enter your current password",
      "NewPasswordLabel": "New Password",
      "NewPasswordHelpblock": "Enter a <a href='https://support.microsoft.com/en-us/help/4026406/microsoft-account-create-a-strong-password' target='_blank'>strong password</a>. You can use <a href='https://xkpasswd.net/s/' target='_blank'>this tool</a> to help you create one.",
      "NewPasswordVerifyLabel": "Re-enter New Password",
      "NewPasswordVerifyHelpblock": "Enter your new password again",
      "ChangePasswordButtonLabel": "Change Password"
    },
    "ErrorsPasswordForm": {
      "FieldRequired": "This field is required",
      "UsernamePattern": "Please enter a valid username",
      "UsernameEmailPattern": "Please enter a valid email address",
      "PasswordMatch": "Passwords do not match"
    },
    "Alerts": {
      "SuccessAlertTitle": "You have changed your password successfully.",
      "SuccessAlertBody": "Please note it may take 2 hours for your new password to reach all domain controllers and to O365.",
      "ErrorPasswordChangeNotAllowed": "You are not allowed to change your password. Please contact your system administrator.",
      "ErrorInvalidCredentials": "You need to provide the correct current password.",
      "ErrorInvalidDomain": "You have supplied an invalid domain to logon to.",
      "ErrorInvalidUser": "We could not find your user account.",
      "ErrorCaptcha": "Could not verify you are not a robot",
      "ErrorFieldRequired": "Fulfill all the fields",
      "ErrorFieldMismatch": "The passwords do not match"
    }
  }
}

**Comment by geoperez** [comment]
Try to set UpdateLastPassword off.

**Comment by geoperez** [comment]
Status?

**Comment by ps45** [comment]
Hi Geovanni,
Same error. Does not meet the password policy requirements..

**Comment by geoperez** [comment]
Check #233

> If I logon to a local domain computer, and I try using PowerShell Set-ADAccountPassword, I get the same error. Group Policy is set to enforce only a 7 character length, complexity rules are otherwise disabled, and I verified this with Get-ADDefaultDomainPasswordPolicy.

> After a bit of troubleshooting, I found that the password history was set to 24, and it was simply that users were trying to reuse an old password, so the error was in fact correct.
