### ISSUE TITLE
Failed to update password: Policy Requirements

### ISSUE THREAD

**Issue by thekeagy** [unosquare/passcore#233]
Failed to update password: The password does not meet the password policy requirements. Check the minimum password length, password complexity and password history requirements. (Exception from HRESULT: 0x800708C5)

**PassCore Server**
- OS: Windows Server 2016
- Provider: Active Directory (Domain Joined)
- Settings file (without sensitive information):
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
  "PasswordChangeOptions": {
    "UseAutomaticContext": true, // Set true to allow PassCore to reset password using the same credentials, or false if you will fill the credentials below
    "RestrictedADGroups": [
      "Administrators",
      "Domain Admins",
      "Enterprise Admins",
      **"XXX**"
    ], // Set the AD groups to restrict the use of PassCore 
    "AllowedADGroups": [], // Set the AD Groups to allow PassCore, if the array is empty all the groups no-restricted above are allowed
    "IdTypeForUser": "DN", // Possible values are "DN", "GUID", "Name", "SAM", "SID" and "UPN"
    "UpdateLastPassword":  true // Set true to allow PassCore to  update the last password timestamp
  },
  "LdapPasswordChangeOptions": {
    "LdapSearchBase": "OU=**XXX**,OU=**XXX**,DC=**XXX**,DC=**XXX**",
    "LdapStartTls": false,
    "LdapChangePasswordWithDelAdd": true,
    "LdapSearchFilter": "(sAMAccountName={Username})" // Another value: "(&(objectClass=person)(cn={Username}))"
  },
  "AppSettings": {
    "LdapHostnames": [ "**XXX.XXX.XXX.XXX**" ], // Set your hostname(s)
    "LdapPort": 389, // Default for AD is 389, for LDAPS 636
    "LdapUsername": "**XXX**", // Set the username or distinguish name (DN) to bind the LDAP server
    "LdapPassword": "**XXX**", // Set the password for the username
    "RecaptchaPrivateKey": "", // ReCAPTCHA private key: replace this! or leave empty if you don't need ReCAPTCHA
    "DefaultDomain": "**XXX.XXX**" // Set your default AD domain here, or non "@" logins will not work! Use empty value to allow user to set the domain.
  },
  "ClientSettings": {
    "ValidationRegex": {
      "EmailRegex": "^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$",
      "UsernameRegex": "^[a-zA-Z0-9._-]{3,20}$"
    },
    "ShowPasswordMeter": true,
    "Recaptcha": {
      "SiteKey": "", // ReCAPTCHA public key: replace this! or leave empty if you don't need ReCAPTCHA
      "LanguageCode": "en"
    },
    "UseEmail": "true",
    "ApplicationTitle": "Self-Service Account Management Tools",
    "ChangePasswordTitle": "Change Account Password",
    "ChangePasswordForm": {
      "HelpTitle": "Help and Support",
      "HelpText": "If you are having trouble with this tool, please contact IT Support",
      "UsernameLabel": "Username",
      "UsernameHelpblock": "Your organization's email address",
      "UsernameDefaultDomainHelperBlock": "Your organization's username",
      "CurrentPasswordLabel": "Current Password",
      "CurrentPasswordHelpblock": "Enter your current password",
      "NewPasswordLabel": "New Password",
      "NewPasswordHelpblock": "Minimum 8 Characters, One Uppercase, One digit (0 through 9), and One Non-alphabetic characters (For example, !, $, #, %)",
      "NewPasswordVerifyLabel": "Re-enter New Password",
      "NewPasswordVerifyHelpblock": "Enter your new password again",
      "ChangePasswordButtonLabel": "Change Password"
    },
    "ErrorsPasswordForm": {
      "FieldRequired": "This field is required",
      "UsernamePattern": "Please enter a valid username",
      "UsernameEmailPattern": "Please enter a valid email address",
      "PasswordMatch": "Passwords do not match"
    },
    "Alerts": {
      "SuccessAlertTitle": "You have changed your password successfully.",
      "SuccessAlertBody": "Please note it may take a few hours for your new password to reach all domain controllers.",
      "ErrorPasswordChangeNotAllowed": "You are not allowed to change your password. Please contact your system administrator.",
      "ErrorInvalidCredentials": "You need to provide the correct current password.",
      "ErrorInvalidDomain": "You have supplied an invalid domain to logon to.",
      "ErrorInvalidUser": "We could not find your user account.",
      "ErrorCaptcha": "Could not verify you are not a robot",
      "ErrorFieldRequired": "Fulfill all the fields",
      "ErrorFieldMismatch": "The passwords do not match"
    }
  }
}

**Describe the bug**
Failed to update password: The password does not meet the password policy requirements. Check the minimum password length, password complexity and password history requirements. (Exception from HRESULT: 0x800708C5)

**To Reproduce**
When resetting a users password

**Screenshots**
![1](https://user-images.githubusercontent.com/29722134/49212258-720dd600-f376-11e8-9117-0de3ea1a8154.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Chrome 
 - Version 70.0.3538.110 (Official Build) (64-bit)

**Comment by ps45** [comment]
I have the same problem..

**Comment by geoperez** [comment]
Just to verify, if you try to change the same password on Windows, you don't get the requirements issue?

Because that Error Code (0x800708C5) is always throw by Active Directory. PassCore is unabled to bypass this [password validation](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/password-must-meet-complexity-requirements).
