### ISSUE TITLE
Turn off forced HTTPS redirect

### ISSUE THREAD

**Issue by crsleeth** [unosquare/passcore#234]
**PassCore Server**
- OS: Windows Server 2016
- Provider: Active Directory

**Describe the bug**
PassCore installed with HTTP doesn't work. HTTPS redirection is forced. 

**Expected behavior**
It would be preferable if HTTP was an option so that HTTPS and certificates could be handled by a reverse proxy.

**Comment by crsleeth** [comment]
This was easy to turn off in PassCore release 3.1 by changing EnableHttpsRedirect to false in appsettings.json so I have reverted to that version, but being on an older release isn't ideal.

**Comment by geoperez** [comment]
OK, good point!

**Comment by geoperez** [comment]
You can find the change in the master branch. Let me know if you need a build.

**Comment by crsleeth** [comment]
That would be great, but no rush. Thank you!!

**Comment by geoperez** [comment]
Please try this:

https://github.com/unosquare/passcore/releases/download/3.6.1/PassCore361.zip

**Comment by crsleeth** [comment]
Thanks! It works. I have one issue though and I'm pretty sure it is unrelated to 3.6.1. I'm getting "Please enter a valid email address" when users type in just their user name. I have the default domain set but it still wants an "@".
