### ISSUE TITLE
Remove current password field

### ISSUE THREAD

**Issue by jok0** [unosquare/passcore#239]
Hi there, i have this working and the tool is great! Although i work in a school and i would love to try get this working where teachers can change students passwords if they have forgotten them.  Would there be any way of removing the current password field?

Many thanks,

**Comment by geoperez** [comment]
You are asking for a reset password form, and this is not what we try to deliver on PassCore. The issue with reset password form, that you need to verify the user somehow (some folks suggest using an SMS code using Twilio) but this feature is out of scope for now.
