### ISSUE TITLE
Cannot read property of 'helpText'

### ISSUE THREAD

**Issue by illi5** [unosquare/passcore#240]
**PassCore Server**
- OS:  Linux 
- Provider: Active Directory]
- Settings file (without sensitive information): 
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
  "PasswordChangeOptions": {
    "UseAutomaticContext": true, // Set true to allow PassCore to reset password using the same credentials, or false if you will fill the credentials below
    "RestrictedADGroups": [
      "Administrators",
      "Domain Admins",
      "Enterprise Admins"
    ], // Set the AD groups to restrict the use of PassCore 
    "AllowedADGroups": [], // Set the AD Groups to allow PassCore, if the array is empty all the groups no-restricted above are allowed
    "IdTypeForUser": "DN", // Possible values are "DN", "GUID", "Name", "SAM", "SID" and "UPN"
    "UpdateLastPassword":  false // Set true to allow PassCore to  update the last password timestamp
  },
  "LdapPasswordChangeOptions": {
    "LdapSearchBase": "ou=people,dc=example,dc=com",
    "LdapStartTls": false,
    "LdapChangePasswordWithDelAdd": true,
    "LdapSearchFilter": "(sAMAccountName={Username})" // Another value: "(&(objectClass=person)(cn={Username}))"
  },
  "AppSettings": {
    "LdapHostnames": [ "" ], // Set your hostname(s)
    "LdapPort": 389, // Default for AD is 389, for LDAPS 636
    "LdapUsername": "", // Set the username or distinguish name (DN) to bind the LDAP server
    "LdapPassword": "", // Set the password for the username
    "RecaptchaPrivateKey": "", // ReCAPTCHA private key: replace this! or leave empty if you don't need ReCAPTCHA
    "DefaultDomain": "" // Set your default AD domain here, or non "@" logins will not work! Use empty value to allow user to set the domain.
  },
  "ClientSettings": {
    "ValidationRegex": {
      "EmailRegex": "^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\\.[a-zA-Z0-9-]+)*$",
      "UsernameRegex": "^[a-zA-Z0-9._-]{3,20}$"
    },
    "ShowPasswordMeter": true,
    "Recaptcha": {
      "SiteKey": "", // ReCAPTCHA public key: replace this! or leave empty if you don't need ReCAPTCHA
      "LanguageCode": "en"
    },
    "UseEmail": "true",
    "ApplicationTitle": "Self-Service Account Management Tools",
    "ChangePasswordTitle": "Change Account Password",
    "ChangePasswordForm": {
      "HelpTitle": "Help and Support",
      "HelpText": "If you are having trouble with this tool, please contact IT Support",
      "UsernameLabel": "Username",
      "UsernameHelpblock": "Your organization's email address",
      "UsernameDefaultDomainHelperBlock": "Your organization's username",
      "CurrentPasswordLabel": "Current Password",
      "CurrentPasswordHelpblock": "Enter your current password",
      "NewPasswordLabel": "New Password",
      "NewPasswordHelpblock": "Enter a <a href='https://support.microsoft.com/en-us/help/4026406/microsoft-account-create-a-strong-password' target='_blank'>strong password</a>. You can use <a href='https://xkpasswd.net/s/' target='_blank'>this tool</a> to help you create one; use the XKCD (random sep, pad digit), or NTLM, options.",
      "NewPasswordVerifyLabel": "Re-enter New Password",
      "NewPasswordVerifyHelpblock": "Enter your new password again",
      "ChangePasswordButtonLabel": "Change Password"
    },
    "ErrorsPasswordForm": {
      "FieldRequired": "This field is required",
      "UsernamePattern": "Please enter a valid username",
      "UsernameEmailPattern": "Please enter a valid email address",
      "PasswordMatch": "Passwords do not match"
    },
    "Alerts": {
      "SuccessAlertTitle": "You have changed your password successfully.",
      "SuccessAlertBody": "Please note it may take a few hours for your new password to reach all domain controllers.",
      "ErrorPasswordChangeNotAllowed": "You are not allowed to change your password. Please contact your system administrator.",
      "ErrorInvalidCredentials": "You need to provide the correct current password.",
      "ErrorInvalidDomain": "You have supplied an invalid domain to logon to.",
      "ErrorInvalidUser": "We could not find your user account.",
      "ErrorCaptcha": "Could not verify you are not a robot",
      "ErrorFieldRequired": "Fulfill all the fields",
      "ErrorFieldMismatch": "The passwords do not match"
    }
  }
}

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/45788360/49795892-d8660180-fd43-11e8-9aff-722bf0b79dcd.png)

![image](https://user-images.githubusercontent.com/45788360/49795919-ee73c200-fd43-11e8-8c6d-a05129e68c68.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser  chrome
 - Version [e.g. 69]

**Additional context**

**Comment by geoperez** [comment]
Can you check the Network tab in Chrome Debugger? I think you may have a bad installation and the API is not respoding.

**Comment by illi5** [comment]
Hi,

**Comment by illi5** [comment]
![image](https://user-images.githubusercontent.com/45788360/49852674-7661d680-fded-11e8-8c36-1dcf9237cada.png)

**Comment by illi5** [comment]
Is the problem with api/password file

**Comment by illi5** [comment]
{
	"username": "",
	"currentPassword": "",
	"newPassword": "",
	"newPasswordVerify": ""
}

**Comment by geoperez** [comment]
There is not an 'api/password' file, the api route is connected to a WebAPI. Probably your IIS is mounting an incorrect folder.

**Comment by geoperez** [comment]
Status?
