### ISSUE TITLE
input field user name cleared after passwort change

### ISSUE THREAD

**Issue by bardware** [unosquare/passcore#241]
My domain admin installed `Powered by PassCore v3.4.2` to allow me to change my password every once in a while. I enter my current password and my new password twice. I get the confirmation my password was changed. 
The URL in the browser looks like `http://server.domain/?userName=myuser` the input field user name, however, is empty.
After changing the password I close the browser window. I just noticed that the browser URL stayed the same, the behaviour that the user name fieled is prefilled from URL does not occur.

**Comment by geoperez** [comment]
Can you test with the latest version  (3.6.0)?

**Comment by k3z0** [comment]
Hi @bardware,

As @geoperez mentions, this is fully working in the last PassCore version. So please try to update to the last version.
