### ISSUE TITLE
Change Footer Logo and Text

### ISSUE THREAD

**Issue by wakhan007** [unosquare/passcore#242]
Hi,

I want to change the footer logos and text in passcore footer, but I am not able to find the exact file.

Please guide.

**Comment by szotyii** [comment]
Hi,

It would be a nice feature that we can customize the footer area.

Thanks!

**Comment by szotyii** [comment]
Thanks for your reply!
We made some change in the main.bundle.js file and we could customize the footer area.

**Comment by geoperez** [comment]
Can I close this issue?

**Comment by wakhan007** [comment]
Please dont close the case now, i am doing some testing and i will update you ..

**Comment by geoperez** [comment]
Reopening

**Comment by wakhan007** [comment]
I have rebuild the Web App but getting below error, when testing it:

Error:
HTTP Error 500.21 - Internal Server Error  Handler "aspNetCore" has a bad module "AspNetCoreModuleV2" in its module list

Steps Followed:
1. Download .NET Core SDK and nodejs.
2. Download and extract passcore-master.zip and go to path \passcore-master\src\Unosquare.PassCore.Web

3. Update Footer.html on path \passcore-master\src\Unosquare.PassCore.Web\ClientApp\app\footer\footer.html

4. Rebuild:
C:\Test\passcore-master\src\Unosquare.PassCore.Web>dotnet publish --configuration Release --runtime win-x64 --output "d:\passcore"


5. Setup the newly compiled folder(Passcore) to IIS. 
But getting error :
HTTP Error 500.21 - Internal Server Error  Handler "aspNetCore" has a bad module "AspNetCoreModuleV2" in its module list

Right now dotnet-hosting-2.1.0-win was installed, so I also installed dotnet-hosting-2.2.0-win. But after installing (dotnet-hosting-2.2.0-win) now getting HTTP Error 503. The service is unavailable.
, also Application Pool Passcore stopped abnormally.

But if I manually run Unosquare.PassCore.Web application then it run with http://localhost:5000/

**Comment by geoperez** [comment]
That's odd. did you set up the Application pool as No Managed Code?

**Comment by wakhan007** [comment]
I tried on the new system and it has started working :-) 

You can close the case now. Thanks for the help.
