### ISSUE TITLE
Title not working

### ISSUE THREAD

**Issue by mskrishna20051974** [unosquare/passcore#245]
**PassCore Server**
- OS: [Windows | 2016
- Provider: [Active Directory]
- Settings file (without sensitive information): 

 I installed 3.6 version today. I am able to change the password successfully.  In the previous version we could get the Title on the Page by adding this field.

"ChangePasswordTitle": "Change Account Password",

Now this field does not work.  Is there a workaround for this?

**Comment by geoperez** [comment]
Yeah, we restore the missing setting in the next version. You can download v3.6.1 at https://github.com/unosquare/passcore/releases/tag/3.6.1
