### ISSUE TITLE
Identify if account is lock

### ISSUE THREAD

**Issue by dragonwarrior00** [unosquare/passcore#252]
**Is your feature request related to a problem? Please describe.**
When an user attempts to change their password with all correct credentials but is currently lock, it will prompt the same error message as if the user entered an incorrect current password.

**Describe the solution you'd like**
A notification stating that the account is currently locked. If possible, before it checks the current password and new passwords are correct.

**Describe alternatives you've considered**
Currently I have modified the incorrect password prompt error to include the statement that the account might be locked as well so the users know.

**Additional context**

**Comment by geoperez** [comment]
Can you share your changes?

**Comment by coofercat** [comment]
Another possible change is to the toaster message that says "you need to provide correct current password" could be changed to ""you need to provide correct current password, or password was changed within minimum password change time" (or something).

My point being that if your AD has a (default?) minimum password age of 1 day, then you can only change your password once in a 24 hour period. It seems that the server returns this in such cases:
```
LdapException: Server Message: 0000052D: AtrErr: DSID-03191083, #1:
      	0: 0000052D: DSID-03191083, problem 1005 (CONSTRAINT_ATT_TYPE), data 0, Att 9005a (unicodePwd)
```
...which the app turns into "you need to provide correct current password". It's a bit confusing as a user to know that this actually means "come back tomorrow".
