### ISSUE TITLE
Error when changing password

### ISSUE THREAD

**Issue by BENT17** [unosquare/passcore#253]
I have everything configured with LDAP. When I come to change password I keep getting the following:

Failed to update password: Value cannot be null.
      Parameter name: source

Can someone help me out

**Comment by BENT17** [comment]
Logs arent helping much also. Can someone help me out? I feel I am very close to completing this but stuck on the last part

**Comment by geoperez** [comment]
Try to post your appsettings.json without sensitive data, please.

**Comment by geoperez** [comment]
What version of ASP.NET Core are you using?

**Comment by BENT17** [comment]
v4.0.30319

**Comment by geoperez** [comment]
Please run `dotnet --info` and paste the output.

**Comment by BENT17** [comment]
Version: 2.1.1
  Commit:  6985b9f684

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by BENT17** [comment]
Updated to 2.2.0 and same issue

**Comment by BENT17** [comment]
Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

**Comment by BENT17** [comment]
It doesnt even look like its even doing an LDAP query as if i enter a random user and random passwords I get the above error

**Comment by geoperez** [comment]
What PassCore version are you using? The latest?

**Comment by BENT17** [comment]
yes the latest version

**Comment by BENT17** [comment]
Any idea what I can do?

**Comment by sasfog** [comment]
I'm experiencing the same issue. 

My configuration is the following:
Downloaded the Linux zip file. Installed on CentOs 7.3.
.NET runtime version is 2.1.7 (2.1.503 SDK installed)

Currently I have HTTPS redirection disabled, so I'm accessing through HTTP protocol http://PassCoreServer:5000
The LDAP connection is set up with FQDN, secure LDAPS (636 secure port), port is open.
Provided user is domain admin, without domain prefix/suffix, default domain is setup. StartTLS is disabled.

The problem only occurs when 636 port is used, but it needs to be used if I want to manage AD through openLDAP.

https://nawilson.com/2010/08/26/ldap-password-changes-in-active-directory/

**Comment by JeromeD49** [comment]
I'm experiencing the same issue #260 

Have you been able to work on this issue ?

Thanks

**Comment by geoperez** [comment]
Related to #260
