### ISSUE TITLE
Failed to update password: While trying to retrieve the authorization groups, an error (1332) occurred.

### ISSUE THREAD

**Issue by Miudon** [unosquare/passcore#254]
**PassCore Server**
- OS: [Windows Server 2008 r2]
- Provider: [Active Directory]
- Settings file (without sensitive information): 
  "AppSettings": {
    // The following options for AD Provider (remove if you don't use this Provider)
    "UseAutomaticContext": false, // Set true to allow PassCore to reset password using the same credentials, or false if you will fill the credentials below
    "RestrictedADGroups": [
      "Administrators",
      "Domain Admins",
      "Enterprise Admins"
    ], // Set the AD groups to restrict the use of PassCore
    "AllowedADGroups": [], // Set the AD Groups to allow PassCore, if the array is empty all the groups no-restricted above are allowed
    "IdTypeForUser": "UPN", // Possible values are "DN", "GUID", "Name", "SAM", "SID" and "UPN" (Default UPN)
    "UpdateLastPassword": false, // Set true to allow PassCore to  update the last password timestamp
    // The following options are for LDAP Provider (remove if you don't use this Provider)
    "LdapSearchBase": "ou=XXX,dc=XXX,dc=XXX,dc=br",
    "LdapStartTls": false,
    "LdapChangePasswordWithDelAdd": true,
    "LdapSearchFilter": "(sAMAccountName={Username})", // Another value: "(&(objectClass=person)(cn={Username}))"
    // General options (valid for both providers)
    "LdapHostnames": [ "XXX.XXX.XXX" ], // Set your hostname(s)
    "LdapPort": 389, // Default for AD is 389, for LDAPS 636
    "LdapUsername": "XXX", // Set the username or distinguish name (DN) to bind the LDAP server
    "LdapPassword": "XXX", // Set the password for the username
    "DefaultDomain": "XXX.XXX.XXX" // Set your default AD domain here, or non "@" logins will not work! Use empty value to allow user to set the domain. This option is ONLY available with UPN.
  },

**Describe the bug**
Passcore was installed on IIS Server joinned to another domain. I've set UseAutomaticContext to false. I think settings of server, domain and user are OK, because if I fill a user that doesn't exist into a domain, the error: "We could not find your user account." appears on screen.
I need this scenario for use Certificate installed on IIS
Thanks in advance.

**STDOUT_XXX.log**
warn: Microsoft.AspNetCore.DataProtection.Repositories.EphemeralXmlRepository[50]
      Using an in-memory repository. Keys will not be persisted to storage.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[59]
      Neither user profile nor HKLM registry available. Using an ephemeral key repository. Protected data will be unavailable when application exits.
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[58]
      Creating key {22e66478-13a0-42b3-a16c-9e86e037a024} with creation date 2019-01-30 09:44:50Z, activation date 2019-01-30 09:44:50Z, and expiration date 2019-04-30 09:44:50Z.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {22e66478-13a0-42b3-a16c-9e86e037a024} may be persisted to storage in unencrypted form.
Hosting environment: Production
Content root path: C:\XXX\XXX\passcore
Now listening on: http://127.0.0.1:3464
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://XXX.XXX.XXX/PassCore/  
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://XXX.XXX.XXX/PassCore/  
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://XXX.XXX.XXX/PassCore/  
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://XXX.XXX.XXX/PassCore/  
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /index.html was not modified
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /index.html was not modified
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 132.231ms 304 text/html
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 132.2188ms 304 text/html
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://XXX.XXX.XXX/PassCore/  
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://XXX.XXX.XXX/PassCore/  
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /index.html was not modified
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /index.html was not modified
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.6223ms 304 text/html
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.6265ms 304 text/html
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://XXX.XXX.XXX/PassCore/polyfills.bundle.js  
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://XXX.XXX.XXX/PassCore/main.bundle.js  
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://XXX.XXX.XXX/PassCore/assets/styles/indigo-pink.css  
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://XXX.XXX.XXX/PassCore/vendor.bundle.js  
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /polyfills.bundle.js was not modified
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /assets/styles/indigo-pink.css was not modified
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /main.bundle.js was not modified
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.3364ms 304 text/css
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.3391ms 304 application/javascript
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.3419ms 304 application/javascript
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /vendor.bundle.js was not modified
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.3325ms 304 application/javascript
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://XXX.XXX.XXX/PassCore/api/password  
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Route matched with {action = "Get", controller = "Password"}. Executing action Unosquare.PassCore.Web.Controllers.PasswordController.Get (Unosquare.PassCore.Web)
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Unosquare.PassCore.Web.Controllers.PasswordController.Get (Unosquare.PassCore.Web) - Validation state: Valid
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action method Unosquare.PassCore.Web.Controllers.PasswordController.Get (Unosquare.PassCore.Web), returned result Microsoft.AspNetCore.Mvc.JsonResult in 0.7093ms.
info: Microsoft.AspNetCore.Mvc.Formatters.Json.Internal.JsonResultExecutor[1]
      Executing JsonResult, writing value of type 'Unosquare.PassCore.Web.Models.ClientSettings'.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action Unosquare.PassCore.Web.Controllers.PasswordController.Get (Unosquare.PassCore.Web) in 227.7107ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 500.9083ms 200 application/json; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://XXX.XXX.XXX/PassCore/assets/images/help.png  
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /assets/images/help.png was not modified
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.341ms 304 image/png
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://XXX.XXX.XXX/PassCore/assets/images/passcore-logo.png  
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /assets/images/passcore-logo.png was not modified
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.271ms 304 image/png
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://XXX.XXX.XXX/PassCore/assets/images/logo.png  
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /assets/images/logo.png was not modified
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.129ms 304 image/png
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://XXX.XXX.XXX/PassCore/assets/images/License_icon-mit.svg.png  
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /assets/images/License_icon-mit.svg.png was not modified
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.1323ms 304 image/png
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://XXX.XXX.XXX/PassCore/assets/images/osi.png  
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /assets/images/osi.png was not modified
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.0921ms 304 image/png
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://XXX.XXX.XXX/PassCore/api/password application/json 117
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Route matched with {action = "Post", controller = "Password"}. Executing action Unosquare.PassCore.Web.Controllers.PasswordController.Post (Unosquare.PassCore.Web)
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Unosquare.PassCore.Web.Controllers.PasswordController.Post (Unosquare.PassCore.Web) with arguments (Unosquare.PassCore.Web.Models.ChangePasswordModel) - Validation state: Valid
info: Unosquare.PassCore.PasswordProvider.PasswordChangeProvider[0]
      PerformPasswordChange for user user@XXX.XXX.XXX
warn: Unosquare.PassCore.PasswordProvider.PasswordChangeProvider[0]
      Not using AutomaticContext  XXX.XXX.XXX:389
warn: Unosquare.PassCore.PasswordProvider.PasswordChangeProvider[0]
      Failed to update password: While trying to retrieve the authorization groups, an error (1332) occurred.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action method Unosquare.PassCore.Web.Controllers.PasswordController.Post (Unosquare.PassCore.Web), returned result Microsoft.AspNetCore.Mvc.BadRequestObjectResult in 508.7835ms.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
      Executing ObjectResult, writing value of type 'Unosquare.PassCore.Web.Models.ApiResult'.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action Unosquare.PassCore.Web.Controllers.PasswordController.Post (Unosquare.PassCore.Web) in 694.5128ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 721.678ms 400 application/json; charset=utf-8

**Comment by geoperez** [comment]
Check new version 3.6.2, please.

**Comment by Miudon** [comment]
Hi!
I tested the version 3.6.2 but the same error persist

Thanks in advance

**Comment by xquetzalcoatl** [comment]
Add validation to catch LDAP error

**Comment by Miudon** [comment]
Sorry but I did not understand

**Comment by geoperez** [comment]
I'm going to release a new version soon.

**Comment by Miudon** [comment]
ok. Thanks a lot :-)
