### ISSUE TITLE
Passcore functional problems

### ISSUE THREAD

**Issue by qiwenha** [unosquare/passcore#264]
Dear：
i have a question，the overview said  ‘’It allows users to change their Active Directory password on their own, provided the user is not disabled‘’ .
If users password expire，this passcore can do unlock user password and reset password？

Cheers
WenHao

**Comment by geoperez** [comment]
You can try setting the option `UpdateLastPassword` to `true`. This setting will try to update the LastPasswordSet value for expired passwords.

**Comment by qiwenha** [comment]
Hi，Geovanni

Thanks you for your valuable advice.
Can i modify the Passcore homepage HTML ICon? and i don't kown.how can add use Google reCaptcha.

**Comment by qiwenha** [comment]
![image](https://user-images.githubusercontent.com/45479991/54338520-163d3380-466d-11e9-8771-f51d001c0240.png)

**Comment by qiwenha** [comment]
I See ，This page talking about for To enable reCAPTCHA.I'm trying to use it.

Thanks
