### ISSUE TITLE
Using Windows Server 2019 - Need .Net 2.2.1

### ISSUE THREAD

**Issue by arielgeffen** [unosquare/passcore#265]
**PassCore Server**
- OS: [Windows Server 2019]
- Provider: [Active Directory]
- Settings file (NA)

**Describe the bug**
Used the PowerShell script and was getting 500.21 Error
Googled around and saw that I needed to update to .Net hosting 2.2.1

Updated and PassCore works fine :)

**Comment by 0x3e4** [comment]
upvoted.. i can confirm this.

**Comment by geoperez** [comment]
I updated the PS script to use the latest version (v2.2.3). Let me know if that works.

**Comment by arielgeffen** [comment]
Seems to work perfectly!
