### ISSUE TITLE
Feature question

### ISSUE THREAD

**Issue by qiwenha** [unosquare/passcore#266]
I'm deploying using binary passcore and iis 10, and it's running successfully.
But other problems bothered me for a long time，I don't know how to delete footer content in binary passcore.Can I delete it？
I see the source code is adjustable，I tried to download the source code and configure it ，But failure
“dotnet publish --configuration Release --runtime win-x64 --output C:\User\will\Desktop\passcore    

Could you please help me cancel the footer file
Thank you very much

**Comment by geoperez** [comment]
What error did you get with the dotnet publish command?

**Comment by qiwenha** [comment]
> 你用dotnet发布命令得到了什么错误？

error MSB3073:command "npm install" sign out，error code 9009

**Comment by qiwenha** [comment]
> What error did you get with the dotnet publish command?
So I want to modify the footer using binary code

Best wishes

**Comment by geoperez** [comment]
You need to install nodejs because the webapp is using Angular 7 and the
code needs to be transpiled.

**Comment by geoperez** [comment]
Did you try after installing nodejs?

**Comment by qiwenha** [comment]
> 安装nodejs后你试过吗？

yep
