### ISSUE TITLE
Running as a sub application

### ISSUE THREAD

**Issue by KAMPFBIBER81** [unosquare/passcore#269]
Hi
I would like that Passcore is reachable with the URL https://mydomain.com/pwtool

I've copied all files under "c:\inetpub" and created an application (For the Default Website) with a physical path to "C:\inetpub"

Ive modified index.html with <base href="/pwtool/">

As soon as I tip the URL https://mydomain.com/pwtool, it throws me back to https://mydomain.com/ 

Is there a way that the URL stays at https://mydomain.com/pwtool

System:
Windows Server 2019 / IIS 10
.NET Hosting 2.1.1

**Comment by geoperez** [comment]
If you need to run Passcore as a subfolder, you need to set up a *virtual directory* at your root path.

**Comment by KAMPFBIBER81** [comment]
Ok, I will try it. many thanks
