### ISSUE TITLE
Loading only

### ISSUE THREAD

**Issue by Lost144** [unosquare/passcore#27]
Hello,

I have installed the passcore tool on a IIS Webserver.
But i get only the header of the website and "Loading...".
I have done every step of the instruction. What can i do to solve this issue?

kind regards

**Comment by mariodivece** [comment]
Have you tried everything on: https://github.com/unosquare/passcore/issues/1
Other than that I can't really help you without more info.

**Comment by mariodivece** [comment]
Please try with the latest version and let us know if this is still a problem. Reopen the issue if necessary.
