### ISSUE TITLE
Can't change password of user that requires password to be changed at next login.

### ISSUE THREAD

**Issue by hessercan** [unosquare/passcore#272]
**PassCore Server**
- OS: Windows Server 2016 
- Provider: Active Directory

Can't change password of user that requires password to be changed at next login. 
This happens when an admin changes the password for a user. I use passcore so that users can fix there VPN connection when their password expires but when I do this, I get the "You are not allowed to change your password." Error. Users are able to change their password otherwise.

**Comment by JeroenKoppenSpil** [comment]
Yep, i experience exactly the same issue. I've set the flag for "User must change password at next logon" for a couple of users. Unfortunately those users are unable to change their passwords. The message "You are not allowed to change your password". Removing this flag allowed the users to change their passwords.

**Comment by geoperez** [comment]
For this scenario, there is an option named `UpdateLastPassword`. When this setting is on, PassCore will try to update the `pwdLastSet` attribute to -1. This value removes the requirement: https://docs.microsoft.com/en-us/windows/desktop/adsi/user-must-change-password-at-next-logon

Are you using this setting?

**Comment by hessercan** [comment]
I have this option set as true.  And it says user is not allowed to change password

**Comment by geoperez** [comment]
Is the user member of one group such as Administrators? If you check the settings, by default Passcore will exclude Administrators group.

**Comment by hessercan** [comment]
No, Standard users.

**Comment by hessercan** [comment]
I think I just hit a break through, and this might just be a bug. The boolean value for "UpdateLastPassword": (true/false) I think is backwards. When I set this value to false, it lets me change passwords that have the user must change password at next login checked. But when it's set to true, it gives me that error only when that option is checked. Also, version 3.6.3 forgot to change the version number in the footer. Haha.

**Comment by geoperez** [comment]
Let me review the logic.

**Comment by JeroenKoppenSpil** [comment]
Thanks you all for the work and effort!

I have, as a test, also changed the value for "UpdateLastPassword" to false. This allowed some (test) users to change their passwords. If i Querry the user in AD i can see that the password was updated, and the date and new expiry date where updated as well according to our policies. The "User needs to change password at next logon" flag was also removed (as expected).

**Comment by eastpiger** [comment]
I met the same issues here. After set UpdateLastPassword to false, all things work as expected
