### ISSUE TITLE
use zxcvbn on the server to optionally enforce secure passwords

### ISSUE THREAD

**Issue by graingert** [unosquare/passcore#273]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to enforce secure passwords without adding security limiting password restrictions like "you must include a number"

**Describe the solution you'd like**
Add a config option for the minimum zxcvbn "number of guesses" allowed. All passwords must exceed this value

**Describe alternatives you've considered**
Default the password to "password" and trust people not to use each others accounts.

**Additional context**
No

**Comment by geoperez** [comment]
Hey, so your suggestion is to include the lib (https://github.com/mickford/zxcvbn-cs) and verify again the password strength?

**Comment by graingert** [comment]
Yes, with a config option for min "number of guesses" which is enforced in the front-end and backend

**Comment by graingert** [comment]
And maybe a sensible default

**Comment by geoperez** [comment]
I like the idea! 👍

**Comment by geoperez** [comment]
Hey @graingert did you read this? https://github.com/mickford/zxcvbn-cs/issues/4

Apparently, the .NET implementation scores differently than JS 😞

**Comment by graingert** [comment]
@geoperez have you tried this fork instead? https://github.com/trichards57/zxcvbn-cs

**Comment by geoperez** [comment]
I didn't see that fork! It is much better. I will keep it on my ToDo List

**Comment by geoperez** [comment]
@MarcoLPR please check this requirement, and let me know if you need help to implement it.

**Comment by graingert** [comment]
might also be possible to use https://www.nuget.org/packages/WasmerSharp/ and https://github.com/shssoichiro/zxcvbn-rs/issues/27

**Comment by geoperez** [comment]
Ready to testing!
