### ISSUE TITLE
dotnet is not recognized as internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by TanzimShaikh** [unosquare/passcore#275]
**PassCore Server**
- OS: [**Windows** ]
- Provider: [**Active Directory**]
- Settings file (without sensitive information): 

**Describe the bug**
While running the following command "**dotnet publish --configuration Release --runtime win-x64 --output 'C:\inetpub\wwwroot\PassCore363**'" it gives the error "_dotnet is not recognized as internal or external command, operable program or batch file_".

**To Reproduce**
1. Go to 'Run and type cmd.'
2. Right-Click on 'cmd and run as Administrator'
3. Run the command on the prompt 'dotnet publish --configuration ... etc. till the path'
4. See error dontnet is not an internal etc. till batch file'

**Expected behavior**
To see the command runs successfully message.

**Screenshots**
![CMD error](https://user-images.githubusercontent.com/49744138/56342827-c39dec80-61c1-11e9-81e3-4b05a667604c.png)

**Desktop (please complete the following information):**
 - OS: [Windows Server 2016]
 - Browser [NA but FireFox is the default browser]
 - Version [Datacenter]

**Comment by geoperez** [comment]
The `dotnet` executable is part of .NET Core. You need to download .NET Core SDK to build your own version or .NET Core Runtime to just run it. You can download both from https://dotnet.microsoft.com/download/dotnet-core/2.2

I would recommend download already compiled version of PassCore if you are not modifying the source code. And just install .NET Core Runtime & Hosting Bundle.

**Comment by TanzimShaikh** [comment]
Thank you Geoperez,
I am new to this so please bear with me and there is no solution available out there. Thanks to you for having this.
Where shall I download the compiled core from?

**Comment by TanzimShaikh** [comment]
I tried using your PowerShell commands but it keeps on opening the webpage to download the donet 2.1 webserver hosting bundle. I downloaded it and installed it as per your instructions. The powershell script doesn't move beyond downloading the dotnet 2.1 webserver hosting bundle.
Can you help please.

**Comment by geoperez** [comment]
That's odd. Let me check the script.

**Comment by TanzimShaikh** [comment]
Did you check the script Geoperez?

**Comment by geoperez** [comment]
Not yet, I've been busy with other projects. Sorry about that.

The script will check, using WMI, if you have any installed software with the label: "Microsoft .NET Core Host - 2.2.3"

`$netCoreHost = Get-wmiobject -class win32_product | Where-Object {$_.Name -match "Microsoft .NET Core Host - 2.2.3" }`

Can you open "Add or Remove Programs" in the machine where are you installing PassCore and check if there is any software with that similar name?

**Comment by TanzimShaikh** [comment]
I didn't find any file with the exact name as you have written. However I have found that few files with a similar name has been installed as shown in the below figure:


![Errorfile](https://user-images.githubusercontent.com/49744138/56909376-d0b7b700-6ab0-11e9-82ac-92cf8da40ecf.png)

**Comment by geoperez** [comment]
You need to install .NET Core 2.2. You have 2.1.

**Comment by TanzimShaikh** [comment]
I think you have to update your code:
![image](https://user-images.githubusercontent.com/49744138/57008380-60b44880-6bf8-11e9-8a5b-a170edc9ae7f.png)

<hr>

However I did installed .Net 2.2.4 and run the script but this time I received another error:
![image](https://user-images.githubusercontent.com/49744138/57008401-8b060600-6bf8-11e9-823a-247065159a2c.png)

<hr>

And the error when I run the page in the browser:
![image](https://user-images.githubusercontent.com/49744138/57008450-f7810500-6bf8-11e9-8245-60c95d573178.png)

**Comment by TanzimShaikh** [comment]
Ok so I installed wrong file. I installed Runtime while it should have been Hosting. I did installed the correct file and Alhamdulillaah it worked.
Thank you Geoperez for all your help.

**Comment by TanzimShaikh** [comment]
Hello Geoperez,
I facing the following issue:

> Failed to update password: The password does not meet the password policy requirements. Check the minimum password length, password complexity and password history requirements. (Exception from HRESULT: 0x800708C5)

No matter what password I put I face the issue. I have tried using the strong password as well as the password generator which generates quite extensive passwords but still the same issue.
