### ISSUE TITLE
HRESULT: 0x80070547 when trying to change password

### ISSUE THREAD

**Issue by avivnexus** [unosquare/passcore#276]
**PassCore Server**
- OS: [Windows Server 2019]
- Provider: [Active Directory]

When a user trying to change password he gets:
Failed to update password: Configuration information could not be read from the domain controller, either because the machine is unavailable, or access has been denied. (Exception from HRESULT: 0x80070547)
 
Anyone know how to fix this ?

**Comment by geoperez** [comment]
Did you check the network connectivity to the AD Domain server?

**Comment by avivnexus** [comment]
Hi, the passcore hosted on the AD server
