### ISSUE TITLE
An empty dialgogue box after pwd change

### ISSUE THREAD

**Issue by honzabfu** [unosquare/passcore#280]
**PassCore Server**
- OS: Windows Server 2016
- Provider: AD
- Settings file: default with "DefaultDomain": "domain.local" filled.

**Describe the bug**
When password is changed, an extra empty dialogue is displayed before "You have changed.." dialogue.

**To Reproduce**
Change password in MSIE locally or from other computer.

**Desktop (please complete the following information):**
 - OS: Windows 10, Windows Server 2016
 - Browser MSIE only
 - Version 11.2969, 11.2972

Chrome, Firefox and Edge do not show an extra dialogue. 

![2019-05-23_16-30-03](https://user-images.githubusercontent.com/50017605/58263706-ce2d4200-7d7c-11e9-9557-1c4d19c6d64c.png)
![2019-05-23_16-30-03 (1)](https://user-images.githubusercontent.com/50017605/58263719-d38a8c80-7d7c-11e9-9d11-1ed4aeb807ad.png)

**Comment by geoperez** [comment]
What version of IE are you using? We are not really proving support for MSIE.

**Comment by honzabfu** [comment]
We tested MSIE versions 11.2969 and 11.2972 with the same result.

**Comment by geoperez** [comment]
@honzabfu the contributor @minorumasuoka did some changes to the UI. Can you test again?

**Comment by honzabfu** [comment]
> @honzabfu the contributor @minorumasuoka did some changes to the UI. Can you test again?

There is no second empty dialogue in MSIE in v3.6.4. Thanks!
