### ISSUE TITLE
PassCore with AD LDS

### ISSUE THREAD

**Issue by Schlapper** [unosquare/passcore#281]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Update:

I changed some things in my configuration. Now i get the message.

Failed to update password: The supplied context type does not match the server contacted. The server type is ApplicationDirectory.

**Comment by geoperez** [comment]
Can you elaborate on the requirement?
