### ISSUE TITLE
Build own version

### ISSUE THREAD

**Issue by putrhlim** [unosquare/passcore#282]
**PassCore Server**
- OS: [Windows]
- Provider: [Active Directory]
- Settings file (without sensitive information): 

**Describe the bug**
Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 25.81 ms for C:\Users\muhd_halim\Desktop\Halim\chat\pw\passcore-master\src\Unosquare.PassCore.Common\Unosquare.PassCore.Common.csproj.
  Restore completed in 25.8 ms for C:\Users\muhd_halim\Desktop\Halim\chat\pw\passcore-master\src\Unosquare.PassCore.PasswordProvider\Unosquare.PassCore.PasswordProvider.csproj.
  Restore completed in 33.08 ms for C:\Users\muhd_halim\Desktop\Halim\chat\pw\passcore-master\src\Zyborg.PassCore.PasswordProvider.LDAP\Zyborg.PassCore.PasswordProvider.LDAP.csproj.
  Restore completed in 96.93 ms for C:\Users\muhd_halim\Desktop\Halim\chat\pw\passcore-master\src\Unosquare.PassCore.Web\Unosquare.PassCore.Web.csproj.
  Restore completed in 43.38 ms for C:\Users\muhd_halim\Desktop\Halim\chat\pw\passcore-master\src\Unosquare.PassCore.Web\Unosquare.PassCore.Web.csproj.
  Unosquare.PassCore.Common -> C:\Users\muhd_halim\Desktop\Halim\chat\pw\passcore-master\src\Unosquare.PassCore.Common\bin\Release\netstandard2.0\win-x64\Unosquare.PassCore.Common.dll
  Unosquare.PassCore.Common -> C:\Users\muhd_halim\Desktop\Halim\chat\pw\passcore-master\
  Unosquare.PassCore.Common -> C:\Users\muhd_halim\Desktop\Halim\chat\pw\passcore-master\src\Unosquare.PassCore.Common\bin\Release\netstandard2.0\Unosquare.PassCore.Common.dll
  Unosquare.PassCore.PasswordProvider -> C:\Users\muhd_halim\Desktop\Halim\chat\pw\passcore-master\src\Unosquare.PassCore.PasswordProvider\bin\Release\netstandard2.0\win-x64\Unosquare.PassCore.PasswordProvider.dll
  Unosquare.PassCore.PasswordProvider -> C:\Users\muhd_halim\Desktop\Halim\chat\pw\passcore-master\
  Unosquare.PassCore.PasswordProvider -> C:\Users\muhd_halim\Desktop\Halim\chat\pw\passcore-master\src\Unosquare.PassCore.PasswordProvider\bin\Release\netstandard2.0\Unosquare.PassCore.PasswordProvider.dll
  Zyborg.PassCore.PasswordProvider.LDAP -> C:\Users\muhd_halim\Desktop\Halim\chat\pw\passcore-master\src\Zyborg.PassCore.PasswordProvider.LDAP\bin\Release\netstandard2.0\win-x64\Zyborg.PassCore.PasswordProvider.LDAP.dll
  Unosquare.PassCore.Web -> C:\Users\muhd_halim\Desktop\Halim\chat\pw\passcore-master\src\Unosquare.PassCore.Web\bin\Release\netcoreapp2.2\win-x64\Unosquare.PassCore.Web.dll
  Zyborg.PassCore.PasswordProvider.LDAP -> C:\Users\muhd_halim\Desktop\Halim\chat\pw\passcore-master\
  Performing run Webpack publish...

  [at-loader] Using typescript@2.9.2 from typescript and "tsconfig.json" from C:/Users/muhd_halim/Desktop/Halim/chat/pw/passcore-master/src/Unosquare.PassCore.Web/tsconfig.json.

  [at-loader] Checking started in a separate process...

  [at-loader] Ok, 1.294 sec.

  WebpackCleanupPlugin: 0 file(s) deleted.
  Hash: 941fdbfdc32547f0d90f
  Version: webpack 3.12.0
  Time: 28842ms
                                   Asset       Size  Chunks                    Chunk Names
                  assets/images/logo.png    3.21 kB          [emitted]
                        vendor.bundle.js     974 kB       0  [emitted]  [big]  vendor
                     polyfills.bundle.js     145 kB       2  [emitted]         polyfills
                              index.html    3.06 kB          [emitted]
                           manifest.json  527 bytes          [emitted]
                      assets/favicon.ico    1.15 kB          [emitted]
                  assets/images/help.png  304 bytes          [emitted]
                          main.bundle.js     1.9 MB       1  [emitted]  [big]  main
         assets/images/passcore-logo.png    3.25 kB          [emitted]
         assets/fonts/Roboto/latin.woff2    15.3 kB          [emitted]
  assets/images/License_icon-mit.svg.png    17.9 kB          [emitted]
                   assets/images/osi.png    18.6 kB          [emitted]
           assets/styles/indigo-pink.css    50.8 kB          [emitted]
  assets/fonts/Roboto/Roboto-Regular.ttf     172 kB          [emitted]
    [82] (webpack)/buildin/global.js 509 bytes {2} [built]
   [184] ./ClientApp/app/change-password/app.change-password.ts 8.8 kB {1} [built]
   [213] ./node_modules/@angular/core/fesm5 lazy 160 bytes {0} [built]
   [214] ./ClientApp/app/dialog/app.dialog.ts 1.02 kB {1} [built]
   [268] multi whatwg-fetch ./ClientApp/main.ts 40 bytes {1} [built]
   [270] ./ClientApp/main.ts 572 bytes {1} [built]
   [271] ./ClientApp/app/app.module.ts 2.44 kB {1} [built]
   [272] ./ClientApp/app/app.routing-module.ts 907 bytes {1} [built]
   [433] ./ClientApp/app/change-password/app.change-password.css 945 bytes {1} [built]
   [437] ./ClientApp/app/footer/app.footer.ts 707 bytes {1} [built]
   [438] ./ClientApp/app/footer/footer.html 1.53 kB {1} [built]
   [439] ./ClientApp/app/footer/app.footer.css 705 bytes {1} [built]
   [440] ./ClientApp/app/app.material-module.ts 1.37 kB {1} [built]
   [447] ./ClientApp/vendor.ts 416 bytes {0} [built]
   [449] ./ClientApp/polyfills.ts 195 bytes {2} [built]
      + 651 hidden modules

  WARNING in ./node_modules/@angular/core/fesm5/core.js
  4982:15-36 Critical dependency: the request of a dependency is an expression
   @ ./node_modules/@angular/core/fesm5/core.js
   @ ./ClientApp/main.ts
   @ multi whatwg-fetch ./ClientApp/main.ts

  WARNING in ./node_modules/@angular/core/fesm5/core.js
  4994:15-102 Critical dependency: the request of a dependency is an expression
   @ ./node_modules/@angular/core/fesm5/core.js
   @ ./ClientApp/main.ts
   @ multi whatwg-fetch ./ClientApp/main.ts
  Child html-webpack-plugin for "index.html":
       1 asset
         [0] ./node_modules/html-webpack-plugin/lib/loader.js!./ClientApp/index.html 3.05 kB {0} [built]
  Coping files to publish...
  Unosquare.PassCore.Web -> C:\Users\muhd_halim\Desktop\Halim\chat\pw\passcore-master\

**To Reproduce**
After I executed this line <dotnet publish --configuration Release --runtime win-x64 --output "<path>"> how can i open it?

**Desktop (please complete the following information):**
 - Windows 10 Pro
 - Browser [chrome]

**Comment by geoperez** [comment]
Are you filling the output parameter?
