### ISSUE TITLE
switch between languages for bilingual business

### ISSUE THREAD

**Issue by dsavaria12** [unosquare/passcore#284]
I need to be able to change the language by clicking on a button like many other sites because our business has french employes.
A button by the ? icon on the upper right that redirect to the french page is what I would like to do.

For now, I have hosted 2 different pages and for the french page, I have changed the text language in the appsetting file, but it is not a great method.
I have no idea how to modify source code, but if you have a link that shows how to, I'd like to learn!

**Comment by kadosh** [comment]
Hi @dsavaria12 ,

Passcore doesn't support internationalization and we don't have any plans to add it. However, you can download the free trial of Passcorepro which already supports multiple languages.

Please feel free to give it a try. You can find it at: https://store.unosquare.com/PasscorePro. Let me know if you have any other doubts

**Comment by geoperez** [comment]
Hello @dsavaria12 , did you get a chance to test passcore pro?

**Comment by dsavaria12** [comment]
Yeah, I tried passcore pro but it is not exacly what we were looking for.
Passcore was easier to work with.

De : Geovanni Perez <notifications@github.com>
Envoyé : 9 juillet 2019 12:07
À : unosquare/passcore <passcore@noreply.github.com>
Cc : Savaria, Dominic <dsavaria@gcmconsultants.com>; Mention <mention@noreply.github.com>
Objet : Re: [unosquare/passcore] switch between languages for bilingual business (#284)

This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.
Ce courrier électronique provient de l'extérieur de l'organisation. Ne cliquez pas sur les liens ni n'ouvrez aucune pièce jointe, sauf si vous reconnaissez l'expéditeur et savez que le contenu est sécurisé.


Hello @dsavaria12<https://github.com/dsavaria12> , did you get a chance to test passcore pro?

**Comment by geoperez** [comment]
Can I reach you by email to get some insights?

**Comment by dsavaria12** [comment]
Sure what do you want to know?

De : Geovanni Perez <notifications@github.com>
Envoyé : 11 juillet 2019 09:51
À : unosquare/passcore <passcore@noreply.github.com>
Cc : Savaria, Dominic <dsavaria@gcmconsultants.com>; Mention <mention@noreply.github.com>
Objet : Re: [unosquare/passcore] switch between languages for bilingual business (#284)

This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.
Ce courrier électronique provient de l'extérieur de l'organisation. Ne cliquez pas sur les liens ni n'ouvrez aucune pièce jointe, sauf si vous reconnaissez l'expéditeur et savez que le contenu est sécurisé.


Can I reach you by email to get some insights?
