### ISSUE TITLE
sub directories

### ISSUE THREAD

**Issue by mvaillancourt81** [unosquare/passcore#285]
I want to run passcore into a subdirectory of a site. password.domain.com/en. 
I have error 500.0 with aspnetcoremodulev2 error code 0x800040005. 
I created a virtualdirectory named en pointing on c:\inetpub\wwwroot\passcore\en
I modify wwwroot\index.html base path to "\en\"
Folder EN 
--------logs (folder)
--------runtimes (folder)
--------wwwroot (folder)
appsettings.json
*.dll

**Comment by geoperez** [comment]
What is the issue?

**Comment by mvaillancourt81** [comment]
Not able to run in subdirectory



Marc Vaillancourt
Directeur adjoint - Technologies de l’information
T 514.351.8350 · F 514.351.5227 – C 514.704.3317
[cid:image001.jpg@01D4F3B6.B9441030]<http://www.gcmconsultants.com/nous-joindre.html>

​                  [cid:image002.png@01D4F3B6.B9441030] <https://www.linkedin.com/company/gcm-consultants/>    [cid:image003.png@01D4F3B6.B9441030] <https://www.facebook.com/GCM-Consultants-2102918579815016/>    [cid:image004.png@01D4F3B6.B9441030] <http://www.gcmconsultants.com/>

GC​MC​ONSULTAN​TS
​9496, boul. du Golf, Montréal (Québec) H1J 3A1​

​www.gcmconsultants.com<http://www.gcmconsultants.com/>
Ce message électronique et tous les fichiers joints qu'il contient sont confidentiels et destinés à l'usage de la personne à laquelle ils sont adressés. Si vous n'êtes pas le destinataire visé (ou si vous ne recevez pas la présente communication au nom du destinataire), merci d'en aviser immédiatement l'expéditeur et de supprimer le présent message sans le retransmettre ou en enregistrer le contenu.

De : Geovanni Perez <notifications@github.com>
Envoyé : 10 juillet 2019 15:05
À : unosquare/passcore <passcore@noreply.github.com>
Cc : Vaillancourt, Marc <mvaillancourt@gcmconsultants.com>; Author <author@noreply.github.com>
Objet : Re: [unosquare/passcore] sub directories (#285)

This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.
Ce courrier électronique provient de l'extérieur de l'organisation. Ne cliquez pas sur les liens ni n'ouvrez aucune pièce jointe, sauf si vous reconnaissez l'expéditeur et savez que le contenu est sécurisé.


What is the issue?

**Comment by mvaillancourt81** [comment]
I configure the subfolder as an application and now I'm stuck on "Loading passcore".

**Comment by mvaillancourt81** [comment]
It work with your build. If I'm using our build it fails.

**Comment by geoperez** [comment]
Are you getting issues building? Are you just modifying the front-end?

**Comment by mvaillancourt81** [comment]
We modified Frontend and main.bundle.js to detect navigator.language.



Marc Vaillancourt
Directeur adjoint - Technologies de l’information
T 514.351.8350 · F 514.351.5227 – C 514.704.3317
[cid:image001.jpg@01D4F3B6.B9441030]<http://www.gcmconsultants.com/nous-joindre.html>

​                  [cid:image002.png@01D4F3B6.B9441030] <https://www.linkedin.com/company/gcm-consultants/>    [cid:image003.png@01D4F3B6.B9441030] <https://www.facebook.com/GCM-Consultants-2102918579815016/>    [cid:image004.png@01D4F3B6.B9441030] <http://www.gcmconsultants.com/>

GC​MC​ONSULTAN​TS
​9496, boul. du Golf, Montréal (Québec) H1J 3A1​

​www.gcmconsultants.com<http://www.gcmconsultants.com/>
Ce message électronique et tous les fichiers joints qu'il contient sont confidentiels et destinés à l'usage de la personne à laquelle ils sont adressés. Si vous n'êtes pas le destinataire visé (ou si vous ne recevez pas la présente communication au nom du destinataire), merci d'en aviser immédiatement l'expéditeur et de supprimer le présent message sans le retransmettre ou en enregistrer le contenu.

De : Geovanni Perez <notifications@github.com>
Envoyé : 11 juillet 2019 09:58
À : unosquare/passcore <passcore@noreply.github.com>
Cc : Vaillancourt, Marc <mvaillancourt@gcmconsultants.com>; Author <author@noreply.github.com>
Objet : Re: [unosquare/passcore] sub directories (#285)

This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.
Ce courrier électronique provient de l'extérieur de l'organisation. Ne cliquez pas sur les liens ni n'ouvrez aucune pièce jointe, sauf si vous reconnaissez l'expéditeur et savez que le contenu est sécurisé.


Are you getting issues building? Are you just modifying the front-end?

**Comment by geoperez** [comment]
Did you check Chrome Debugger console?
