### ISSUE TITLE
Could not load file or assembly 'System.Diagnostics.DiagnosticSource

### ISSUE THREAD

**Issue by dsavaria12** [unosquare/passcore#287]
I modified the source code and now when I run Unosquare.PassCore.Web.exe in cmd I get this error:

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at Unosquare.PassCore.Web.Startup.Main(String[] args)

But the file System.Diagnostics.DiagnosticSource.ddl is there... and  .NET Framework 4.6.1 is installed
Here is my dotnet info:

.NET Core SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]
  3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by geoperez** [comment]
Did you get any issues at the build process?

**Comment by dsavaria12** [comment]
No, I ran this dotnet publish --configuration Release --runtime win-x64 --output "<path>" in cmd as administrator and it worked fine

**Comment by geoperez** [comment]
Did you change the project to run with NET 4.6.1? Because right now the project is a .NET Core App 2.2.

You can try with dotnet run.

**Comment by dsavaria12** [comment]
Ok si when I run : \passcore-master2\src\Unosquare.PassCore.Web>dotnet run, it work. But I still get an error... 
_The launch profile "(Default)" could not be applied._
_A usable launch profile could not be located._
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\dsavaria\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Hosting environment: Production
Content root path: c:\Users\dsavaria\Desktop\passcore-master2\src\Unosquare.PassCore.Web
Now listening on: http://localhost:5000

Not sure if it is normal but then what am I suppose to do? I'm really new in source code, etc..

**Comment by geoperez** [comment]
That is normal output, you can browse the localhost:5000?

**Comment by dsavaria12** [comment]
Yes it works

**Comment by dsavaria12** [comment]
My question is if it work with dotnet run, why does the site gives a 502.5 error after i dotnet publish?
