### ISSUE TITLE
Update angular http

### ISSUE THREAD

**Issue by AnyxLeo** [unosquare/passcore#289]
**Is your feature request related to a problem? Please describe.**
@angular/http@6.1.10 is deprecated

**Describe the solution you'd like**
Switch to  @angular/common/http

**Additional context**
https://angular.io/guide/http

**Comment by geoperez** [comment]
Also, update Angular to the latest version.

**Comment by geoperez** [comment]
We are moving the front-end to React, this is no longer a valid issue.
