### ISSUE TITLE
Install in subfolder

### ISSUE THREAD

**Issue by th3b00** [unosquare/passcore#29]
Hello.
Installation with README went ok and app is working as main app. But I need it to integrate it with my current app working with one ssl cert. After adding app as subfolder I get only:

```
PassCore logo
Powered by PassCore v2.0.2.beta.2 - OSS and MIT Licensed
Copyright © 2016 Unosquare
```

Is it possible to install app as subfolder of default site?

**Comment by mariodivece** [comment]
Duplicate of #30

**Comment by geoperez** [comment]
Check the latest version.
