### ISSUE TITLE
Error Information: Unknown error (0x8000500c)

### ISSUE THREAD

**Issue by roflharris** [unosquare/passcore#3]
Hola Mario, 

I'm the BigFrodo guy [here ](http://forums.asp.net/p/2082720/6010940.aspx) and the reason I was digging around and googling your issue original is that my organisation runs PassCore that was set up by a previos tech with no documentation and is now spitting out the above error (Unknown error (0x8000500c)) whenever the user submits the password. After upgrading to PassCore v2.0 it's still the same error message but [much prettier](http://imgur.com/eXKAiJ2)

After a proper google-fu I believe I somehow overlooked [this fix ](https://support.microsoft.com/en-us/kb/2802148)before and I'll report back if it works. Until then I thought I'd leave the link here in case any other hapless techs like myself encounter it and are looking for answers in the passcore issues log.

**Comment by roflharris** [comment]
no bueno, fix is for Windows Server 2012 while this is happening on our 2008 server. Will investigate further but any suggestions would be much appreciated.

**Comment by mariodivece** [comment]
I searched for this error and read more about it. It might be because you are using an older version of Active Directory. I could not find any clear evidence of why this might be occurring though. Maybe try and setup a VM with a sample installation of AD (Windows Server 2012 or higher) and test it out?

**Comment by mariodivece** [comment]
No responses in about a month now. Closing issue.
