### ISSUE TITLE
Multiple domains or applications

### ISSUE THREAD

**Issue by jkberry** [unosquare/passcore#30]
Multiple domain support in PassCore would be a useful feature.  Without multiple domain support, is it possible to configure more than one instance of PassCore as independent applications beneath a single IIS website instance so that, for example, website/domain1 and website/domain2 could be independently configured with UseAutomaticContext set to false and explicit domain information and credentials?

**Comment by mariodivece** [comment]
That would certainly be a useful feature. Currently it is not supported but I will add it as a nice to have.

**Comment by marubadi** [comment]
Hi, i just managed to install passcore.  Please refer to the screenshot and your help is requred.  thanks
![capture](https://user-images.githubusercontent.com/35490562/34987917-e6f27fc2-facd-11e7-9b82-60553e5bf8c0.PNG)

**Comment by geoperez** [comment]
Check the latest version.
