### ISSUE TITLE
Problem with config limit account "Log On To"

### ISSUE THREAD

**Issue by nbnew25** [unosquare/passcore#31]
My company domain account is limited log on to with their computer.
When I change password with passcore, I have issue :
The password change operation failed with the following message: The system detected a possible attempt to compromise security. Please ensure that you can contact the server that authenticated you. (Exception from HRESULT: 0x800704F1)

**Comment by mariodivece** [comment]
Have you tried setting UseAutomaticContext to false and setting the correct Domain Admin credentials in the config file?

**Comment by stpgh** [comment]
You can try the patche kb3177108 and kb3167679 uninstall . That worked for me .
