### ISSUE TITLE
Recaptcha v3 is a bad choice for this type of app

### ISSUE THREAD

**Issue by xxbiohazrdxx** [unosquare/passcore#320]
**Is your feature request related to a problem? Please describe.**
Recaptcha v3 is more reliable for large, complex websites/apps. It uses analytics on as many pages as possible to track a user's interactions with the site over a long period of time. A small app that consists of a single page and that is rarely visited by a user and only for a few seconds is not enough data for Recaptcha v3 to be reliable.

Without a fallback to select images, etc. Recaptcha v3 fails for me frequently in PassCore v4

**Describe the solution you'd like**
Re-add support for Recaptcha v2

**Comment by geoperez** [comment]
@Serk352 there is a way to support both versions in the React component that you used?

**Comment by geoperez** [comment]
@Serk352 can you give it a chance to this issue this week?

**Comment by Serk352** [comment]
@geoperez  sure, I will.

**Comment by geoperez** [comment]
@xxbiohazrdxx can you verify the new implementation?

**Comment by dragoangel** [comment]
@geoperez getting Could not verify you are not a robot after update from 3 to 4 version all time.

**Comment by Serk352** [comment]
Hi @dragoangel, there's a new release that fixed this issue, please try it.

**Comment by messiah109501** [comment]
I had same issue as dragoangel with the captcha v2 verification. Just updated to 4.2.2 and issue remains.

**Comment by dragoangel** [comment]
@Serk352 ok will try 4.2.2

**Comment by dragoangel** [comment]
@Serk352 build from 4.2.2 GET https://change-pwd.ua.pnnsoft.com/api/password net::ERR_ABORTED 500 and page loading endless

**Comment by avoit** [comment]
Hi All,

Everything is working except the Recaptcha part. I keep getting could not verify you are not a robot error. Anything specific I need to check? I used V2 & V3 with the correct site and secret keys.

**Comment by geoperez** [comment]
@Serk352 can you take a look in the Recaptcha issue?

**Comment by dragoangel** [comment]
@geoperez Hi, after update to 4.2.3 I can successfully build app for linux. I had issues with nuget packages via npm install cli, but via Visual Studio 2019 Community it works. Doesn't know why exactly.
