### ISSUE TITLE
IE11 Support - App just display an empty screen

### ISSUE THREAD

**Issue by jamesxv7** [unosquare/passcore#324]
**PassCore Server**
- OS: Not impacted
- Provider: Not impacted
- Settings file (without sensitive information): Not impacted

**Describe the bug**
A new 4.00 deploy using React for client, when trying to open the app from IE11 the app just display an empty screen. 

Console logs an SCRIPT1002: Syntax error. File: App.ba8f5c53.js, Line: 461, Column: 295. 

Refer to screenshots for more details. 

**To Reproduce**
Access app using IE11.

**Expected behavior**
Since there is no indication in the documentation that IE11 is not supported, it is expected that the tool will work on IE11 browser. 

**Screenshots**

![2019-08-23_9-16-25](https://user-images.githubusercontent.com/121668/63595556-3d3a5280-c587-11e9-9346-9333d99ba2e2.jpg)
![2019-08-23_9-19-10](https://user-images.githubusercontent.com/121668/63595564-3f9cac80-c587-11e9-89a8-8986e2c5b4dc.jpg)

**Desktop (please complete the following information):**
 - Device: Desktop
 - OS: Windows 7
 - Browser IE11
 - Version 11.0.9600.19399

**Comment by geoperez** [comment]
Hi @jamesxv7, sorry but we are not supporting IE11 in this version. I need to update the documentation with the minimal browser versions.
