### ISSUE TITLE
HTTP Error 502.5 on PassCore 3.7.0

### ISSUE THREAD

**Issue by xxbiohazrdxx** [unosquare/passcore#326]
**PassCore Server**
- OS: Windows Server 2019
- Provider: Active Directory
- Settings file (without sensitive information): 
Default

**Describe the bug**
When attempting to use PassCore 3.7.0, error 502.5 is presented. I have tried with Net Core Hosting runtime 2.2.0, 2.2.3, and 2.2.7

Version 3.6.4 and 4.0.0 both work as expected.

**Additional context**
Logfile output contains the following

`Error:
  An assembly specified in the application dependencies manifest (Unosquare.PassCore.Web.deps.json) was not found:
    package: 'runtime.win-x64.Microsoft.NETCore.App', version: '2.2.0'
    path: 'runtimes/win-x64/native/api-ms-win-core-file-l2-1-0.dll'`

**Comment by geoperez** [comment]
I need to rebuild the package.

**Comment by geoperez** [comment]
Do you test more recent versions?

**Comment by xxbiohazrdxx** [comment]
I have not yet had an opportunity to test as my schedule has been extremely tight. I will try the change this week or next.
