### ISSUE TITLE
enforce edit distance when resetting passwords

### ISSUE THREAD

**Issue by graingert** [unosquare/passcore#329]
**Is your feature request related to a problem? Please describe.**
When resetting passwords users often "increment" their password eg:

hunter2 -> hunter3 -> hunter4 ...

**Describe the solution you'd like**
It should be possible to configure an edit distance score function and threshold eg levenshtein distance between previous password and new password

**Describe alternatives you've considered**
I've considered none

**Additional context**
No additional context

**Comment by geoperez** [comment]
I can't see the pattern, I only see

****** -> ****** -> ****** ...

😆😆😆

Just kidding, I like the idea. Let me try to check if we can work on it.

Thanks!

**Comment by graingert** [comment]
Bunp

**Comment by geoperez** [comment]
Do you know a C# implementation?

**Comment by graingert** [comment]
Bump

**Comment by graingert** [comment]
bump

**Comment by Serk352** [comment]
Hi, @graingert I added an approach to measure the edit distance using Levenshtein distance as you suggested. You can set the minimum distance between old and new password using the "MinimumDistance" setting.
