### ISSUE TITLE
Error 502.3 - Bad Gateway in browser

### ISSUE THREAD

**Issue by kbisignani** [unosquare/passcore#33]
So to start, please know that I'm an IIS noob.  Hand me an .htaccess file and some PHP code in Apache and I can move mountains.  But IIS and ASP... I am so lost.

I think the issue is with the httpPlatformHandler.  But first, let me give you my setup:
**Here's what I'm running:**
- Windows Server 2012 R2 x64
- IIS 8.5
- httpPlatformHandler x64 version 1.2

**Here's what I did:**
- I ran through the instructions in the ReadMe file first.
- I then ran through the instructions at https://github.com/unosquare/passcore/issues/24

**Here's what I get:**
I get a web page that does load, but it is giving me a "HTTP Error 502.3 - Bad Gateway"
This page contains other nuggets of information like:
- Module: httpPlatformHandler
- Notification: ExecuteRequestHandler
- Error Code: 0x8007053d
- Physical Path: C:\inetpub\passcore-master\src\Unosquare.PassCore.Web\wwwroot

Everytime I browse to the website, I get 10 Errors in the Windows Application Log that read:
- Process '0' failed to start.  Port = 28844, Error Code = '-2147024894'.

(each time the port number changes to some other random number)
After the tenth Error, I get an Information message that reads:
- Maximum rapid fail count per minute of '10' exceeded.

I tried disabling all firewalls, same result.
I tried rebooting about two dozen times, same result.
I tried uninstalling and reinstalling the httpPlatformHandler about three times, same result.

Googling various error messages and error codes brought me into the depths of httpPlatformHandler hell, with most of the results being tailored to the developers of applications, not end users, so I really wasn't 100% certain I understood what I was reading half the time.   I found myself at sites like:
https://github.com/aspnet/Hosting/issues/364
and
https://github.com/aspnet/Home/issues/1000
and
https://github.com/aspnet/IISIntegration/issues/45

I got the idea from one of those posts to set "stdoutLogEnabled" to true in the web.config file.  All that does, however, is create additional warnings in the Application log that read "Could not create stdoutLogFile \?\C:\inetpub\logs\stdout_2852)201682445931.log. ErrorCode = -2147024891."

In a move of sheer desperation, I gave "Everyone" full rights to the inetpub directory.  It started to create the stdout error log files, but unfortunately, they were all empty.

(I have since removed the Everyone permission and changed the stdoutLogEnabled flag back to false.)

Since I don't think this is a PassCore problem and more of an httpPlatformHandler issue (or a "I don't know what I'm doing and shouldn't be given sharp objects" issue), I don't know if anyone here can really help.  But if anyone knows or understands what I'm talking about and can at the very least point me in the direction of a place or post that can shed some light on what I might possibly be doing wrong, I'd very much appreciate it.

Thank you.

**Comment by kbisignani** [comment]
Just a quick update - I decided to blow everything up, format the server, start from scratch.

Installed Server 2012 R2
Configure server IP, server name, joined it to a domain

Logging in as the local admin (I used a domain login last time), I then...
Did a fresh install of IIS 8.5
Installed everything in the exact order as prescribed in https://github.com/unosquare/passcore/issues/24 (although steps 9 and 10 there was a little back and forth).

The end result - the exact same thing.  So, the good news is I'm happy to see that I can repeat the problem.  It means I didn't do something silly the last time to cause the issue.  But, unfortunately, the bad news, I'm still stuck on implementing this.

Not sure if anyone has had a chance to even look at this, but I figured I'd post my progress.

Thank you again.

**Comment by Hardywo** [comment]
Hi Kbisignani,
I am also receiving the same 502.3 error after following all of the directions carefully, and then even starting over and repeating the process twice! Have you been able to find a solution yet? Thank you for your help!
Bill

**Comment by kbisignani** [comment]
I never did.  I ended up rolling my own - used C# and ASP.NET.  If I can find a few moments to myself, I'll post the source.  One caveat I ran in to though was I needed to put in a config file Active Directory credentials for access.  But a positive - it will check the "must change password" value and let you validate the password even if that's checked (by programmatically unchecking the box, validating the old password, and then rechecking the box).
Let me know if you're interested...

**Comment by Hardywo** [comment]
Thanks for your reply! I am interested in hearing your solution as I need a way for remote, email only users to be able to change their passwords. Thanks for your help and hopefully I can get Passcore working eventually too!

**Comment by Hardywo** [comment]
I was able to get it working today! The issue was that my wwwroot folder was missing the bin, Content, and Views folders, along with Global.asax, packages.config, and a more expanded Web.config file. These files can all be found in PassCore.zip on [the original post about PassCore](https://unopasscore.codeplex.com/releases/view/106556). Now my top level folder has approot, logs, and wwwroot from passcore-2.0.2.beta.2-2016-03-14.zip and then I put added the contents of PassCore.zip to the wwwroot folder. Now my final step before releasing the site is branding it with my company logo and information. Good luck and let me know if you need any help!

**Comment by kbisignani** [comment]
Huh.  So the trick is to put all the files and folders in the main root of
the visible web folder... I'll have to give that a shot!  Thank you for
letting me know.

**Comment by mariodivece** [comment]
Please try with the latest version and let us know if this is still a problem. Reopen the issue if necessary.
