### ISSUE TITLE
Force server side random generation of new passwords

### ISSUE THREAD

**Issue by graingert** [unosquare/passcore#330]
**Is your feature request related to a problem? Please describe.**
Users often select insecure passwords, either passwords that are dictionary words or duplicated on other sites. Even if a password is "zxcvbn secure" it's difficult to determine if the password has been re-used or will be written down.

If the server generates the password we can at least guarantee it has not been used elsewhere before. If the password is of a very large length 100-300 or so characters we can ensure it's unlikely to be written down and will encourage if not require use of a password manager.

**Describe the solution you'd like**
Have the server generate the password and display it once for copying by the user. Add a configuration option to prevent the user from customizing the password.

**Describe alternatives you've considered**
Use zxcvvbn to enforce passwords that appear random and generated

**Additional context**
No additional context

**Comment by geoperez** [comment]
I like this idea too. My only concern is that we don't have enough time to work on this feature.

**Comment by graingert** [comment]
@geoperez out of the issues I raised zxcvbn, distance function and this one, this one is the highest priority

**Comment by geoperez** [comment]
This is ready for testing!
