### ISSUE TITLE
The Variables in "RestrictedADGroups" and "AllowedADGroups" in appsettings.json aren't being honored.

### ISSUE THREAD

**Issue by LeftShoeAT2ShoesDE** [unosquare/passcore#333]
**PassCore Server**
- OS: Windows Server 2008R2
- Provider: Active Directory
- Settings file (without sensitive information): 
[appsettings.json.txt](https://github.com/unosquare/passcore/files/3583905/appsettings.json.txt)

**Describe the bug**
The Variables in RestrictedADGroups and AllowedADGroups in 
 [IIS_ROOT]\PassCore\appsettings.json
 aren't being honored. I can, without failure, change any domain-admin passwords I like (given I know the origianal PW of course), even though only the members of the AD-Group "ExternalUsers" should be allowed to update their passwords. Please analyse my settings an tell me if I missed something.

**To Reproduce**
normal use

**Expected behavior**
only allow users that are members of the AD-Group "ExternalUsers" 

**Screenshots**
NOT APPLICABLE

**Desktop (please complete the following information):**
 - OS: Windows 10 1903, Mac OsX
 - Browser MS EDGE, Opera, safari in Mac OsX
 - Version Windows 10 1903,  Mac OsX 10.14.6

**Additional context**

**Comment by geoperez** [comment]
Your settings look fine. Let me take a look in the code.

**Comment by LeftShoeAT2ShoesDE** [comment]
I thank you very much 




Outlook for Android herunterladen







On Fri, Sep 6, 2019 at 4:42 PM +0200, "Geovanni Perez" <notifications@github.com> wrote:












Your settings look fine. Let me take a look in the code.

**Comment by Serk352** [comment]
@LeftShoeAT2ShoesDE could you please tell me which IPasswordChangeProvider implementation are you using?

**Comment by geoperez** [comment]
Are you running the Windows provider or LDAP (Linux) Provider?

**Comment by LeftShoeAT2ShoesDE** [comment]
Windows 2008r2




Outlook for Android herunterladen







On Wed, Sep 18, 2019 at 5:29 PM +0200, "Geovanni Perez" <notifications@github.com> wrote:












Are you running the Windows provider or LDAP (Linux) Provider?

**Comment by LeftShoeAT2ShoesDE** [comment]
Good day Señior Perez, any updates on this issue?

I would greatly appreciate an update.

**Comment by geoperez** [comment]
Hi, we did some testing on our end, buy @Serk352 was not able to reproduce.  I'm going to give a try again by myself.

**Comment by geoperez** [comment]
Quick question, can you post the log file? Sometimes the AD is not returning properly the user's groups and this might bypass the groups check.

**Comment by LeftShoeAT2ShoesDE** [comment]
Which log do you need and where may I locate it?

**Comment by geoperez** [comment]
You may need to activate, check step 9 https://github.com/unosquare/passcore#installation-on-iis

**Comment by geoperez** [comment]
Did you get the logs?

**Comment by LeftShoeAT2ShoesDE** [comment]
HI sorry for the delay: here is the relevant part of the log
```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 POST http://[URL]/PassCore/api/password application/json 117
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Route matched with {action = "Post", controller = "Password"}. Executing action Unosquare.PassCore.Web.Controllers.PasswordController.Post (Unosquare.PassCore.Web)
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Unosquare.PassCore.Web.Controllers.PasswordController.Post (Unosquare.PassCore.Web) with arguments (Unosquare.PassCore.Web.Models.ChangePasswordModel) - Validation state: Valid
info: Unosquare.PassCore.PasswordProvider.PasswordChangeProvider[0]
      PerformPasswordChange for user adm-passcore
warn: Unosquare.PassCore.PasswordProvider.PasswordChangeProvider[0]
      Using AutomaticContext
fail: Unosquare.PassCore.PasswordProvider.PasswordChangeProvider[888]
      ValidateGroups
Unosquare.PassCore.Common.ApiErrorException: Error Code: ChangeNotPermitted
**The User principal is listed as restricted**
   at Unosquare.PassCore.PasswordProvider.PasswordChangeProvider.ValidateGroups(UserPrincipal userPrincipal) in C:\Unosquare\passcore\src\Unosquare.PassCore.PasswordProvider\PasswordChangeProvider.cs:line 144
dbug: Unosquare.PassCore.PasswordProvider.PasswordChangeProvider[0]
      **The User principal password updated with setPassword**
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action method Unosquare.PassCore.Web.Controllers.PasswordController.Post (Unosquare.PassCore.Web), returned result Microsoft.AspNetCore.Mvc.JsonResult in 1363.5664ms.
info: Microsoft.AspNetCore.Mvc.Formatters.Json.Internal.JsonResultExecutor[1]
      Executing JsonResult, writing value of type 'Unosquare.PassCore.Web.Models.ApiResult'.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action Unosquare.PassCore.Web.Controllers.PasswordController.Post (Unosquare.PassCore.Web) in 1480.5211ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 1499.7316ms 200 application/json; charset=utf-8
```
is there a setting to route the POST-Request over HTTPS?

![image](https://user-images.githubusercontent.com/30696507/66307056-a857a280-e903-11e9-8561-ea24e93bf00a.png)

**Comment by geoperez** [comment]
Status?

**Comment by LeftShoeAT2ShoesDE** [comment]
Sorry, I  unfortunately had more pressing issues to attend. I'll look into updating this by Friday and will report my findings when I do.
