### ISSUE TITLE
PS installer fails at Get-IISAppPool

### ISSUE THREAD

**Issue by wtip** [unosquare/passcore#334]
**PassCore Server**
- OS: [Windows Server 2012 R2]
- Provider: [Active Directory]
- Settings file (without sensitive information): 

**Describe the bug**
Tried running the powershell installer and it failed at 
```
Get-IISAppPool : The term 'Get-IISAppPool' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:60 char:5
+     Get-IISAppPool $iisAppPoolName
+     ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-IISAppPool:String) [], CommandNotFoundException
```
It looks like this module might not be available on 2012 r2.

**Comment by geoperez** [comment]
Do you have IIS installed? The IIS Management cmdlets are available only with IIS.

**Comment by wtip** [comment]
yes it is installed and a default site is running.
I just ran ` Install-Module –Name IISAdministration` and now `Get-IISAppPool` works

**Comment by geoperez** [comment]
So the PS installer is working for you?

**Comment by wtip** [comment]
yes after installing the module it worked

**Comment by sanzic-wes** [comment]
I have the same problem. Running powershell 4.0
PS C:\Windows\system32> $psversiontable

Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.3.9600.19170
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

**Comment by sanzic-wes** [comment]
PS C:\Windows\system32> Install-Module –Name IISAdministration
Install-Module : The term 'Install-Module' is not recognized as the name of a cmdlet, function, script file, or operable
At line:1 char:1
+ Install-Module –Name IISAdministration
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Install-Module:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
