### ISSUE TITLE
Cannot contact a domain controller

### ISSUE THREAD

**Issue by tedbass** [unosquare/passcore#34]
Installed and got running.  However trying to change the first password gives me this error:

"There was an error changing your password
Error Information: The system cannot contact a domain controller to service the authentication request. Please try again later. (Exception from HRESULT: 0x800704F1)"

I had this issue with a different password manager as well.  It seems MS did some shifting around on their changing password policies with a MS update.  see https://support.microsoft.com/en-us/kb/3177108  

Any ideas?

**Comment by tedbass** [comment]
Before you ask, Ive already uninstalled this update from all the dcs and from this server as well.  Same issue

**Comment by dkkazak** [comment]
We have started to see this happen in our environment.  I don't think it is related to the KB as that refers to disabled or expired accounts.  Sometimes if I restart the web service, it seems to work again for awhile, but not always.

**Comment by tedbass** [comment]
Found out there is another KB that needs to be uninstalled KB3167679
