### ISSUE TITLE
Unable to change expired password

### ISSUE THREAD

**Issue by lucafabbri365** [unosquare/passcore#343]
**PassCore 4.0.0 Server**

- OS: Windows Server 2012 R2 (domain-joined)
- Provider: Active Directory
- PassCore AppPool runs with "LocalSystem"

I get the error "You need to provide the correct current password." when I try to change a password when it is expired.

Is there a way to solve it ? With reference to [Cannot Change Expired Password -- Version 3.4.2 #225](https://github.com/unosquare/passcore/issues/225)
Using a privileged "service account" for AppPool ?

Thank you,
Luca

**Comment by geoperez** [comment]
You need to set the setting 'UpdateLastPassword' to true, and provide an account with enough permissions to change the LDAP attribute in Active Directory.

Using passcore without a credential will use automatic context using the user's provided credentials and usually they don't have enough permissions to reset the expired password flag.

**Comment by lucafabbri365** [comment]
Hello @geoperez,
thank you for your e-mail.

Do you think a service user with these attribute set, could be enough for PassCore ?

- Change password
- Reset password
- Read pwdLastSet
- Write pwdLastSet
- Read accountExpires
- Write accountExpires

Thank you,
Luca

**Comment by geoperez** [comment]
AccountExpires is not used by passcore, the first 4 items are correct.

**Comment by lucafabbri365** [comment]
Hello again @geoperez,
sorry but do I need to set the Service Account in AppPool or inside appsettings.json (and leave "LocalSystem" for AppPool) ?

Thank you again,
Luca

**Comment by geoperez** [comment]
The Service Account in AppPool is independent. The credentials in appsettings.json are the one used to connect to AD.

**Comment by lucafabbri365** [comment]
Hello @geoperez,
I made these changes:

1. Set AppPool to run as LocalSystem (as originally)
2. Created a domain user (Service Account) and assigned these permissions on OU containing users:

a. Change & reset Password
b. Read & write pwdLastSet

3. Changed **appsettings.json**:

"UpdateLastPassword": true
"LdapHostnames": [ "" ]
"LdapPort": 389,
"LdapUsername": "CN=PassCore,CN=Users,DC=Domain,DC=local",
"LdapPassword": "<Password>",
"DefaultDomain": ""

I commented _LdapSearchBase_, _LdapSecureSocketLayer_, _LdapStartTls_, _LdapChangePasswordWithDelAdd_, _LdapSearchFilter_ because (I suppose) it is using Microsoft Active Directory Services provided by .NET Framework.

However I still get the error "You need to provide the correct current password." when I try to change a password when it is expired.

Did I miss something?

Thank you,
Luca

**Comment by geoperez** [comment]
> But I noticed that using a Service Account for PassCore, the end-user is always able to change its password despite Default Domain Policy (e.g. it can change password before Minimum password age, set to 3).

This is correct because you are forcing a reset password when you add an account. So the entire scope of what can/cannot do a user is lost. You can check in the [source code](https://github.com/unosquare/passcore/blob/master/src/Unosquare.PassCore.PasswordProvider/PasswordChangeProvider.cs#L232) how the method `ChangePassword` is used and if it fails then will try `SetPassword`.

I think I need to clarify this scenario in the documentation. Or maybe include an option to ignore the `SetPassword` method...

**Comment by lucafabbri365** [comment]
Hello @geoperez,
so using a Service Account doesn't help us to accomplish the objective.
Can PassCore be used by end-users (those that don't use a company computer) to change their password when expired or flag "must change password at next logon" is selected according to **Default Domain Policy** settings (without bypassing them) ? The same that any user can be perform from a Windows client ?

Thank you very much for your answer.

Luca

**Comment by lucafabbri365** [comment]
Hello,
please, can you confirm (or not): currently, there's no way to let end-user reset its password when expired or flag "must change password at next logon" is selected without using a Service Account with change/reset password and r/w pwdLastSet permissions?

Thank you,
Luca

**Comment by geoperez** [comment]
Sorry for the delay, let me clarify the issue.

- Without a Service Account, a user is NOT able to set pwdLastSet value. So they may fail to reset an expired password.
- WIth a Service Account, a user MIGHT be able to change a password if the Service Account has the permissions to reset the pwdLastSet value.

**Comment by lucafabbri365** [comment]
Hello @geoperez,
now I have a clear situation, thank you.

Just a question: isn't there the possibility to have PassCore working like a "Windows client"; where the end user has the possibility to change its password when expired or flag "must change password at next logon" selected but being subjected by Default Domain Policy ?

Thank you again,
Luca

**Comment by geoperez** [comment]
Thanks for the bug hunting. I need to review it.

**Comment by geoperez** [comment]
I need to publish a new version!

**Comment by geoperez** [comment]
A new PR was merged. Tomorrow will be released the version.

**Comment by lucafabbri365** [comment]
Hello,
this issue has been resolved. 

Thank you,
Luca
