### ISSUE TITLE
Error Information: Logon failure: unknown user name or bad password.

### ISSUE THREAD

**Issue by MeanKty** [unosquare/passcore#36]
When I try to change a password, I get an error:

" There was an error changing your password
Error Information: Logon failure: unknown user name or bad password."

I've tried changing the server in the appsettings.json to the DC and it does the same thing.  Any suggestions?  I've already checked our firewall and the traffic is getting to the DC fine.

**Comment by roaima** [comment]
Are you trying with a UPN or an unadorned username? You should be using a UPN (`someuser@contoso.com`).

**Comment by MeanKty** [comment]
That would be why.  Thanks.
