### ISSUE TITLE
Error on building docker image

### ISSUE THREAD

**Issue by nikinname** [unosquare/passcore#363]
**PassCore Server**
- OS: Docker on Linux
- Docker version 19.03.1, build 74b1e89

**Describe the bug**
Error on
docker build --rm -t passcore .

After correct download of dotnet I obtain this output error

Unosquare.PassCore.Web -> /app/src/Unosquare.PassCore.Web/bin/Release/netcoreapp2.2/Unosquare.PassCore.Web.dll
  Performing run Parcel build...

  > passcore@1.0.0 build /app/src/Unosquare.PassCore.Web/ClientApp
  > parcel build index.html -d ../wwwroot --no-source-maps

  sh: parcel: not found
  npm ERR! file sh
  npm ERR! code ELIFECYCLE
  npm ERR! errno ENOENT
  npm ERR! syscall spawn
  npm ERR! passcore@1.0.0 build: `parcel build index.html -d ../wwwroot --no-source-maps`
  npm ERR! spawn ENOENT
  npm ERR!
  npm ERR! Failed at the passcore@1.0.0 build script.
  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
  npm WARN Local package.json exists, but node_modules missing, did you mean to install?

  npm ERR! A complete log of this run can be found in:
  npm ERR!     /root/.npm/_logs/2019-10-04T10_21_15_401Z-debug.log
/app/src/Unosquare.PassCore.Web/Unosquare.PassCore.Web.csproj(77,5): error MSB3073: The command "npm run build" exited with code 1.
The command '/bin/sh -c dotnet publish -c Release -o /app/out /p:PASSCORE_PROVIDER=LDAP' returned a non-zero code: 1

**Comment by geoperez** [comment]
The npm package is not installed. Let me review the docker file.

**Comment by nikinname** [comment]
Thank you, I can try to fix it.
My problem is that I found that npm must be installed as non root user and the dockerfile assumes that is run by root

**Comment by Techcadia** [comment]
Hey I am the one that merged the Dockerfile. Sorry about not seeing this earlier. I assume we can moved up to node 10 without any issues.

Also are we still on 2.1 or 3.0 for builds @geoperez. I can create a PR with the updated Dockerfile this week.

**Comment by geoperez** [comment]
Welcome back @Techcadia, we upgraded to ASP.NET Core 3.0.

**Comment by JonathonReinhart** [comment]
I just opened issue #392 which may be related to this.

**Comment by geoperez** [comment]
Your ticket is related to the version of .NET Core. We need to upgrade the docker file to use version 3.

**Comment by Techcadia** [comment]
Resolved with https://github.com/unosquare/passcore/pull/393
