### ISSUE TITLE
Loading site hangs 

### ISSUE THREAD

**Issue by moosamus** [unosquare/passcore#37]
I have tested on Server 2008 R2 (IIS 7.5, .NET 4.5.2) and 2012 (IIS 8.5, .NET 4.5.2). dnvm version 1.0.0-rc1-update2, all packages installed to location specified in docs. Also, Windows Firewall is disabled, and I'm running under a privileged user for testing.

Loading the site hangs until timeout. Logs and failed request traces do not show anything of note ( to my eyes). I can load the app by running the startup script (%passcore-root%\approot\web), which allows me to connect on localhost:5000 and shows incoming requests in the shell. 

It seems that httpplatformhandler (v1.2) is not correctly proxying requests to the application.

**Comment by mariodivece** [comment]
Please try with the latest version and let us know if this is still a problem. Reopen the issue if necessary.
