### ISSUE TITLE
PassCore Debug

### ISSUE THREAD

**Issue by lucafabbri365** [unosquare/passcore#371]
Hello,
I'd like to look inside PassCore code, just for my personal knowledge, but I encountered some problems while debugging it. I'm not programming expertise, but I'm an IT, so if you can give me just a few recommendations it would be great. 
Please, tell me if it is the wrong place to ask.

**Describe the bug**
Basically I have to problems while debugging PassCore code:

1. Warning "_The breakpoint will not currently be hit. No symbols have been loaded for this document_" for any breakpoint set in dependency project (_e.g. Unosquare.PassCore.Common => PasswordChangeProvider.cs_)
2. While testing it, any username/password is accepted (message: "_You have changed your password successfully._") even if it doesn't exist or it's wrong. 

**Desktop:**
 - OS: Windows 10 1903
 - Browser: Chrome
 - Development Environment: VS 2019 (16.3.4), .NET Core SDK 3.0.100, Node.js 10.16.3 LTS, parcel-bundler 1.12.4 (npm install -g parcel-bundler).

Thank you very much,
Luca

**Comment by geoperez** [comment]
Hi, 

Let me explain each issue:

1 - If you are not able to set a breakpoint you may need to check if you are running in Debug. If it is not the case, you can check at Google for similar issues with VS (https://developercommunity.visualstudio.com/content/problem/97445/vs2017-the-breakpoint-will-not-currently-be-hit-no.html)
2 - Passcore has three possible builds, based on build settings. Each one will use a different PasswordChange Provider:
- Release Windows - Provider using Microsoft Directory Services
- Release Linux/Mac - Provider using Novell LDAP.
- Debug - Provider using mock data.
You might be using Debug provider and that is why you are getting this behaviour (and also issue 1)

If you want to switch to Release Provider using the debugger. You can edit the Startup.cs file in Web project (https://github.com/unosquare/passcore/blob/master/src/Unosquare.PassCore.Web/Startup.cs) and modify the lines:

`#if DEBUG`

to 

`#if !DEBUG`

This will adjust the source code to compile against the right provider.

**Comment by lucafabbri365** [comment]
Hello @geoperez,
thank you very much for clear explanation.
It worked: I missed the #if DEBUG part.

Thank you again guy.
Luca

**Comment by lucafabbri365** [comment]
Hello @geoperez,
thank you very much for clear explanation.
It worked: I missed the #if DEBUG part.

Thank you again guy.
Luca
