### ISSUE TITLE
Multiple domains support

### ISSUE THREAD

**Issue by lucafabbri365** [unosquare/passcore#379]
Hello,
I'd like to know if PassCore supports multiple domains (=without configuring multiple/separate websites with different _appsettings.json_).
I read some posts here (#223, #219, #30 or #188) and looking inside the code I can suppose it isn't possible, at least using AD Provider; what about using LDAP Provider?
If not supported, then...

Assuming this AD environment:

- 1 forest and tree root: **domain.local**
- Child domains: **child[1...n].domain.local**
- Tree root (in same forest): **domain01.local** 
- UPNs suffixes: **@domain.com**, @domain.local, @child[1...n].domain.local, @domain01.local

...should I create different websites/_appsettings.json_ with **DefaultDomain** parameter set?

_Example_

_Website 1 / appsettings.json - DefaultDomain: domain.local_
_Website 2 / appsettings.json - DefaultDomain: child1.domain.local_
_Website 3 / appsettings.json - DefaultDomain: child2.domain.local_
_..._

(?!?)

I can image it means changing some code, but did you plan to support multiple domains with AD Provider, into only one PassCore "installation"?

Thank you,
Luca

**Comment by geoperez** [comment]
Hi Luca, 

We've been researching this issue, but there are no plans to include right now. The only option is to have an instance for each domain.

**Comment by lucafabbri365** [comment]
Hello @geoperez,
what do you mean with "_instance for each domain_" ? Should PassCore be installed in a server joined to the same domain where are defined users that will use it (if I intend to use AD Provider and Automatic Context) ? Or it doesn't matter ? 
I have one server joined to parent domain and as PassCore websites as our domains (1 for parent domain and another for child domain); each website has a different configuration file, but it doesn't work: "_The User principal doesn't exist_". 
By debugging the code, I found something strange, that I'd like to understand. Below the analysis.

Assuming:

- Domain: **child.domain.local**
- PassCore Server: **SERVER** (joined to parent domain **domain.local**)
- Domain Controller: **DC.child.domain.local**
- UPNs: **@domain.com, @child.domain.local, @domain.local**

**appsettings.json**

1. _UseAutomaticContext = true_
2. _LdapHostnames = DC.child.domain.local_
2. _DefaultDomain = child.domain.local_

**Domain Password Information**

When PassCore starts, acquires domain password information (_GetDomainPasswordInformation()_):

```
using (var server = new SamServer())
            {
                foreach (var domain in server.EnumerateDomains())
                {
                    if (domain == "Builtin") continue;
                    if (!string.IsNullOrEmpty(_options.DefaultDomain) && !_options.DefaultDomain.Contains(domain)) continue;

                    var sid = server.GetDomainSid(domain);
                    return server.GetDomainPasswordInformation(sid);
                }
            }
```
The _domain_ variable assumes **Builtin** and **SERVER** values; when equal to **Builtin**, it continues with next value:

`if (domain == "Builtin") continue;`

When equal to something else (**SERVER** - it is PassCore server name) it is "compared" with _DefaultDomain_ parameter value:

`if (!string.IsNullOrEmpty(_options.DefaultDomain) && !_options.DefaultDomain.Contains(domain)) continue;`

1. If there is the match (_DefaultDomain_ contains _domain_) it goes one step over by retrieving domain password info:

```
var sid = server.GetDomainSid(domain);
return server.GetDomainPasswordInformation(sid);
```

2. If there is no match, it continues with next _domain_ value; here the strangeness (why this check ?!?):

_DefaultDomain = child.domain.local_ doesn't contain _domain = SERVER_ so the loop ends (because the last value) and no domain password info is retrieved. 

**Note:** If _DefaultDomain_ parameter isn't specified, then it retrieves, correctly, domain password info from the PassCore server's domain (_domain.local_).

**Password Change**

When "Change Password" button is pressed:

1. It cheks new password length with min domain password length, that is empty, and goes one step over
2. It acquires the **PrincipalContext**: automatic context is in use (_UseAutomaticContext=true_) and it returns the same PassCore server's domain (_domain.local_), but it's wrong (I expect to be _child.domain.local_)

```
if (_options.UseAutomaticContext)
            {
                _logger.LogWarning("Using AutomaticContext");
                return new PrincipalContext(ContextType.Domain);
            }
```

3. It searches for the UPN in a wrong context so the error "_The User principal doesn't exist_" appears.

What about ?

**Comment by geoperez** [comment]
For instance, I mean a Passcore WebApp running with settings for one domain. So multiple webapps running for multiple domains.

Let me take a deep look at your analysis and I come back to you later. Thanks btw for your help to improve this tool.

**Comment by lucafabbri365** [comment]
Hello @geoperez,
I like to help you because, to be honest, I need it (because free :-)) and I really believe in this tool.

Thank you,
Luca

**Comment by geoperez** [comment]
So for the first part, you suggest using the last found domain (except "Builtin") And avoid the unnecessary check of default domain?

@Serk352  can you check this?

**Comment by lucafabbri365** [comment]
Hello @geoperez,
regarding the first part (DOMAIN PASSWORD INFORMATION): I supposed the _DefaultDomain_ parameter inside **appsettings.json** could covers those cases where PassCore is installed in a server joined to one domain (example _domain.local_), but intended to be used for another domain (example _child.domain.local_).

Looking at the code, the function who retrieves domain password information:
1. Enumerates domains: it returns _Builtin_ and the _\<hostname\>_ where PassCore is installed
2. Get domain SID by passing PassCore server's _\<hostname\>_ - `var sid = server.GetDomainSid(domain);`
3. Get password information from SID - `return server.GetDomainPasswordInformation(sid);`

If present, it also compares _DefaultDomain_ parameter with enumerated domain _\<hostname\>_ - `...!_options.DefaultDomain.Contains(domain)...`, between **steps 1 and 2**. 

I don't understand why an hostname (example _SERVER01_) can be compared with domain name (_DefaultDomain_ - example _child.domain.local_) ?

The objective is to retrieve domain password information from _DefaultDomain_.

**Comment by geoperez** [comment]
I think this bad design is because of how our AD is working.

We have our domain 'unosquare.com' and the hostname is 'ad.unosquare.com'. So our logic was, the hostname SHOULD contain the domain in the very end.

I'll review this code and fixed it.

**Comment by lucafabbri365** [comment]
Hello @geoperez,
I try to explain with this example:

- PassCore server's hostname (joined to _domain.local_): **SERVER01** (It is my machine's name from where I'm debugging the code)
- **DefaultDomain** in appsettings.json = _child.domain.local_

**PROCESS**

1. `server.EnumerateDomains()` returns: **Builtin** and **SERVER01** (not _domain.local_)
2. When `domain` = **Builtin**, it continues with next `domain` value in the loop (`if (domain == "Builtin") continue;`)
3. When `domain` = **SERVER01**, it evaluates and matches the `if (!string.IsNullOrEmpty(_options.DefaultDomain) && !domain.Contains(_options.DefaultDomain)) continue;` because **SERVER01** doesn't contain _child.domain.local_; then it continues with next `domain` value in the loop, but SERVER01 is the last loop value, then no domain password information was retrieved.

Does it sound good for you now ?

Thank you,
Luca

**Comment by geoperez** [comment]
Ok, I removed the check. I double-checked the response of `server.EnumerateDomains()` you are right, it returns the hostname.

**Comment by lucafabbri365** [comment]
Hello @geoperez,
I noticed you removed the check, however it isn't enough: domain password information should be retrieved from domain specified in **DefaultDomain** parameter, if any; if not, then treat it like now.

What about ?

**Comment by geoperez** [comment]
Yeah, I need to figure out how to use SAM to request this information for a particular domain.

I was checking something like this: https://stackoverflow.com/questions/7726093/are-there-better-easier-ways-to-get-a-specific-domains-sid

So there will be two steps, check the DefaultDomain and if exists and we can query the SID, request the info. Otherwise, get info from the first domain from EnumerateDomains.

**Comment by lucafabbri365** [comment]
> Yeah, I need to figure out how to use SAM to request this information for a particular domain.
> 
> I was checking something like this: https://stackoverflow.com/questions/7726093/are-there-better-easier-ways-to-get-a-specific-domains-sid
> 
> So there will be two steps, check the DefaultDomain and if exists and we can query the SID, request the info. Otherwise, get info from the first domain from EnumerateDomains.

Yes, that's sounds good to me. At the same time, please, take care of the **PrincipalContext** where to search the UPN (while resetting password): it should "point" to right domain too.

Thank you very much,
Luca

**Comment by geoperez** [comment]
Well, that is another issue. To retrieve a PrincipalContext from a child domain, you may need to set a Global Catalog. The DefaultDomain is not enough.

**Comment by lucafabbri365** [comment]
> Well, that is another issue. To retrieve a PrincipalContext from a child domain, you may need to set a Global Catalog. The DefaultDomain is not enough.

Mmm, not all domain(s) info and passwords are replicated in GC: then, will all PassCore check work (example: `ValidateGroups(...)`, `ValidateUserCredentials(...)`, etc.) ?

What about using **LdapHostnames** parameter in appsettings.json, if any, to force the DC for PrincipalContext ? Something like:

`return new PrincipalContext(ContextType.Domain, LdapHostnames[i]);`

Bye,
Luca

**Comment by geoperez** [comment]
My idea to use PrincipalContext and then SAM Server is failing.

Probably, I will change the SAM Server code to query directly to the Password Object in AD, like this: https://stackoverflow.com/a/38491829

**Comment by lucafabbri365** [comment]
Hello @geoperez,
it could be a good idea. So in that case how appsettings.json will be managed (just for my curiosity) ?
Will you refer to _DefaultDomain_ and _LdapHostnames_ parameters ? If they weren't specified, then you will consider current PassCore server's domain ?

Bye,
Luca

**Comment by geoperez** [comment]
Yeah, the idea is to keep the same parameters for the additional domain. Anyway, I've been kinda busy, so I might take a while to start working on this. If you get a chance, don't hesitate to start a branch.
