### ISSUE TITLE
False error: The system cannot contact a domain controller to service the authentication request

### ISSUE THREAD

**Issue by roaima** [unosquare/passcore#38]
I'm using [PassCore 2.0.2.Beta.2](https://github.com/unosquare/passcore/releases/download/v2.0.2.beta.2/passcore-2.0.2.beta.2-2016-03-14.zip) in a domain environment. I have a default configuration where `UseAutomaticContext = true`.

I'm seeing an error message displayed "_Error Information: The system cannot contact a domain controller to service the authentication request. Please try again later. (Exception from HRESULT: 0x800704F1)_" when trying to change a password but falling foul of GPO enforced password requirements.

When "following the password rules" I can change my password. However, I get this message when trying to set a password that's too short, or that doesn't have a sufficient number of different character groups, or that is contained within the password history.

Looking around, it seems that that this may be Known Issue 2 at https://support.microsoft.com/en-us/kb/3177108 but there is no obvious solution offered by Microsoft in that article.

Any thoughts please?

<sub>Lastly, I really appreciate you putting in the work to deliver this updated version of PassCore (we've been using your previous one for a year or so). Thank you.</sub>

**Comment by alexwhitman** [comment]
We're also seeing the same error when the current password entered doesn't match the current password for the account.

**Comment by tedbass** [comment]
https://github.com/unosquare/passcore/issues/34

**Comment by roaima** [comment]
Uninstalling the two MS patches is not viable moving onwards, "_All future security and non-security updates for [...] Windows Server 2012 R2 require update 2919355 to be installed_".

**Comment by tedbass** [comment]
I agree.  Just letting you know what I found.  Also, neither of the two updates I un-installed were the 2919355 update you mentioned.  But I agree best practice would be to find a way to work WITH the updates rather than never install them.

**Comment by roaima** [comment]
As of September 21, the latest on the [MS KB article](https://support.microsoft.com/en-us/kb/3177108) I referenced earlier is as follows:

> The root cause of this issue is understood. We plan to release a fix that resolves this issue in October 2016. This release date is subject to change. This article will be updated with additional details as they become available.

**Comment by roaima** [comment]
As of the latest round of patches to Windows Server 2012 R2 this has now been resolved on my systems and I'm going to close the ticket.
