### ISSUE TITLE
Changing IdTypeForUser 

### ISSUE THREAD

**Issue by jameelboonzaaier** [unosquare/passcore#385]
**PassCore Server**
- OS: [Windows ]
- Provider: [Active Directory]
- Settings file (without sensitive information): 

**Describe the bug**
Im trying to change the IdTypeForUser to DN but getting a error cannot find users. Reason for the change we use gmail in our organisation and the sync tool for gmail that runs on AD looks at DN when changes is made for a user.

Is there anyway i can get help changing this in appsettings file 
<img width="433" alt="Screenshot 2019-10-21 at 11 53 48" src="https://user-images.githubusercontent.com/19990542/67197729-ba563c80-f3fd-11e9-95cf-593a49511592.png">

**Comment by jameel-boonzaaier** [comment]
Hi is there any response to the issue i raised ?

**Comment by geoperez** [comment]
Not yet, we've been kinda busy.

**Comment by jameel-boonzaaier** [comment]
Hi Guys

Really need some help with this

**Comment by geoperez** [comment]
Can you post a log file?

**Comment by jameel-boonzaaier** [comment]
Hi

Can you please tell me what request is being send to the DC when the password request is put through via the passcore tool

**Comment by geoperez** [comment]
Passcore will use ChangePassword (https://github.com/unosquare/passcore/blob/master/src/Unosquare.PassCore.PasswordProvider/PasswordChangeProvider.cs#L228)

If this fails, I might try SetPassword (https://github.com/unosquare/passcore/blob/master/src/Unosquare.PassCore.PasswordProvider/PasswordChangeProvider.cs#L240).

More information:
https://docs.microsoft.com/en-us/windows/win32/api/iads/nf-iads-iadsuser-changepassword
https://docs.microsoft.com/en-us/windows/win32/api/iads/nf-iads-iadsuser-setpassword

**Comment by jameel-boonzaaier** [comment]
I think i found my problem but i am now trying to find this file called PasswordController.cs but i dont manage to see this file in the passcore folder

**Comment by geoperez** [comment]
It's because the source code is compiled into an assembly (a DLL file). What do you need to edit?

**Comment by jameel-boonzaaier** [comment]
Username instead of email #103

**Comment by geoperez** [comment]
Can you explain?

**Comment by jameel-boonzaaier** [comment]
I want to use a username when changing a password instead of email address.

**Comment by geoperez** [comment]
If you don't want to use the UPN (email alike format) you can change the setting `IdTypeForUser` to `SamAccountName`.

**Comment by jameel-boonzaaier** [comment]
Hi

When i change it to SAM i still get the below when i enter the username eg:
name.domain

<img width="574" alt="Screenshot 2019-11-11 at 16 44 31" src="https://user-images.githubusercontent.com/19990542/68595798-d8fe9f00-04a2-11ea-9ccf-492ba0407e95.png">
![Uploading Screenshot 2019-11-11 at 16.44.40.png…]()

**Comment by jameel-boonzaaier** [comment]
![Screenshot 2019-11-11 at 16 44 40](https://user-images.githubusercontent.com/19990542/68595838-e9af1500-04a2-11ea-8601-5881603f1a95.png)

**Comment by geoperez** [comment]
Try to change the setting `UseEmail` to false please.

**Comment by jameel-boonzaaier** [comment]
It works with that but now the password change successfully however it does not change the email password as email and ad uses the same password.

We use gmail for emails.

**Comment by jameel-boonzaaier** [comment]
Gmail uses a tool called Gsuite password sync that runs on every dc to look for password chagnes and this is what is looks for.

![Screenshot 2019-11-12 at 09 36 20](https://user-images.githubusercontent.com/19990542/68651412-06ddf500-0530-11ea-863f-476d6d815b32.png)

**Comment by jameel-boonzaaier** [comment]
Gmail has a password sync tool called G suite password sync that runs on every DC and this is how its confugured

![Screenshot 2019-11-12 at 09 36 20](https://user-images.githubusercontent.com/19990542/68651560-515f7180-0530-11ea-970f-dd7025c6d9e8.png)
