### ISSUE TITLE
Expand-Archive

### ISSUE THREAD

**Issue by TaamirH** [unosquare/passcore#386]
**PassCore Server**
- OS: Windows 
- Provider: Active Directory
- Settings file (without sensitive information): 

**Describe the bug**
I tried to run the script , and thats what happend:
**PS C:\Windows\system32> Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/unosquare/passcore/master/Installer.ps1'))
Installing Passcore
Creating Directory

Determining latest release
Downloading passcore.zip
Unzipping
Expand-Archive : The term 'Expand-Archive' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the 
name, or if a path was included, verify that the path is correct and try again.
At line:28 char:1
+ Expand-Archive $zipPath -dest $directory -force
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Expand-Archive:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException**
 

**Expected behavior**
the script to install

**Desktop (please complete the following information):**
 - OS:  windows server 2012 r2

**Comment by geoperez** [comment]
What version of PowerShell are you using?

**Comment by TaamirH** [comment]
Hey . im using JS

‫בתאריך יום ו׳, 25 באוק׳ 2019 ב-20:33 מאת ‪Geovanni Perez‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by geoperez** [comment]
JS? This script is for PowerShell 5.1 or better. You can check the MSDN documentation here: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/expand-archive?view=powershell-5.1
