### ISSUE TITLE
found multiple with same username

### ISSUE THREAD

**Issue by nikinname** [unosquare/passcore#397]
- OS: Docker Linux
- Provider: LDAP
- Settings file:

docker run  \
-e WebSettings__EnableHttpsRedirect='false'  \
-e AppSettings__UseAutomaticContext='false' \
-e AppSettings__LdapSearchBase='DC=xxx,DC=xxx' \
-e AppSettings__LdapHostnames__0='mypdc.xxx.xxx' \
-e AppSettings__DefaultDomain='xxx.xxx' \
-e AppSettings__IdTypeForUser='SAM' \
-e AppSettings__LdapPort='389' \
-e AppSettings__LdapUsername='DN of the ldap admin user' \
-e AppSettings__LdapPassword='password of the ldap user' \
-e ClientSettings__UseEmail='false' \
-it \
-p 80:80 passcore:latest 

**Describe the bug**
the user is never found. I use the samAccountName in the form.
in log I find:

**found multiple with same username:** [vittoriam]
but the user with samAccountName vittoriam is clearly unique

the log is the following:

`Hosting environment: Production
,Content root path: /app
,Now listening on: http://[::]:80
,Application started. Press Ctrl+C to shut down.
,info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
,      Request starting HTTP/1.1 GET http://dockerdmz-test.sit.local/api/password  
,info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
,      Executing endpoint 'Unosquare.PassCore.Web.Controllers.PasswordController.Get (Unosquare.PassCore.Web)'
,info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
,      Route matched with {action = "Get", controller = "Password"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Get() on controller Unosquare.PassCore.Web.Controllers.PasswordController (Unosquare.PassCore.Web).
,warn: Zyborg.PassCore.PasswordProvider.LDAP.LdapPasswordChangeProvider[0]
,      option [LdapIgnoreTlsErrors] is ENABLED; invalid certificates will be allowed
,warn: Zyborg.PassCore.PasswordProvider.LDAP.LdapPasswordChangeProvider[0]
,      option [LdapStartTls] is DISABLED in combination with non-standard TLS port [389]
,info: Microsoft.AspNetCore.Mvc.Infrastructure.SystemTextJsonResultExecutor[1]
,      Executing JsonResult, writing value of type 'Unosquare.PassCore.Web.Models.ClientSettings'.
,info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
,      Executed action Unosquare.PassCore.Web.Controllers.PasswordController.Get (Unosquare.PassCore.Web) in 70.8579ms
,info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
,      Executed endpoint 'Unosquare.PassCore.Web.Controllers.PasswordController.Get (Unosquare.PassCore.Web)'
,info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
,      Request finished in 187.34650000000002ms 200 application/json; charset=utf-8
,info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
,      Request starting HTTP/1.1 POST http://dockerdmz-test.sit.local/api/password application/json 127
,info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
,      Executing endpoint 'Unosquare.PassCore.Web.Controllers.PasswordController.Post (Unosquare.PassCore.Web)'
,info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
,      Route matched with {action = "Post", controller = "Password"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Post(Unosquare.PassCore.Web.Models.ChangePasswordModel) on controller Unosquare.PassCore.Web.Controllers.PasswordController (Unosquare.PassCore.Web).
,warn: Zyborg.PassCore.PasswordProvider.LDAP.LdapPasswordChangeProvider[0]
,      found multiple with same username: [vittoriam]
,info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
,      Executing ObjectResult, writing value of type 'Unosquare.PassCore.Web.Models.ApiResult'.
,info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
,      Executed action Unosquare.PassCore.Web.Controllers.PasswordController.Post (Unosquare.PassCore.Web) in 251.6901ms
,info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
,      Executed endpoint 'Unosquare.PassCore.Web.Controllers.PasswordController.Post (Unosquare.PassCore.Web)'
,info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
,      Request finished in 286.1524ms 400 application/json; charset=utf-8
,`

**Comment by geoperez** [comment]
Can you retest against the master branch?

**Comment by nikinname** [comment]
I updated to the master branch

Fast-forward
 .github/ISSUE_TEMPLATE/Bug_report.md               |   1 +
 .../Unosquare.PassCore.Common.csproj               |   2 +-
 .../Unosquare.PassCore.PasswordProvider.csproj     |   2 +-
 .../ClientApp/Components/ChangePasswordForm.tsx    |   2 +-
 .../ClientApp/package-lock.json                    | 104 ++++++++++----------
 src/Unosquare.PassCore.Web/ClientApp/package.json  |   8 +-
 .../Unosquare.PassCore.Web.csproj                  |   2 +-
 .../LdapPasswordChangeProvider.cs                  | 106 ++++++++++-----------
 .../Zyborg.PassCore.PasswordProvider.LDAP.csproj   |   2 +-
 9 files changed, 110 insertions(+), 119 deletions(-)

But the problem remains.

**Comment by geoperez** [comment]
Can you post the log?

**Comment by nikinname** [comment]
Yes,
I repeat the command I used to run docker:

docker run  -e WebSettings__EnableHttpsRedirect='false'  -e AppSettings__UseAutomaticContext='false' -e AppSettings__LdapSearchBase='DC=sit,DC=local' -e AppSettings__LdapHostnames__0='mypdcfqdn' -e AppSettings__DefaultDomain='MYDOMAIN' -e AppSettings__IdTypeForUser='SAM' -e AppSettings__LdapPort='389' -e AppSettings__LdapUsername='DN of an admin user' -e AppSettings__LdapPassword='somepassword' -e ClientSettings__ChangePasswordForm__UsernameLabel='Inserire il proprio nome utente' -e ClientSettings__UseEmail='false' -it -p 80:80 passcore:latest

Of corse I changed sensible info

This it the log trying wit an user that has samAccountName = vittoriam

Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://dockerdmz-test.sit.local/  
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /index.html was not modified
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 30.558ms 304 text/html
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://dockerdmz-test.sit.local/App.54a8830a.js  
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /App.54a8830a.js was not modified
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 1.0391000000000001ms 304 application/javascript
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://dockerdmz-test.sit.local/react.fc4dbac6.js  
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/react.fc4dbac6.js'. Physical path: '/app/wwwroot/react.fc4dbac6.js'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 20.9018ms 200 application/javascript
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://dockerdmz-test.sit.local/react-dom.66c8cbbe.js  
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://dockerdmz-test.sit.local/main.21408868.js  
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /main.21408868.js was not modified
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 0.6124ms 304 application/javascript
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/react-dom.66c8cbbe.js'. Physical path: '/app/wwwroot/react-dom.66c8cbbe.js'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 95.8014ms 200 application/javascript
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://dockerdmz-test.sit.local/favicon.ico  
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 41.6544ms 0 
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://dockerdmz-test.sit.local/api/password  
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Unosquare.PassCore.Web.Controllers.PasswordController.Get (Unosquare.PassCore.Web)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "Get", controller = "Password"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult Get() on controller Unosquare.PassCore.Web.Controllers.PasswordController (Unosquare.PassCore.Web).
warn: Zyborg.PassCore.PasswordProvider.LDAP.LdapPasswordChangeProvider[0]
      option [LdapIgnoreTlsErrors] is ENABLED; invalid certificates will be allowed
warn: Zyborg.PassCore.PasswordProvider.LDAP.LdapPasswordChangeProvider[0]
      option [LdapStartTls] is DISABLED in combination with non-standard TLS port [389]
info: Microsoft.AspNetCore.Mvc.Infrastructure.SystemTextJsonResultExecutor[1]
      Executing JsonResult, writing value of type 'Unosquare.PassCore.Web.Models.ClientSettings'.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action Unosquare.PassCore.Web.Controllers.PasswordController.Get (Unosquare.PassCore.Web) in 65.2153ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Unosquare.PassCore.Web.Controllers.PasswordController.Get (Unosquare.PassCore.Web)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 134.592ms 200 application/json; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://dockerdmz-test.sit.local/passcore-logo.265a699e.png  
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/passcore-logo.265a699e.png'. Physical path: '/app/wwwroot/passcore-logo.265a699e.png'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 7.0502ms 200 image/png
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://dockerdmz-test.sit.local/osi.38a8cb73.png  
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/osi.38a8cb73.png'. Physical path: '/app/wwwroot/osi.38a8cb73.png'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 3.5129ms 200 image/png
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://dockerdmz-test.sit.local/License_icon-mit.svg.fd4b276c.png  
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/License_icon-mit.svg.fd4b276c.png'. Physical path: '/app/wwwroot/License_icon-mit.svg.fd4b276c.png'
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://dockerdmz-test.sit.local/logo.c481326b.png  
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 4.2596ms 200 image/png
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/logo.c481326b.png'. Physical path: '/app/wwwroot/logo.c481326b.png'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 2.3969ms 200 image/png
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://dockerdmz-test.sit.local/api/password application/json 127
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Unosquare.PassCore.Web.Controllers.PasswordController.Post (Unosquare.PassCore.Web)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "Post", controller = "Password"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Post(Unosquare.PassCore.Web.Models.ChangePasswordModel) on controller Unosquare.PassCore.Web.Controllers.PasswordController (Unosquare.PassCore.Web).
warn: Zyborg.PassCore.PasswordProvider.LDAP.LdapPasswordChangeProvider[0]
      found multiple with same username: [vittoriam]
info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
      Executing ObjectResult, writing value of type 'Unosquare.PassCore.Web.Models.ApiResult'.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action Unosquare.PassCore.Web.Controllers.PasswordController.Post (Unosquare.PassCore.Web) in 215.834ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Unosquare.PassCore.Web.Controllers.PasswordController.Post (Unosquare.PassCore.Web)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 249.71470000000002ms 400 application/json; charset=utf-8

**Comment by nikinname** [comment]
could anyone help?

**Comment by Techcadia** [comment]
```warn: Zyborg.PassCore.PasswordProvider.LDAP.LdapPasswordChangeProvider[0]
found multiple with same username: [vittoriam]```

This means that you have multiple usernames in your active directory that contain the same SamAccountName. Either limit your `LdapSearchBase` or Fix the duplicate user.

**Comment by nikinname** [comment]
Of course there is only one! I have checked

```
PS C:\WINDOWS\system32> Get-ADUser -Filter 'samaccountname -eq "vittoriam"' | select samaccountname

samaccountname
--------------
vittoriam
```
The error is somewere else

**Comment by Techcadia** [comment]
@nikinname Can you run the same command with the current master branch and provide logs.

Thanks

**Comment by nikinname** [comment]
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://dockerdmz-test.sit.local/
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /index.html was not modified
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 27.201500000000003ms 304 text/html
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://dockerdmz-test.sit.local/App.54a8830a                                                                                                                                                             .js
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /App.54a8830a.js was not modified
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 1.5186000000000002ms 304 application/javascript
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://dockerdmz-test.sit.local/react.fc4dba                                                                                                                                                             c6.js
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://dockerdmz-test.sit.local/react-dom.66                                                                                                                                                             c8cbbe.js
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/react.fc4dbac6.js'. Physical path: '/app/www                                                                                                                                                             root/react.fc4dbac6.js'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 13.916400000000001ms 200 application/javascript
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/react-dom.66c8cbbe.js'. Physical path: '/app                                                                                                                                                             /wwwroot/react-dom.66c8cbbe.js'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 14.638300000000001ms 200 application/javascript
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://dockerdmz-test.sit.local/main.2140886                                                                                                                                                             8.js
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[6]
      The file /main.21408868.js was not modified
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 0.3779ms 304 application/javascript
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://dockerdmz-test.sit.local/favicon.ico                                                                                                                                                              
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 42.042ms 0
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://dockerdmz-test.sit.local/api/password                                                                                                                                                             
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Unosquare.PassCore.Web.Controllers.PasswordController.                                                                                                                                                             Get (Unosquare.PassCore.Web)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "Get", controller = "Password"}. Executing co                                                                                                                                                             ntroller action with signature Microsoft.AspNetCore.Mvc.IActionResult Get() on c                                                                                                                                                             ontroller Unosquare.PassCore.Web.Controllers.PasswordController (Unosquare.PassC                                                                                                                                                             ore.Web).
warn: Zyborg.PassCore.PasswordProvider.LDAP.LdapPasswordChangeProvider[0]
      option [LdapIgnoreTlsErrors] is ENABLED; invalid certificates will be allo                                                                                                                                                             wed
warn: Zyborg.PassCore.PasswordProvider.LDAP.LdapPasswordChangeProvider[0]
      option [LdapStartTls] is DISABLED in combination with non-standard TLS por                                                                                                                                                             t [389]
info: Microsoft.AspNetCore.Mvc.Infrastructure.SystemTextJsonResultExecutor[1]
      Executing JsonResult, writing value of type 'Unosquare.PassCore.Web.Models                                                                                                                                                             .ClientSettings'.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action Unosquare.PassCore.Web.Controllers.PasswordController.Get                                                                                                                                                              (Unosquare.PassCore.Web) in 74.06230000000001ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Unosquare.PassCore.Web.Controllers.PasswordController.G                                                                                                                                                             et (Unosquare.PassCore.Web)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 146.5329ms 200 application/json; charset=utf-8
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://dockerdmz-test.sit.local/passcore-log                                                                                                                                                             o.265a699e.png
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/passcore-logo.265a699e.png'. Physical path:                                                                                                                                                              '/app/wwwroot/passcore-logo.265a699e.png'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 1.3931ms 200 image/png
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://dockerdmz-test.sit.local/osi.38a8cb73                                                                                                                                                             .png
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://dockerdmz-test.sit.local/License_icon                                                                                                                                                             -mit.svg.fd4b276c.png
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/osi.38a8cb73.png'. Physical path: '/app/wwwr                                                                                                                                                             oot/osi.38a8cb73.png'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 0.8613000000000001ms 200 image/png
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/License_icon-mit.svg.fd4b276c.png'. Physical                                                                                                                                                              path: '/app/wwwroot/License_icon-mit.svg.fd4b276c.png'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 1.0443ms 200 image/png
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://dockerdmz-test.sit.local/logo.c481326                                                                                                                                                             b.png
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/logo.c481326b.png'. Physical path: '/app/www                                                                                                                                                             root/logo.c481326b.png'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 0.43510000000000004ms 200 image/png
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 POST http://dockerdmz-test.sit.local/api/passwor                                                                                                                                                             d application/json 127
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Unosquare.PassCore.Web.Controllers.PasswordController.                                                                                                                                                             Post (Unosquare.PassCore.Web)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "Post", controller = "Password"}. Executing c                                                                                                                                                             ontroller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCo                                                                                                                                                             re.Mvc.IActionResult] Post(Unosquare.PassCore.Web.Models.ChangePasswordModel) on                                                                                                                                                              controller Unosquare.PassCore.Web.Controllers.PasswordController (Unosquare.Pas                                                                                                                                                             sCore.Web).
**warn: Zyborg.PassCore.PasswordProvider.LDAP.LdapPasswordChangeProvider[0]
      found multiple with same username: [vittoriam]**
info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
      Executing ObjectResult, writing value of type 'Unosquare.PassCore.Web.Mode                                                                                                                                                             ls.ApiResult'.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action Unosquare.PassCore.Web.Controllers.PasswordController.Post                                                                                                                                                              (Unosquare.PassCore.Web) in 218.56150000000002ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Unosquare.PassCore.Web.Controllers.PasswordController.P                                                                                                                                                             ost (Unosquare.PassCore.Web)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 260.6336ms 400 application/json; charset=utf-8
^CApplication is shutting down...

**Comment by nikinname** [comment]
I am still bangin my head please let me know if there something wrong or missing in my config
in the ezample below I obviously changed domain name and passwords the assumption is:
domain = my.domain
I use samAccountName to login

 docker run  \
 -e WebSettings__EnableHttpsRedirect='false'  \
 -e AppSettings__LdapSearchBase='DC=my,DC=domain' \
 -e AppSettings__DefaultDomain='my.domain' \
 -e AppSettings__LdapSecureSocketLayer='false' \
 -e AppSettings__LdapStartTls='false' \
 -e AppSettings__LdapSearchFilter='"(sAMAccountName={Username})"' \
 -e AppSettings__LdapHostnames__0='mypdc.my.domain' \
 -e AppSettings__LdapPort='389' \
 -e AppSettings__LdapUsername='CN=some user,OU=someOU,DC=my,DC=domain' \
 -e AppSettings__LdapPassword='someverysecretpassword' \
 -e AppSettings__LdapSearchFilter='(sAMAccountName={Username})' \
 -e ClientSettings__UseEmail='false' \
 -it -p 80:80 passcore:latest
