### ISSUE TITLE
Modify

### ISSUE THREAD

**Issue by ifenice81** [unosquare/passcore#4]
Hello

First of all congratulations for the work done.
Second, I would like to use your project in my company.
My company is a government company, so I wanted to ask if we are entitled to change your home Page of the application?
and if you can help in this regard.
via file AppSetting.Json I could change some things but I was interested to change also the place PassCore and put it in the bottom of the page and add the location of our company.
It also adds some interest to the LINKS page.
Can you tell us how we can proceed.
I'm a systems engineer and I do not mean that much of the Web application

Thank you in advance

**Comment by mariodivece** [comment]
Yes. You are free to use and modify anything that I have made available here. Check out the License document available here: https://github.com/unosquare/passcore/blob/master/LICENSE
Make sure you star this project if you like it!
