### ISSUE TITLE
'Novell.Directory.Ldap.Logger' threw an exception.

### ISSUE THREAD

**Issue by 420kruk** [unosquare/passcore#400]
**PassCore Server**
- OS: Alpine Linux 3.10
- Docker version: 18.09.8-ce
- Provider: LDAP
- Passcore version: 4.2.1
- Settings file (without sensitive information): 
docker run \ 
 -e WebSettings__EnableHttpsRedirect='false' \ 
 -e AppSettings__UseAutomaticContext='false' \ 
 -e AppSettings__LdapSearchBase='DC=company,DC=corp' \ 
 -e AppSettings__LdapHostnames__0='server.company.corp' \ 
 -e AppSettings__LdapPort='636' \ 
 -e AppSettings__LdapUsername='CN=First Last,OU=Users,DC=company,DC=corp' \ 
 -e AppSettings__LdapPassword='P@ssw0rd1' \
 -e AppSettings__LdapSecureSocketLayer='true' \
 -it -p 80:80 user/passcore

**To Reproduce**
1. Start docker with parameters
2. Open passcore in web browser
3. Change password

**Expected behavior**
Password change

**Screenshots**
![usererror](https://user-images.githubusercontent.com/11447792/68152468-02b84300-ff44-11e9-9a68-d9f69a0b6e64.png)

![Capture](https://user-images.githubusercontent.com/11447792/68150929-04343c00-ff41-11e9-825e-c25dd3cd1999.PNG)

**Desktop (please complete the following information):**
 - OS: Windows Server 2012
 - Browser: Chrome

**Additional info:**
I have tried with ldap over 389 port with same result. I can send ldap request to server.company.corp without any issues using ldapsearch flast@company.corp / P@ssw0rd1

**Comment by JonathonReinhart** [comment]
I, too, noticed this exception and reported this issue to the upstream library: https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard/issues/100

It was just fixed a few hours ago, and AFAICT the fix should be present in the [`3.0.0-beta6` version](https://www.nuget.org/packages/Novell.Directory.Ldap.NETStandard/3.0.0-beta6).

**Comment by geoperez** [comment]
The new version of Novell client is up, let me review the code and upgrade.

**Comment by geoperez** [comment]
I updated the nuget, can you test against master branch?

**Comment by 420kruk** [comment]
Application won't load 
![Capture](https://user-images.githubusercontent.com/11447792/68625870-70331900-04da-11ea-962c-53a35664e291.PNG)

**Comment by Techcadia** [comment]
@420kruk Can you give master another try. The MR above should now allow you to see the actual error.

**Comment by 420kruk** [comment]
![Capture](https://user-images.githubusercontent.com/11447792/69575339-54e00780-0fca-11ea-94b3-3e09f22ab8f4.PNG)

**Comment by thejockel** [comment]
Hey @Techcadia,
when I try to build Master (using docker) the build fails.

I tried to use version 4.2.2 and replace 'src/Unosquare.PassCore.Web/Startup.cs' manually.
Now the build is successful, unfortunately now I get the same error.

Any ideas?

<img width="1280" alt="Screenshot 2020-01-22 at 18 24 24" src="https://user-images.githubusercontent.com/12292135/72917638-7ea47900-3d44-11ea-9f8b-15870a61e716.png">

**Comment by Xeiro** [comment]
> Hey @Techcadia,
> when I try to build Master (using docker) the build fails.
> 
> I tried to use version 4.2.2 and replace 'src/Unosquare.PassCore.Web/Startup.cs' manually.
> Now the build is successful, unfortunately now I get the same error.
> 
> Any ideas?
> 
> <img alt="Screenshot 2020-01-22 at 18 24 24" width="1280" src="https://user-images.githubusercontent.com/12292135/72917638-7ea47900-3d44-11ea-9f8b-15870a61e716.png">

Hello,
I am unable to build passcore from 4.2.1 to 4.2.2 too.

**Comment by geoperez** [comment]
There is a new version of Novell LDAP Client. Maybe we can take a look.
