### ISSUE TITLE
Passcore not working with Internet Explorer in Windows 10 client computers. Shows blank screen.

### ISSUE THREAD

**Issue by JC-CAN** [unosquare/passcore#401]
**PassCore Server**
- OS: [Windows ]
- Provider: [Active Directory]
- Settings file (without sensitive information): 
- Log file (without sensitive information): 

**Describe the bug**

I installed passcore in a Windows 2016 server.

Our clients computers are setup with Windows 10.

Passcore works well with Google Chrome and Mozilla Firefox from the client computers.

**The problem is that with Internet Explorer it shows a blank screen**

**Expected behavior**
I expect the passcore interface to render properly in Internet Explorer

**Screenshots**

This is how it shows in Internet Explorer

![image](https://user-images.githubusercontent.com/57373676/68160967-1c409700-ff12-11e9-9a76-7d8c1b8a82f8.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Internet Explorer]
 - Version [11]

**Comment by geoperez** [comment]
We are not supporting IE.

**Comment by JC-CAN** [comment]
Thanks Geovanni.

Do you mind me asking why is not supported with IE ?

Any plans to support IE in the future ? 

This application is solving an important issue for us in my organization.

Thanks for your help.

**Comment by JC-CAN** [comment]
Thanks Geovanni.
