### ISSUE TITLE
AllowedAD Groups not working

### ISSUE THREAD

**Issue by technicallife** [unosquare/passcore#402]
**PassCore Server**
- OS: Windows Server 2016 Core
- Provider: Active Directory
- Settings file (without sensitive information): 

{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
  "WebSettings": {
    "EnableHttpsRedirect": true
  },
  "AppSettings": {
    // The following options for AD Provider (remove if you don't use this Provider)
    "UseAutomaticContext": false, // Set true to allow PassCore to reset password using the same credentials, or false if you will fill the credentials below
    "RestrictedADGroups": [
      "Administrators",
      "Domain Admins",
      "Enterprise Admins",
      "other Groupname"], // Set the AD groups to restrict the use of PassCore
    "AllowedADGroups": [
      "nonrestricted Groupname"
      ], // Set the AD Groups to allow PassCore, if the array is empty all the groups no-restricted above are allowed
    "IdTypeForUser": "UPN", // Possible values are "DN", "GUID", "Name", "SAM", "SID" and "UPN" (Default UPN)
    "UpdateLastPassword": true, // Set true to allow PassCore to  update the last password timestamp
    // The following options are for LDAP Provider (remove if you don't use this Provider)
    "LdapSearchBase": "OU=base,DC=domain,DC=local",
    "LdapSecureSocketLayer": false, // Default for AD is true when using LDAPS 636
    "LdapStartTls": true, // Default for AD is true when using LDAP 389
    "LdapChangePasswordWithDelAdd": true,
    "LdapSearchFilter": "(sAMAccountName={Username})", // Another value: "(&(objectClass=person)(cn={Username}))"
    // General options (valid for both providers)
    "LdapHostnames": [ "dc1.domain.local","dc2.domain.local" ], // Set your hostname(s)
    "LdapPort": 389, // Default for AD is 389, for LDAPS 636
    "LdapUsername": "adminuser", // Set the username or distinguish name (DN) to bind the LDAP server
    "LdapPassword": "adminpw", // Set the password for the username
    "DefaultDomain": "domain.local" // Set your default AD domain here, or non "@" logins will not work! Use empty value to allow user to set the domain. This option is ONLY available with UPN.
  },{
      not relevant code
  }

- Log file (without sensitive information): 

**Describe the bug**
my testuser is in the "other groupname" group and also not in the "nonrestricted groupname" group, altough i am able to edit my password.

**To Reproduce**
give the user an restrictedadgroup and try to change the password 
**Expected behavior**
you can change the password

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by geoperez** [comment]
Can you post the log file, please?

**Comment by technicallife** [comment]
Oh i am sorry!
searched the logs and found this:

System.DirectoryServices.AccountManagement.PrincipalOperationException: While trying to retrieve the authorization groups, an error (5) occurred.

   at System.DirectoryServices.AccountManagement.AuthZSet..ctor(Byte[] userSid, NetCred credentials, ContextOptions contextOptions, String flatUserAuthority, StoreCtx userStoreCtx, Object userCtxBase)

   at System.DirectoryServices.AccountManagement.ADStoreCtx.GetGroupsMemberOfAZ(Principal p)

   at System.DirectoryServices.AccountManagement.UserPrincipal.GetAuthorizationGroupsHelper()

   at System.DirectoryServices.AccountManagement.UserPrincipal.GetAuthorizationGroups()

   at Unosquare.PassCore.PasswordProvider.PasswordChangeProvider.ValidateGroups(UserPrincipal userPrincipal) in C:\Unosquare\passcore\src\Unosquare.PassCore.PasswordProvider\PasswordChangeProvider.cs:line 157

**Comment by geoperez** [comment]
Since you are not using `UseAutomaticContext`, maybe the credentials that you are using are not allowed to read the groups of the user.

**Comment by geoperez** [comment]
I will investigate this issue: https://stackoverflow.com/questions/5814561/while-trying-to-retrieve-the-authorization-groups-an-error-5-occurred

**Comment by technicallife** [comment]
my service user is allowed to read groups :-( 

thanks for the investigation

**Comment by technicallife** [comment]
Any news out there?

**Comment by geoperez** [comment]
This is an open bug yet, @Serk352 can you take a look?

**Comment by rpelletierrefocus** [comment]
I am having the same problem. I am trying to change the password of a Domain Admin. There should not be any reason this would be denied.

**Comment by geoperez** [comment]
@rpelletierrefocus did you get the same error in your logs?

```
System.DirectoryServices.AccountManagement.PrincipalOperationException: While trying to retrieve the authorization groups, an error (5) occurred.
```

**Comment by Serk352** [comment]
@rpelletierrefocus  I made some changes in the code, could you please try it?

**Comment by technicallife** [comment]
@Serk352 @geoperez downloaded the last version - error still exists

**Comment by geoperez** [comment]
Same error? Do you get something else in the logs?
