### ISSUE TITLE
Allow for Passwords to be generated as suggestions

### ISSUE THREAD

**Issue by penguinthingie** [unosquare/passcore#415]
**Is your feature request related to a problem? Please describe.**
Not a problem, more requesting for a functionality that already exists but would like to see if its modular-able to a specific use.

*Note:* If you want to request a feature of passcorepro, please use the proper bug report form at https://store.unosquare.com/passcorepro

**Describe the solution you'd like**
Would it be possible to create a field during entering a new password to select an option to "generate a secure password" using the entropy and complexity requirements set within appsettings.json? This way an end user can take a suggested value or take inspiration from the generated value to pad their self preferred password. All of it as an optional function for the end user rather then "enforced".

The reason this option would be great to have is that we already have AD based password policy that enforces the "complexity" requirements which dissuades an end user from having too weak of a password. The ability to propose a randomly generated string of characters that could be utilized on its own or be suggested as something more personable by adding their unique memorable phrase to it would make the password change process a lot more positive to the end user experience.

**Describe alternatives you've considered**

**Additional context**
Thank you for this wonderful project!

**Comment by penguinthingie** [comment]
Hello.. any idea if this is possible or not in the pictures?

**Comment by Serk352** [comment]
@penguinthingie sorry for the long waiting, we have been busy, we will work on this as soon as possible, let you know when it is finished.
