### ISSUE TITLE
"UseAutomaticContext" false / true issue

### ISSUE THREAD

**Issue by takeahike** [unosquare/passcore#43]
In reference to this issue: https://github.com/unosquare/passcore/issues/21
I hope I correctly opened a new issue instead of commenting on issue 21.

I have an issue that I'm not sure the cause of. I have replaced PasswordControllr.cs with adalfa's and used the powershell script by jkberry on the service account used in appsettings.json.
Can anyone think of what I am doing wrong / what is going on?

If "UseAutomaticContext" is set to false:
-   User can change password on "User must change password on next login"
-   Seems to violate the password expiry rule? User can change password to the same one
-   User cannot change password on expired account, "You need to provide the current password"

If "UseAutomaticContext" is set to true:
-    User cannot change password on expired account. Just refreshes page and says nothing.
-    User cannot change password on "User must change password on next login" Just refreshes page and says nothing.
-    But password expiry policy appears to hold up.

**Comment by adalfa** [comment]
the service account is meant to be used on the application pool associated with the webapp: can you please verify?
The patch should be logging some info on the failure, can you please show the contents of the log?

thanks

**Comment by takeahike** [comment]
Thank you for the reply, I did not have it set that way before but it still does not seem to work.
I must be missing something obvious.

Just to clarify my setup.
- The Application pool identity for the website is set to the domain user that is also set in appsettings.json
- UseAutomaticContext is set to false in appsettings.json (will not work with true either)
- The powershell script by jkberry is run on that user. (I logged the output and there were no errors)
- That user is a standard (non-admin) domain user

There are no errors in the log, here is a snippet from a password change that should not have occurred as it was the same password. The next one was when the password was set to expired and it errored out saying "You need to provide the current password"


info: Microsoft.AspNet.Hosting.Internal.HostingEngine[1]
      Request starting HTTP/1.1 POST https://<REDACTED>/api/password application/json; charset=UTF-8 134
info: Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker[1]
      Executing action method Unosquare.PassCore.Web.Controllers.PasswordController.Post with arguments (Unosquare.PassCore.Web.Models.ChangePasswordModel) - ModelState is Valid'
info: Unosquare.PassCore.Web.Controllers.PasswordController[0]
      User  ianw
info: Unosquare.PassCore.Web.Controllers.PasswordController[0]
      InvalidCredentials
info: Microsoft.AspNet.Mvc.JsonResult[1]
      Executing JsonResult, writing value Unosquare.PassCore.Web.Models.ApiResult.
info: Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler[2]
      Executed action Unosquare.PassCore.Web.Controllers.PasswordController.Post in 0.0047ms
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[2]
      Request finished in 0.0047ms 400 application/json; charset=utf-8
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[1]
      Request starting HTTP/1.1 POST https://<REDACTED>/api/password application/json; charset=UTF-8 134
info: Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker[1]
      Executing action method Unosquare.PassCore.Web.Controllers.PasswordController.Post with arguments (Unosquare.PassCore.Web.Models.ChangePasswordModel) - ModelState is Valid'
info: Unosquare.PassCore.Web.Controllers.PasswordController[0]
      User  ianw
info: Unosquare.PassCore.Web.Controllers.PasswordController[0]
      Changepassword
info: Unosquare.PassCore.Web.Controllers.PasswordController[0]
      setpassword
info: Microsoft.AspNet.Mvc.JsonResult[1]
      Executing JsonResult, writing value Unosquare.PassCore.Web.Models.ApiResult.
info: Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler[2]
      Executed action Unosquare.PassCore.Web.Controllers.PasswordController.Post in 0.0063ms
info: Microsoft.AspNet.Hosting.Internal.HostingEngine[2]
      Request finished in 0.0063ms 200 application/json; charset=utf-8

**Comment by takeahike** [comment]
I managed to get this working but I still have a question regarding the configuration. 

The application pool identity is set to the service account as adalfa had reminded me about. Thank you for that.  But "UseAutomaticContext" has to be set to true.
If "UseAutomaticContext" is set to false it errors out:

There was an error changing your password
Error Information: The user name or password is incorrect. 
(no errors in the log either)

Could there be something else I am missing or is this OK that it works this way?
The comment by jkberry: https://github.com/unosquare/passcore/issues/21

Thanks!
Says to set "UseAutomaticContext" to false.

**Comment by takeahike** [comment]
I managed to get this working but I still have a question regarding the configuration.

The application pool identity is set to the service account as adalfa had reminded me about. Thank you for that. But "UseAutomaticContext" has to be set to true.
If "UseAutomaticContext" is set to false it errors out:

There was an error changing your password
Error Information: The user name or password is incorrect.
(no errors in the log either)

Could there be something else I am missing or is this OK that it works this way?
The comment by jkberry: https://github.com/unosquare/passcore/issues/21
Says to set "UseAutomaticContext" to false.

Thanks!

**Comment by tpattison** [comment]
@takeahike 

How did you get this to work as I am still receiving the "Error Information: You need to provide the correct current password." message even with UseAutomaticContext" set to true or false. The application pool identity set to a service account as well as the same account in the appsettings.json file. I ran the powershell script on this user without errors. 

Are you on a 2012R2 server?

**Comment by tpattison** [comment]
Actually, I can get them to change if I create a new user and set the change password flag in AD. It's when they are expired that I have an issue.

**Comment by takeahike** [comment]
Actually I only was testing "User must change password at next login" / setting the pwdLastSet attribute to 0.  Aside from setting a password policy to force a password expiring in say 1 day.  How would I force a password expiry on an account to test it? I am new to administrating AD and I thought that the pwdLastSet flag being set to 0 is what would happen when an password expired. What other attribute changes that I can test that with?

**Comment by takeahike** [comment]
I have confirmed that I cannot change an expired password. 
It fails with: "Error Information: You need to provide the correct current password." 
This happens when I set "UseAutomaticContext" to true or false.  
Have you had any luck with this?

**Comment by roaima** [comment]
Take the code from issue #21. Create a user account that has got delegated permissions to reset password and put those details on the configuration file.

**Comment by takeahike** [comment]
Thank you roaima, I did not have reset password delegation set for the service account.  Expired password changing is working now.
