### ISSUE TITLE
username with full domain 

### ISSUE THREAD

**Issue by ZioGuillo** [unosquare/passcore#44]
There is any option to set up by default the domain in the username field in any place ?

so only write the username in the box without the full domain

**Comment by johntraskcgi** [comment]
Did you ever figure this out?

**Comment by geoperez** [comment]
Current version can't do that, but you may modify the next line (https://github.com/unosquare/passcore/blob/master/src/Unosquare.PassCore.Web/Controllers/PasswordController.cs#L84) to append the domain.
