### ISSUE TITLE
Passcore works just once and second reset failed

### ISSUE THREAD

**Issue by inebriarete** [unosquare/passcore#45]
Hi all,

As a lot of companies I have some people that work at home or international, so I got the problem to permit the password reset.
I'd to try passcore and it seemed to be very usefull until my issue.

I've followed all the installation howto and it was ok
I've created a user to test it, I reset the password and it was ok.
But at the second tried to reset the password I got an error.
This issue appeared for all created users that I've tested.

error message:
"There was an error changing your password 
Error Information: An error occurred while sending the request."

Did someone get the same issue? And almost did someone know how to resolve it?

Thanks in advance for your help!

**Comment by johntraskcgi** [comment]
Did you ever figure this out?

**Comment by Hardywo** [comment]
This might be related to your password minimum age set in group policy...

**Comment by mariodivece** [comment]
Password policy is not controlled by PassCore
