### ISSUE TITLE
Urgent!!! There was an error changing your password-HRESULT: 0x800704F1

### ISSUE THREAD

**Issue by marlonc1980** [unosquare/passcore#46]
Hello everyone.

The application was working for 10 days without problems.

But then I get the following error and searching the Internet says it is an upgrade.

These updates are not installed on my Windows Server 2012r2 (my domain is Windows Server 2012r2)

***\* Error Information: The system cannot contact a domain controller to service the authentication request. Please try again later. (Exception from HRESULT: 0x800704F1)

**Comment by mdbrauer** [comment]
You need to uninstall:
KB3167679 
KB3177108 
Reboot your machine, then hide these updates.
Check for new updates, then install the latest patches.

**Comment by marlonc1980** [comment]
Thank you.


But Now i have:


Error Information: The password does not meet the password policy requirements. Check the minimum password length, password complexity and password history requirements. (Exception from HRESULT: 0x800708C5)





[cid:e42ccc76-ed37-44d1-8ffb-32461e9034fc]


________________________________

**Comment by JaggedKixx** [comment]
Is there another work around for this issue?  I am not able to uninstall those updates.

**Comment by ghaith9** [comment]
I have the same issue from beginning,
***
There was an error changing your password 
Error Information: The password does not meet the password policy requirements. Check the minimum password length, password complexity and password history requirements. (Exception from HRESULT: 0x800708C5)
****
we actually need to be a simple password not complex "or with user option" I hope to get help very soon

**Comment by mariodivece** [comment]
Please try with the latest version and let us know if this is still a problem. Reopen the issue if necessary.

**Comment by testbuilds123** [comment]
It is a old post but might be helpfull for the people like me.I was struggling for 4 days and this link solve my problem. Good Explanation.

http://blog.cionsystems.com/?p=907
