### ISSUE TITLE
Help!!!!----There was an error changing your password-Exception from HRESULT: 0x800708C5

### ISSUE THREAD

**Issue by marlonc1980** [unosquare/passcore#47]
There was an error changing your password
Error Information: The password does not meet the password policy requirements. Check the minimum password length, password complexity and password history requirements. (Exception from HRESULT: 0x800708C5)

![clave](https://cloud.githubusercontent.com/assets/22773021/19537394/fce4b22c-960c-11e6-996b-95fc13caecbd.PNG)

**Comment by roaima** [comment]
What's the problem? You have read the error message, haven't you...?

**Comment by marlonc1980** [comment]
Hi.


The Message is.



 There was an error changing your password

Error Information: The password does not meet the password policy requirements. Check the minimum password length, password complexity and password history requirements. (Exception from HRESULT: 0x800708C5)



My password policy did not trouble before




________________________________

**Comment by roaima** [comment]
Have you checked that your proposed new password does meet your domain's requirements?

**Comment by marlonc1980** [comment]
Yes, I used very complex password. I tried to change directly to the Active Directory server and work well in the portal, no longer works


________________________________

**Comment by SteveVerniers** [comment]
Hi, 

I'm having the exact same problem. I can assure that the password meets the complexity and requirement that is set by GPO.
When I reset my password inside an RDS session, it works perfectly.  When I try and reset it with passcore I get the fore mentioned error msg.

Please advice ?

**Comment by dmayan** [comment]
Same problem.

Even using password generator and this password:

**H8Q59{s@[{-FA%4~**

No problems at all changing it on the PDC.

Regards, Diego

**Comment by mariodivece** [comment]
Please search the other issues. I think there were a couple of Windows Server bugs and fixes that you need to apply.

**Comment by testbuilds123** [comment]
It is a old post but might be helpfull for the people like me.I was struggling for 4 days and this link solve my problem. Good Explanation.

http://blog.cionsystems.com/?p=907
