### ISSUE TITLE
Words are overlapping and everything is misaligned.

### ISSUE THREAD

**Issue by Adam-North** [unosquare/passcore#475]
picture is self explanatory.
![image](https://user-images.githubusercontent.com/16639794/72012604-d231a580-3221-11ea-9ab3-aab733facabb.png)

**Comment by Adam-North** [comment]
Happens in chrome but not edge by the way. this is a new install.

**Comment by ManuSanRam** [comment]
@Adam-North 
I'm currently checking this issue, however there doesn't seem to be any issue:
**Chrome**
![image](https://user-images.githubusercontent.com/28661932/72113429-0b434600-3306-11ea-999f-9727c5f75724.png)
Chrome version: 79.0.3945.117

**Edge**
![image](https://user-images.githubusercontent.com/28661932/72113466-2e6df580-3306-11ea-86b6-6f14535b1b06.png)
Edge version: 44.18362.449.0

**Comment by Xeiro** [comment]
Hello,
I do have same problem as @Adam-North in Safari. Chrome and Firefox are fine.

**Comment by geoperez** [comment]
@ManuSanRam  can you take a look at Safari?

**Comment by Adam-North** [comment]
This only seems to be happening in my chrome. Other machines I test it on are okay. it might be an extension installed.
