### ISSUE TITLE
IIS install via PowerShell fails due to incorrect Version Check .NET Core Windows Server Hosting bundle

### ISSUE THREAD

**Issue by xerxies** [unosquare/passcore#491]
**PassCore Server**
- OS: [Server 2019 Core]

The IIS install instructions point to .NET Core 3.0.0 Windows Server Hosting bundle as a prerequisite, but the Inststaller.ps1 script is doing a -match on "Microsoft .NET Core Host - 2.2" and pointing to the 'dotnet-runtime-2.2.3-windows-hosting-bundle-installer' file.

**To Reproduce**
1. Stand up a fresh 2019 Core install.
2. Install the IIS role.
3. Follow the [.NET Core 3.0.0 Windows Server Hosting bundle](https://dotnet.microsoft.com/download/thank-you/dotnet-runtime-3.0.0-windows-hosting-bundle-installer) link in the 'PowerShell Installer' section of the README.md.
4. Execute the PowerShell command that kicks off the install.
5. Install will fail on checking for the .NET Core Hosting bundle prereq, string matching on the wrong version.

**Expected behavior**
Installation begins after verifying the PreReqs.

**Screenshots**
![image](https://user-images.githubusercontent.com/6953368/72764700-dc9f5800-3bae-11ea-961e-6e94cc963343.png)

**Comment by Serk352** [comment]
Hi, @xerxies,

This issue was fixed in #495.
