### ISSUE TITLE
Custom PassCore color

### ISSUE THREAD

**Issue by lucafabbri365** [unosquare/passcore#507]
Hello,
I'm writing to ask for a (simple) way to customize PassCore, like changing color and/or adding a custom logo. I already read #201 and #249 however can you give me more information or make an example that I can use as a starting point?

Thank you,
Luca

**Comment by geoperez** [comment]
You can edit the front-end web app, for customization of the colors you need to check Material UI Themes (https://material-ui.com/customization/theming/).

**Comment by lucafabbri365** [comment]
Hello @geoperez,
thank you for your information.
I managed to customize PassCore palette and add custom logo (in place of question mark, on top-right) by modifying these files:

- _App.tsx_
- _ClientAppBar.tsx_
- _common.d.ts_

Thank you,
Luca

**Comment by geoperez** [comment]
Awesome! Out of curiosity, do you think it was easy?

Don't forget, please star this project if you find it useful!

**Comment by lucafabbri365** [comment]
Hello @geoperez,
I'm not a developer, but I'm an IT person, so using a little bit of logic and investigation I found the way to do a simple customization.

I have two questions/suggestions for you:

1. Is there a way to show a [Throbber](https://en.wikipedia.org/wiki/Throbber) after the user click the "Change Password" button and active until the password change process is not completed ? 
2. I'd like to show a pop-up window (like the box containing the form fields) to list password policy requirements to end-users. Currently I created a link placed behind Password field (see [screenshot](https://1drv.ms/u/s!ApCM_O5R9lZthPRVoSbqawVIqoMYMA?e=QBLJGZ)) to a standalone html page (see [screenshot](https://1drv.ms/u/s!ApCM_O5R9lZthPRUGrHXBT5xTpY1Pg?e=37VQy4)).

Thank you,
Luca

**Comment by geoperez** [comment]
Hi Luca,

1 - Yeah, it is possible. @Serk352 can you help us?
2 - You can add a popup there, you just need to create a Dialog like this one:

https://github.com/unosquare/passcore/blob/master/src/Unosquare.PassCore.Web/ClientApp/Dialogs/ChangePasswordDialog.tsx#L14

And use it at https://github.com/unosquare/passcore/blob/master/src/Unosquare.PassCore.Web/ClientApp/Components/ChangePasswordForm.tsx

If you see, the Dialog component contains two props, open is a boolean, so you just need to handle the onClick event in your link to set this flag on, and the Dialog will appear.

**Comment by Darkomen78** [comment]
Hi @lucafabbri365 can you show me where did you make your modifications ?
I'm an IT guy too but not really good in JS.
