### ISSUE TITLE
Docker Build fails

### ISSUE THREAD

**Issue by thejockel** [unosquare/passcore#508]
**PassCore Server**
- OS: [ Linux & macOS]
- Docker Version: 19.03.5
- Provider: [ Active Directory ]
- Settings file (without sensitive information): 
- Log file (without sensitive information): 

**Describe the bug**
Hey I am not able to build the master branch after this [commit](https://github.com/unosquare/passcore/commit/06b1ac840602477d300f3d93d6c88c7d3c26516f)
Swan seems not to be available.
```
Controllers/PasswordController.cs(9,11): error CS0246: The type or namespace name 'Swan' could not be found (are you missing a using directive or an assembly reference?) [/build/src/Unosquare.PassCore.Web/Unosquare.PassCore.Web.csproj]
Models/ApiResult.cs(17,43): warning CS8625: Cannot convert null literal to non-nullable reference type. [/build/src/Unosquare.PassCore.Web/Unosquare.PassCore.Web.csproj]
The command '/bin/sh -c dotnet publish -c Release -o /publish /p:PASSCORE_PROVIDER=LDAP' returned a non-zero code: 1
```

**To Reproduce**
    - git clone https://github.com/unosquare/passcore
    - cd passcore
    - docker build .

**Comment by geoperez** [comment]
Can you check again? I updated the master branch.

**Comment by thejockel** [comment]
I am able to build again.

THX
Jockel
