### ISSUE TITLE
Urgent: Unable to run the solution

### ISSUE THREAD

**Issue by manishseth9** [unosquare/passcore#52]
Hello, I am getting below error:

1. It's saying syntax error in line 1 of Vendor.min.js (dynamic). Also, my solution is not able to resolve dependencies on Angular and npm. I did go to nuget command console and installed bower and angularjs package.

Please let me know, what am I missing. Appreciate all help

Thanks
Manish

**Comment by mariodivece** [comment]
Please try with the latest version and let us know if this is still a problem. Reopen the issue if necessary.
