### ISSUE TITLE
PassCore no longer respects the ApplicationTitle property

### ISSUE THREAD

**Issue by AndrewStickler** [unosquare/passcore#523]
**PassCore Server**
- Version 4.2.0
- OS: Windows
- Provider: Active Directory
- Settings file (without sensitive information): N/A
- Log file (without sensitive information): N/A

**Describe the bug**
The ApplicationTitle property in ClientSettings used to populate the <head><title/></head> HTML element on the page, but, probably since the move to React, this is broken and the page title is always "passcorepro - Unosquare".

**Comment by Serk352** [comment]
@AndrewStickler this bug was fixed in #528 .

**Comment by AndrewStickler** [comment]
Excellent, thanks - any rough ETA when it will appear in a new release?

**Comment by geoperez** [comment]
I can release a new version tomorrow. @Serk352 you agree?

**Comment by AndrewStickler** [comment]
No need to do it just for me, I can wait until your next scheduled release if its not too far.

**Comment by Serk352** [comment]
@geoperez yes, let's do it.

**Comment by geoperez** [comment]
@AndrewStickler you can check the new version.

**Comment by AndrewStickler** [comment]
That fix looks good thank you, although I notice the version string at the bottom of the web page says v4.2.0, but perhaps you don't normally update that.
