### ISSUE TITLE
Non-AD, local machine Provider

### ISSUE THREAD

**Issue by ipaulo** [unosquare/passcore#524]
**Is your feature request related to a problem? Please describe.**
I have a web application that supports using local Windows users for accounts. It is a standalone server and not connected to a domain. Installing ADS on the server for the sole purpose of allowing passcore to handle password changes is a problem since some components don't like to be installed on a DC.

**Describe the solution you'd like**
Add the option to change passwords for local users instead of ADS.

**Describe alternatives you've considered**
1. Forgo implementing password changes. 
2. _Very_ carefully install the application components to workaround the presence of the DC. This is problematic because the workarounds are brittle and prone to break in future app updates.

**Comment by geoperez** [comment]
Did you already test using `UseAutomaticContext`?

**Comment by ipaulo** [comment]
Not until you mentioned it but I just tried it. It responds "The LDAP server is unavailable."

**Comment by geoperez** [comment]
According to this SO post (https://stackoverflow.com/questions/25386240/change-password-of-a-local-windows-user). Can you try?

**Comment by ipaulo** [comment]
I'm sorry, I don't follow what you are asking me to try from the SO post. Use that snippet to contribute a provider? I found in your code you are already doing a fallback to SetPassword if ChangePassword fails, so I'm not sure where to go. 

My assumption has been your tool - as is without AD - will fail because your code cannot talk to the host via LDAP. Non-DCs are not running LDAP.
