### ISSUE TITLE
Help -  Error Information: Exception from HRESULT: 0xC000006C

### ISSUE THREAD

**Issue by johntraskcgi** [unosquare/passcore#54]
I have done a bunch of searching but I am not seeing anything on this. I am getting the attached error when trying to change a password. Anyone seen this before? 
![001192](https://cloud.githubusercontent.com/assets/13320584/20373049/dbed9364-ac45-11e6-9ae1-d111d4b559dd.png)

**Comment by johntraskcgi** [comment]
After redeploying Passcore from scratch it seems it only works the first time and then stops working.

**Comment by gferen** [comment]
you maybe have restriction in domain to change password only one time in 24h period. had the same problem.

**Comment by johntraskcgi** [comment]
I fixed it by adding the LDAP hostname, username, password to the AppSetting file.
