### ISSUE TITLE
page design not mobile friendly

### ISSUE THREAD

**Issue by funmix** [unosquare/passcore#559]
Hi, is it possible to make the page to mobile friendly? the page is cut into half. need to change phone orientation to landscape in order to fully view.

![Screenshot_20200309_141848](https://user-images.githubusercontent.com/20920616/76187739-1e449a80-6211-11ea-86c6-bfb9f2c5f21a.jpg)

**Comment by geoperez** [comment]
It's possible to create a responsive design. unfortunately, we are not planning to have it yet.

PRs are welcome. Passcore is using Material UI, you can check for responsive UI here (https://material-ui.com/guides/responsive-ui/#responsive-ui)

**Comment by funmix** [comment]
> It's possible to create a responsive design. unfortunately, we are not planning to have it yet.
> 
> PRs are welcome. Passcore is using Material UI, you can check for responsive UI here (https://material-ui.com/guides/responsive-ui/#responsive-ui)

Thanks for reply, maybe can add some code to make it able to scroll at least left and right? the UI in mobile able to scroll to the left, but not scroll to the right. XD

**Comment by lmmartinm** [comment]
Hello @funmix 

What i ve done to make it look better on mobile is to replace:

**content="width=device-width, initial-scale=1">**

with:
**content="width=device-width, initial-scale=0.5">**

On wwwroot\index.html

And now you can zoom it, and move right - left. I dont know if i broken something, checking it now. (Tested on Android with default and Firefox browsers)

Thanks

![passcore-on-mobile-fix](https://user-images.githubusercontent.com/28003919/81287942-f2546280-9063-11ea-847e-fc513fce4bbf.png)

**Comment by lmmartinm** [comment]
Hello @funmix 

I think found a better fix, leave initial-scale as original:
**content="width=device-width, initial-scale=1">**

But modified:
**<div id="rootNode" style="height:100%;"></div>**
by:
**<div id="rootNode" style="height:100%;zoom:50%"></div>**

Still making tests

Thanks

**Comment by funmix** [comment]
> Hello @funmix
> 
> I think found a better fix, leave initial-scale as original:
> `content="width=device-width, initial-scale=1">`
> 
> But modified:
> `<div id="rootNode" style="height:100%;"></div>`
> 
> by:
> 
> `<div id="rootNode" style="height:100%;zoom:50%"></div>`
> 
> Still making tests
> 
> Thanks

@lmmartinm Thank you very much for your efforts. Appreciate it. Let me do some modification on it.

Thank you
