### ISSUE TITLE
Feature Request: The ability to change expired passwords

### ISSUE THREAD

**Issue by stevenmcastano** [unosquare/passcore#56]
That's one of my users biggest problems. I have an environment where people need to VPN in to connect and all they have access to are some file shares and database connections, there's no remote desktop session they can log into to be prompted to change their password when it expires and it seems as thought, once it's expired, using passcore they can't change their password. They get an error message about using correct credentials to change the password. I'm assuming it's failing the password check since their credentials are already expired.

Is there any way to make this happen? That would a HUGE improvement for us!

**Comment by doanhp** [comment]
You can setup a email reminder before it has expired. Search for Active Directory email password reminder.

**Comment by stevenmcastano** [comment]
I did not know that! I’m gonna look it up right now. Thanks!

**Comment by stevenmcastano** [comment]
Is this part of passcore, or do you mean I should just install something else to do it?

**Comment by doanhp** [comment]
It's something else. There are lots of free powershell scripts or plugins you can setup. Attached is what I used. You want to add the batch file to Task Scheduler on your Domain Controller, set it to run everyday at 7am. Edit the EmailExpiringPassword.ini file, enter your SMTPRelay, SMTPFROM, and customize the email message. You just got email reminder that email users 14days prior to their password expired.
[Emailscript.zip](https://github.com/unosquare/passcore/files/629024/Emailscript.zip)

**Comment by alejandroed** [comment]
is it the only way? It will be possible to deal with this inside passcore?

**Comment by geoperez** [comment]
Sorry, but we are not including that feature.
