### ISSUE TITLE
No support for modern cipher suites

### ISSUE THREAD

**Issue by illukas** [unosquare/passcore#562]
**PassCore Server**
- OS: Windows Server 2012 R2
- Provider: Active Directory 

**Describe the bug**
Application does not appear to work if only modern TLS 1.2 cipher suites are enabled.

**To Reproduce**
1. Run IISCryptoGUI as admin
2. Disable everything but TLS 1.2 on both Client and Server. 
3. Disable all ciphers but AES 128/128 and AES 256/256
4. Disable MD5 hashing
5. Enable only the following cipher suites:
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384_P521
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384_P384
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256_P521
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256_P384
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256_P256
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384_P521
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384_P384
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256_P521
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256_P384
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256_P256
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P521
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P384
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P256
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256_P521
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256_P384
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256_P256

**Expected behavior**
Application should function as expected.

**Desktop (please complete the following information):**
 - OS: Windows 10 1903
 - Browser: Firefox 68.4.1esr, Edge 80.0.361.62

**Additional context**
.net core 3.0 does have support both for GCM ciphers and SHA256/384 integrity hashes, yet the application will only accept TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA_P256 and none of the above mentioned suites.

**Comment by geoperez** [comment]
Do you mount passcore in IIS? Is IIS able to handle those ciphers?
