### ISSUE TITLE
Configuration issue Unknown error (0x80005000)

### ISSUE THREAD

**Issue by kansasdev** [unosquare/passcore#563]
**PassCore Server**
- OS: [Windows]
- Provider: [Active Directory]
- Settings file (without sensitive information): 
"UseAutomaticContext": false, // Set true to allow PassCore to reset password using the same credentials, or false if you will fill the credentials below
    "RestrictedADGroups": [
      "Administrators",
      "Domain Admins",
      "Enterprise Admins"
    ], // Set the AD groups to restrict the use of PassCore
    "AllowedADGroups": [], // Set the AD Groups to allow PassCore, if the array is empty all the groups no-restricted above are allowed
    "IdTypeForUser": "UPN", // Possible values are "DN", "GUID", "Name", "SAM", "SID" and "UPN" (Default UPN)
    "UpdateLastPassword": false, // Set true to allow PassCore to  update the last password timestamp
    // The following options are for LDAP Provider (remove if you don't use this Provider)
    "LdapSearchBase": "OU=myOU,DC=domain,DC=com",
    "LdapSecureSocketLayer": true, // Default for AD is true when using LDAPS 636
    "LdapStartTls": true, // Default for AD is true when using LDAP 389
    "LdapChangePasswordWithDelAdd": true,
    "LdapSearchFilter": "(sAMAccountName={Username})", // Another value: "(&(objectClass=person)(cn={Username}))"
    // General options (valid for both providers)
    "LdapHostnames": [ "dc.domain.com" ], // Set your hostname(s)
    "LdapPort": 389, // Default for AD is 389, for LDAPS 636
    "LdapUsername": "PwdReseter", // Set the username or distinguish name (DN) to bind the LDAP server
    "LdapPassword": "PwdPass", // Set the password for the username
	"DefaultDomain": "domain.com" // Set your default AD domain here, or non "@" logins will not work! Use empty value to allow user to set the domain. This option is ONLY available with UPN.
- Log file (without sensitive information): 

**Describe the bug**
I am not able to change password of an user. User can be found but when I am changing password I am receiving error Unknown error (0x80005000).
I have read that it can be because of inproper tls setting as changing password is requiring tls

**Expected behavior**
Possible to change password

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome

**Comment by smnzrn** [comment]
I have the same problem on the mac `{errors: [{errorCode: 8, fieldName: null, message: "Unexpected null exception"}], payload: null}`

**Comment by alex4108** [comment]
Same issue here

Passcore 4.2.0 on .NET Core 3.0.3 on Windows Server 2016 Core
Using plaintext LDAP and "UseAutomaticContext": false

**Comment by alex4108** [comment]
It seems by rolling back to .NET Core 3.0.0 I was able to resolve the issue.
That, or I fat fingered the JSON in the configuration.

**Comment by Petyaev** [comment]
Same issue.  PassCore v4.2.0 on Windows server 2016 Microsoft.NETCore.App 3.0.0

**Comment by mazrim67** [comment]
I am having the same issue on Windows Server 2016 Microsoft.NETCore.App 3.0.0. Running Passcore v4.2.0 and regular LDAP over 389/tcp with a service account. I tried switching to LDAPS and upgrading from 3.0.0 .NetCore to 3.1.4, but both changes failed with the same Unknown error (0x80005000).

Running with no service account and changing "UseAutomaticContext" to true does work, but I am looking for a solution to reset expired passwords and need a service account

**Comment by markstubb** [comment]
Same issue here. 2016 4.2.0

**Comment by unittech** [comment]
I have the same issue
really keen to use this site . it would be a life saver!
