### ISSUE TITLE
Fail on password change

### ISSUE THREAD

**Issue by DrRumack** [unosquare/passcore#564]
Hi,
I installed version 4.2.3 on iis and used default config file.  
I got the following log when i tried to change a users password.
Did i configured something wrong or is this a problem in the source code?

> info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]

Executing endpoint 'Unosquare.PassCore.Web.Controllers.PasswordController.Post (Unosquare.PassCore.Web)'

> info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]

 Route matched with {action = "Post", controller = "Password"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Post(Unosquare.PassCore.Web.Models.ChangePasswordModel) on controller Unosquare.PassCore.Web.Controllers.PasswordController (Unosquare.PassCore.Web).

> warn: Unosquare.PassCore.PasswordProvider.PasswordChangeProvider[0]

Using AutomaticContext

> info: Unosquare.PassCore.PasswordProvider.PasswordChangeProvider[0]

PerformPasswordChange for user yy@xxx.com

> fail: Unosquare.PassCore.PasswordProvider.PasswordChangeProvider[888]

ValidateGroups

> System.NullReferenceException: Object reference not set to an instance of an object.

at Unosquare.PassCore.PasswordProvider.PasswordChangeProvider.<ValidateGroups>b__7_1(Principal x) in C:\Unosquare\passcore\src\Unosquare.PassCore.PasswordProvider\PasswordChangeProvider.cs:line 173
at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
at Unosquare.PassCore.PasswordProvider.PasswordChangeProvider.ValidateGroups(UserPrincipal userPrincipal) in C:\Unosquare\passcore\src\Unosquare.PassCore.PasswordProvider\PasswordChangeProvider.cs:line 173

> warn: Unosquare.PassCore.PasswordProvider.PasswordChangeProvider[0]

The User principal password cannot be changed and setPassword won't be called

> warn: Unosquare.PassCore.PasswordProvider.PasswordChangeProvider[0]

The password does not meet the password policy requirements. Check the minimum password length, password complexity and password history requirements. (0x800708C5)

> info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]

Executing ObjectResult, writing value of type 'Unosquare.PassCore.Web.Models.ApiResult'.

**Comment by geoperez** [comment]
@Serk352 can you help me to verify the Group's validations? It looks like there is a null reference.

**Comment by DrRumack** [comment]
It happens when i leave " "AllowedADGroups": [] " blank. 
Now it works when i provided a group name to allowed ad groups but returns complexity error when i try to change the password second time for the same user.

**Comment by DrRumack** [comment]
Seems like it worked just that one time. I still can't change password for the test user and other users.
But there is no null reference error in the logs now.
