### ISSUE TITLE
recaptcha error:  Unexpected character encountered while parsing value: <. Path '', line 0, position 0. 

### ISSUE THREAD

**Issue by manu-tv** [unosquare/passcore#57]
dear all,

the system work fine and very well for me, but if I try to enable the recaptcha feature I receive this error after the click on "change password" button:

   Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

The recaptcha seems to works fine: I see the image and when I select the correct squares and click on "verify" button I receive the "I'm not a robot" correct validation.

Please can you help me to correct this issue?

Thanks in advance
Bye

**Comment by mariodivece** [comment]
Possibly WAF issue. Those F5s are kinda terrible. Outside the scope.
