### ISSUE TITLE
Support for Pwned Passwords API

### ISSUE THREAD

**Issue by jagbarcelo** [unosquare/passcore#570]
**Is your feature request related to a problem? Please describe.**
There are checks to prevent the users from using passwords that do not meet certain set of rules or complexity. Some of those checks could be performed locally. That is the case of the recent changes about distancing passwords (not too similar from the previous one).

However, there are cases where no simple set of rules can be used to check against passwords that should never be used. For those cases you either need a local DB with banned passwords or an external API to use.

**Describe the solution you'd like**
I have implemented support for calling to Pwned Passwords API before doing the actual change of the password. So, it the intended password does not qualify, the password is not updated in AD.
You can have a look at it https://github.com/jagbarcelo/passcore. I can make a PR if you want too.

**Describe alternatives you've considered**
Right now the Pwned Passwords API is always called. I have not made any config options to make it optional (on|off switch). I think that could be done easily too, but I didn't want to make more changes than those sctrictly  necessary to achieve what I needed. 
I created a different Project called PwnedPasswordsSearch so that the important code could be easily spotted. Feel free to move the code into another Project/Class anyway.

**Additional context**
See https://haveibeenpwned.com/API/v2#PwnedPasswords

**Comment by geoperez** [comment]
Hello, I like the idea, can you make a PR?

**Comment by jagbarcelo** [comment]
Done. Bear in mind that this is my first PR ever. I hope I had done it right.
