### ISSUE TITLE
unkown error 0x80005000

### ISSUE THREAD

**Issue by robina80** [unosquare/passcore#573]
hi all,

im getting this error and i dont know why

i have made passcore on a windows 10 pro and im using windows server 2012 r2 as the DC

thanks,
rob

**Comment by geoperez** [comment]
Can you paste the stacktrace?

**Comment by robina80** [comment]
i would geoperez but atm i cant even get it working ie using IIS, its just stopped working, sorry, i will get back to you when i get it back up and running again

also is it best to run this on windows server or windows pro?

**Comment by geoperez** [comment]
As far I know, IIS on Windows Pro is intended for development purposes, not for production environments.

**Comment by robina80** [comment]
Thanks, and is it OK to use

Net core hosting bundle 3.1.4

**Comment by robina80** [comment]
ok geoperez i have it finally working on windows 10 pro with net core 3.1.4

where do i find the stacktrace?

**Comment by robina80** [comment]
ok i have cracked it but i dont know why this is happening, when i change this

"UseAutomaticContext": true,

it works, when i change to "false" it doesnt

i have no idea why as i have put in my password reset username below in the required fields

"LdapHostnames": [ "dc.robo84.ddns.net" ],
    "LdapPort": 389,
    "LdapUsername": "passcore",
    "LdapPassword": "Passw0rd!",
    "DefaultDomain": "robo84.ddns.net"
