### ISSUE TITLE
起项目流程

### ISSUE THREAD

**Issue by dongshihao666** [unosquare/passcore#575]
Hello, I'm a front-end developer. I downloaded our project and entered the front-end directory. I downloaded all the necessary packages and executed the NPM run start command. As a result, the server got up, but the page is always in a loading state. So I want to ask how to load the project normally locally and then modify some UI styles. Thank you

**Comment by geoperez** [comment]
Ok, you need to run the .NET application (back-end) too. The start command in the package.json will only run the parcel build but you need to connect with the back-end. Otherwise the front-end won't start properly.

**Comment by dongshihao666** [comment]
OK, can you tell me in detail how to run the back-end application? I may not understand this. Thank you

**Comment by geoperez** [comment]
You need to run the command "dotnet run" to start the webapp.

**Comment by dongshihao666** [comment]
Does the current version of. Net support the development on Mac? Can it be realized through. Net core at present

**Comment by geoperez** [comment]
Yes, you can start the webapp in .NET Core for Mac.
