### ISSUE TITLE
Can't reach this page

### ISSUE THREAD

**Issue by starman9215** [unosquare/passcore#577]
**PassCore Server**
- OS: Windows server 2019
- Provider: Active directory
- Settings file (without sensitive information): 
- Log file (without sensitive information): 

Hi. I followed all the steps for installation on IIS, but the page says "can't reach this page" when I browse it. 

I downloaded a zip file (PassCore423.zip) and unzipped it under c:\inetpub where wwwroot and logs folders reside. 
So the final path is C:\inetpub\passcore423.

I installed dotNetFx45 and dotnet-sdk. 

I also tried a PowerShell command but it says I need to configure appsetting.json first, so I gave up. 

Sorry if I'm asking you really basic and dumb question. I'm kinda new to this, But I really want to deploy it to our environment. 

Thanks.

**Comment by geoperez** [comment]
All the files should be unzipped inside wwwroot.

**Comment by starman9215** [comment]
@geoperez Thanks for your super quick response!

I just unzipped all files under c:\inetpub\wwwroot, but still doesn't work. 
[https://ibb.co/s9QMy2q](url)

I attached a screenshot.

**Comment by geoperez** [comment]
Did you do this part?

Go to your IIS Manager, Right-click on Application Pools and select Add Application Pool.
A dialog appears. Under Name enter PassCore Application Pool, Under .NET CLR Version select No Managed Code and finally, under Managed pipeline mode select Integrated. Click OK after all fields have been set.

**Comment by starman9215** [comment]
Yes I already did. Am I missing something?

https://ibb.co/5r3gTBP
https://ibb.co/QJvqnCb

**Comment by starman9215** [comment]
Firewall is already disabled.

**Comment by starman9215** [comment]
NVM. I edited a host file, it's working now. 

Thanks.
