### ISSUE TITLE
not issue but question

### ISSUE THREAD

**Issue by gferen** [unosquare/passcore#58]
why is response posted to your page?
/* MAKE AJAX REQUEST to our server with g-captcha-string */
						$http.post('https://code.ciphertrick.com/demo/phpapi/api/signup','mykey',vcRecaptchaService.getResponse()).success(function(response){

**Comment by geoperez** [comment]
I'm not sure about that code, where is it?

**Comment by gferen** [comment]
app.js
Line 103
But as checked again in current version 2.0.2 beta2 app.js was removed.

**Comment by geoperez** [comment]
Ok, closing issue.
