### ISSUE TITLE
Running as a sub-application blank page

### ISSUE THREAD

**Issue by spokkioso** [unosquare/passcore#582]
**PassCore Server**
- OS: [Windows ]
- Provider: [Active Directory]
- Settings file (without sensitive information): 
- Log file (without sensitive information): 

**Describe the bug**
After installed passcore using online instructions i'm trying to configure it to respond to a url https://hostname/changepwd, following the "Running as a sub-application" settings i put this line on the index.html file

<base href="/changepwd/" />

and added a virtual app with the same name under de Passcore website...the result is a blank page everytime i try to load the page at the url http://hostname:8080/changepwd

on the logs i can't see any error messages

**Comment by PandaBjoern** [comment]
I have the exact same issue. With or without placing <base href="/PassCore/" /> into index.html I only receive a blank page in response. I configured the sub-application as "PassCore". And there are no error messages in the logs either.

**Comment by PandaBjoern** [comment]
Wow - that is so lame. Let a bot close your tickets! Bravo!
