### ISSUE TITLE
New version with disable button feature

### ISSUE THREAD

**Issue by JuanSpezialeModus** [unosquare/passcore#588]
I saw that you already did the changes to [disable the submit button](https://github.com/unosquare/passcore/commit/1dc0b1d88dc8a7a9bbe29f3db05d25b39efa7aa2#diff-026e373333cdf94a99ddc5533f8ddfe4) and I did a build including that change but it is not working, maybe I am using the wrong version of net Core, node or who knows.

I wonder if you can release a new version or give me some tips to be able to do it.

Thanks!

**Comment by geoperez** [comment]
You can download the new compiled version 4.2.4 from the Releases page.

**Comment by JuanSpezialeModus** [comment]
Thank you so much!
