### ISSUE TITLE
How to install Passcore on Ubuntu, can give me step by step

### ISSUE THREAD

**Issue by voducthoitc888** [unosquare/passcore#589]
Dear,

I have been got the source code of passcore a few day ago, But I don't know how to install it on Ubuntu server.
Please help me : How do I install passcore on ubuntu, can give me the step by step.

Thanks so much,
Tho

**Comment by geoperez** [comment]
Can you take a look at https://github.com/unosquare/passcore#docker ?

**Comment by voducthoitc888** [comment]
> Can you take a look at https://github.com/unosquare/passcore#docker ?

Thanks , but I'm not yet know about docker :(. so I don't know how to begin?

**Comment by husisusi** [comment]
It is really a shame and bitter to have awesome software with no information's how to install it on Linux!!!!
Can someone tell us which dll should we start? There is no passcore.dll!

**Comment by husisusi** [comment]
I was able to install and run the last version on Ubuntu 18.04 and I will now document it.
@geoperez, where and how should it be documented?

**Comment by geoperez** [comment]
You can add a PR editing the README file.

Thanks

**Comment by husisusi** [comment]
PR done.

**Comment by voducthoitc888** [comment]
Thanks for your updated step on linux. So would you like show me how to configure it to run on apache2.
Install and configure apache2 (or nginx) as Porxy your apache vhost should look something like this (Please use SSL):
<VirtualHost *:80>

    RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}
    ProxyPreserveHost On
    ProxyPass / http://127.0.0.1:5000/
    ProxyPassReverse / http://127.0.0.1:5000/
    ServerName passcore.company.com

         ErrorLog /var/log/apache2/passcoreerror.log
         CustomLog /var/log/apache2/passcoreaccess.log combined

</VirtualHost>
==> added on  **/etc/apache2/sites-available/000-default.conf**
But can not start apache2, some thing error.
Please help me, 
Which file config, which file to add home directory of passcore on apache2 config.
Thanks so much !

**Comment by husisusi** [comment]
@voducthoitc888 if you are not familiar with Linux, please use Windows installation or ask some administrator to help you.

**Comment by voducthoitc888** [comment]
> @voducthoitc888 if you are not familiar with Linux, please use Windows installation or ask some administrator to help you.

Thanks, I have been running a web on window server 2012 but it will be shutdown about the license of Window, So I need help to build passcore again on linux.
thanks !

**Comment by voducthoitc888** [comment]
Please help me how to bring up the web access passcore?
the defaul home Directory on apache < /var/www/html/>
Where do I need change something to bring up web?

thanks so much !

**Comment by voducthoitc888** [comment]
Dear ,

I have been actived ssl on apache2, I can access with https://pwd.local ( my site).
But I can not access home directory of passcore on apache2. 
still default apache2 home page, like as :
![pwd local](https://user-images.githubusercontent.com/70127967/91524704-0c26f780-e92a-11ea-91ee-d43be52260b9.gif)

Please help me how to access the drirectory passcore from apache2.

Thanks so much !

**Comment by voducthoitc888** [comment]
Now , I have success to access home directory passcore, but apache2 loading,( as picture)
![Untitled](https://user-images.githubusercontent.com/70127967/91526787-9b360e80-e92e-11ea-9082-1e0ec37ae682.gif)
Just loading passcore...
please help me,

**Comment by voducthoitc888** [comment]
This is my passcore server on Window Server, It's running,
Affter access by web to it, it's tranfer to here. (as picture)
![pass](https://user-images.githubusercontent.com/70127967/91545638-7d2ad700-e94b-11ea-8d69-c4b08b525908.gif)

But on linux, It's still Loading Passcore....
Don't work on linux,
![Untitled](https://user-images.githubusercontent.com/70127967/91545683-92076a80-e94b-11ea-9def-58f7178eca8d.gif)
PLease help me fix it, thanks so much !

**Comment by voducthoitc888** [comment]
Update code on index.html on linux, not work for view.
<!DOCTYPE html><html lang="en" style="height:100%;overflow-y:auto;overflow-x:hidden"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="passcore"><meta name="author" content="Unosquare"><title id="title">Loading...</title></head><body style="height:800px;"> <div id="rootNode" style="height:100%;"></div> <script src="/App.e6589045.js"></script>
</body></html>

**Comment by voducthoitc888** [comment]
I Update the status of passcore.service.


thovo@ubuntu:/opt/passcore$ sudo systemctl status passcore.service
● passcore.service - PassCore
   Loaded: loaded (/etc/systemd/system/passcore.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: signal) since Fri 2020-08-28 18:26:08 +07; 3s ago
  Process: 60974 ExecStart=/usr/bin/dotnet /opt/passcore/Unosquare.PassCore.Web.dll (code=killed, signal=ABRT)
 Main PID: 60974 (code=killed, signal=ABRT)

Aug 28 18:26:08 ubuntu systemd[1]: passcore.service: Main process exited, code=killed, status=6/ABRT
Aug 28 18:26:08 ubuntu system[1]: passcore.service: Failed with result 'signal'.


thanks,

**Comment by geoperez** [comment]
Open the Chrome Debugger and check what call is failing.

**Comment by voducthoitc888** [comment]
I have check the PID but it's not exit. Please check as bellow.

**thovo@ubuntu:/opt/passcore$ sudo systemctl start passcore.service
thovo@ubuntu:/opt/passcore$ sudo systemctl status passcore.service
● passcore.service - PassCore
   Loaded: loaded (/etc/systemd/system/passcore.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: signal) since Mon 2020-08-31 10:36:43 +07; 2s ago
  Process: 76335 ExecStart=/usr/bin/dotnet /opt/passcore/Unosquare.PassCore.Web.dll (code=killed, signal=ABRT)
 Main PID: 76335 (code=killed, signal=ABRT)

Aug 31 10:36:43 ubuntu systemd[1]: passcore.service: Main process exited, code=killed, status=6/ABRT
Aug 31 10:36:43 ubuntu systemd[1]: passcore.service: Failed with result 'signal'.
thovo@ubuntu:/opt/passcore$ kill -9 76335
-bash: kill: (76335) - No such process
thovo@ubuntu:/opt/passcore$**

Help me,
Is it start?
thanks so much,.

**Comment by voducthoitc888** [comment]
Dear,
Please help me check the passcore.service config file. I have been install a new clean ubuntu server. But still not work,.


thovo@passcore:/opt$ systemctl status passcore.service
● passcore.service - PassCore
     Loaded: loaded (/etc/systemd/system/passcore.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: core-dump) since Tue 2020-09-01 09:49:05 UTC; 19s ago
    Process: 57743 ExecStart=/usr/bin/dotnet /opt/passcore/Unosquare.PassCore.Web.dll (code=dumped, signal=ABRT)
   Main PID: 57743 (code=dumped, signal=ABRT)

Sep 01 09:49:05 passcore systemd[1]: passcore.service: Main process exited, code=dumped, status=6/ABRT
Sep 01 09:49:05 passcore systemd[1]: passcore.service: Failed with result 'core-dump'.
thovo@passcore:/opt$ kill -9 57743
-bash: kill: (57743) - No such process

Please help me fix ,

Thanks so much .

**Comment by voducthoitc888** [comment]
@crsleeth can you help me this issue

**Comment by crsleeth** [comment]
@voducthoitc888 I never was able to get PassCore working on Ubuntu but didn't attempt more than once. I set it up successfully on Windows Server 2016.

**Comment by voducthoitc888** [comment]
> @voducthoitc888 I never was able to get PassCore working on Ubuntu but didn't attempt more than once. I set it up successfully on Windows Server 2016.

Thanks so much, I has passcore on window server, but now, i want to install it on ubuntu, but as you know, i have many error with passcore on unbuntu.  :(

**Comment by sergiochoo** [comment]
Same issue with docker.
Stuck on "Loading Passcore..."

Docker logs looks good except this:
"fail: Microsoft.AspNetCore.Server.Kestrel[13]
Connection id "0HM3R7VBDLT60", Request id "0HM3R7VBDLT60:00000005": An unhandled exception was thrown by the application."

Chrome debugger says:
Request URL: http://<passcore_server_ip>/api/password
Status Code: 500 Internal Server Error

**Comment by sergiochoo** [comment]
Also, I found this in the logs:
System.InvalidOperationException: Failed to convert configuration value at 'AppSettings:LdapPort' to type 'System.Int32'.
passcore    |  ---> System.ArgumentException: '389' is not a valid value for Int32. (Parameter 'value')
passcore    |  ---> System.FormatException: Input string was not in a correct format.

What's wrong with value '389'?
