### ISSUE TITLE
HTTP Error 500.19 - Internal Server Error

### ISSUE THREAD

**Issue by ravikanchi8** [unosquare/passcore#59]
Hi,

i have followed same steps given https://github.com/unosquare/passcore  in this link.. 

pls do needful.. 
![image](https://cloud.githubusercontent.com/assets/25028785/21801256/ec24fa98-d746-11e6-9c67-6f228f25d8a5.png)
![passcode](https://cloud.githubusercontent.com/assets/25028785/21801274/f696349c-d746-11e6-9fbc-898b7031638c.jpg)

**Comment by mariodivece** [comment]
Please try with the latest version and let us know if this is still a problem. Reopen the issue if necessary.

**Comment by TheVakman** [comment]
@mariodivece I'm on the latest (3.0.1) and I'm having this issue.

If I manually run the Unosquare.PassCore.Web.exe, the application functions as expected.

- All "Application Development" sub-roles of IIS have been installed.
- I'm running Server 2016. 
- .NET 4.6 is installed from Server Features.

**Comment by geoperez** [comment]
Did you install the hosting bundle? The error is because a missing module.

**Comment by TheVakman** [comment]
@geoperez I did. It shows in Programs and Features as well.
