### ISSUE TITLE
Require minimum password strength?

### ISSUE THREAD

**Issue by dyelton** [unosquare/passcore#6]
Is there a way to require a minimum password strength?

**Comment by mariodivece** [comment]
The GPO policy does get applied by directory services which passcore uses to change passwords. Try it out and let me know if after applying your password policy you are able to change passwords that don't comply with your password requirements.

**Comment by dyelton** [comment]
You are correct, GPO settings get applied correctly, but I guess I'm looking for greater flexibility. Complexity requirements for group policy state that you just need to have at least three of uppercase, lowercase, digit, and special character. I would rather require say all four from within Passcore if possible to make things even more secure. Otherwise someone could just make their password 'Password1' and satisfy the requirements.

It would be a huge benefit to tie it into the password strength meter to require a minimum strength to proceed.

**Comment by mariodivece** [comment]
I am not planning on implementing this feature. My apologies @dyelton 
Closing.
