### ISSUE TITLE
someone is using reCAPTCHA (I'm trying but it doesn't works)?

### ISSUE THREAD

**Issue by manu-tv** [unosquare/passcore#60]
1) I've registered my site and get the private code and site cote
2) I'ìve edited the appsettings.json:

      "AppSettings": {
          "RecaptchaPrivateKey": "put here my private key",
          "PasswordChangeOptions": {
            "UseAutomaticContext": true,
            "LdapHostname": "",
            "LdapPort": 389,
            "LdapUsername": "",
            "LdapPassword": ""
          },
          "ClientSettings": {
            "ShowPasswordMeter": true,
            "Recaptcha": {
              "IsEnabled": true,
              "SiteKey": "put here my prite key",
              "LanguageCode": "en"

3) after restarting the webserver , I see the recaptcha option (I'm not a robot) on the change password screen;
4) clicking on I'm not a robot I see the selection window (select all the the square with ....)
5) after the square selection the recaptcha verification work fine and the browser returns on the change password;
6)then, if I submit the form (with correct username, old password and new password) the the change password task doesn't works wits a recaptcha verification problem
1) I've registered my site and get the private code and site cote
2) I'ìve edited the appsettings.json:

      "AppSettings": {
          "RecaptchaPrivateKey": "put here my private key",
          "PasswordChangeOptions": {
            "UseAutomaticContext": true,
            "LdapHostname": "",
            "LdapPort": 389,
            "LdapUsername": "",
            "LdapPassword": ""
          },
          "ClientSettings": {
            "ShowPasswordMeter": true,
            "Recaptcha": {
              "IsEnabled": true,
              "SiteKey": "put here my prite key",
              "LanguageCode": "en"

3) after restarting the webserver , I see the recaptcha option (I'm not a robot) on the change password screen;
4) clicking on I'm not a robot I see the selection window (select all the the square with ....)
5) after the square selection the recaptcha verification work fine and the browser returns on the change password;
6)then, if I submit the form (with correct username, old password and new password) the the change password task doesn't works wits a recaptcha problem.

It's working to someone?
(I would like to use because increase the security ... and is very nice! )

Thanks in advance to all!

**Comment by merocle** [comment]
Yes, all working perfect.
look:
"RecaptchaPrivateKey": "put here my private key"  - ok, Secret key
"SiteKey": "put here my private key",  - no, put here you Site key

**Comment by mariodivece** [comment]
@merocle Thanks!

**Comment by fdelcorso** [comment]
Hi, I had the same issue on IIS 10 and reCAPTCHA v2 , the message was: could not verify you are not a robot. I put the right "Recaptcha": {
      "SiteKey": "...",
      "PrivateKey": ".."
