### ISSUE TITLE
Password change is very long and when it's done, I have a lot of error message

### ISSUE THREAD

**Issue by fredericfleury** [unosquare/passcore#600]
**PassCore Server**
- OS: Windows 
- Provider: Active Directory
- Settings file (without sensitive information): 
"AppSettings": {
    // The following options for AD Provider (remove if you don't use this Provider)
    "UseAutomaticContext": true, // Set true to allow PassCore to reset password using the same credentials, or false if you will fill the credentials below
    "RestrictedADGroups": [
		"Domain Admins"
	], // Set the AD groups to restrict the use of PassCore
    "AllowedADGroups": [
		"Passcore"
	], // Set the AD Groups to allow PassCore, if the array is empty all the groups no-restricted above are allowed
    "IdTypeForUser": "SAM", // Possible values are "DN", "GUID", "Name", "SAM", "SID" and "UPN" (Default UPN)
    "UpdateLastPassword": false, // Set true to allow PassCore to  update the last password timestamp
    // The following options are for LDAP Provider (remove if you don't use this Provider)
    "LdapSearchBase": "dc=xx,dc=xx,dc=xx,dc=xx",
    "LdapSecureSocketLayer": false, // Default for AD is true when using LDAPS 636
    "LdapStartTls": true, // Default for AD is true when using LDAP 389
    "LdapChangePasswordWithDelAdd": false,
    "LdapSearchFilter": "(sAMAccountName={Username})", // Another value: "(&(objectClass=person)(cn={Username}))"
    // General options (valid for both providers)
    "LdapHostnames": [ "xx.xx.xx.xx.xx" ], // Set your hostname(s)
    "LdapPort": 389, // Default for AD is 389, for LDAPS 636
    "LdapUsername": "xxxx", // Set the username or distinguish name (DN) to bind the LDAP server
    "LdapPassword": "xxxx", // Set the password for the username
    "DefaultDomain": "xxxxxxxxxx" // Set your default AD domain here, or non "@" logins will not work! Use empty value to allow user to set the domain. This option is ONLY available with UPN.
  },
- Log file (without sensitive information): 
info: Unosquare.PassCore.PasswordProvider.PasswordChangeProvider[0]

      PerformPasswordChange for user test-user2
warn: Unosquare.PassCore.PasswordProvider.PasswordChangeProvider[0]

      The User principal password cannot be changed and setPassword won't be called

warn: Unosquare.PassCore.PasswordProvider.PasswordChangeProvider[0]

      The specified network password is not correct. (0x80070056)

**Describe the bug**
When I launch a password reset, it took a very long time (at least 2 minutes, but sometimes more).
After displaying the message of success, I have a lot of messages "Failed due to password complex policies: New password length is shorter than AD minimum password length".
When I watched the log, I have a lot of tries to change password and a lot of warning messages.
In my last log I have 3330 times "PerformPasswordChange for user test-user2" and 3325 "The specified network password is not correct. (0x80070056)".
I have the same behaviour with ldaps.

*Note:* If you want to report an issue of passcorepro, please use the proper bug report form at https://store.unosquare.com/passcorepro

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Whale, Chrome, Firefox
 - Version [e.g. 22] : all in last version.

**Comment by postheimer** [comment]
same problem, the right is correct 

sometime its work at the first time and sometime he loop on chrome

![image](https://user-images.githubusercontent.com/54264707/99087125-b11cac80-25ca-11eb-9956-631e62dc1e3c.png)

**Comment by fredericfleury** [comment]
I stopped debugging this issue.
I try a passcore pro version and it works better.

**Comment by postheimer** [comment]
i have purchases the passcore pro too , but i dont understand , the website is a manager of ad for admin users

i search a website for users change itself the password

**Comment by fredericfleury** [comment]
> i have purchases the passcore pro too , but i dont understand , the website is a manager of ad for admin users
> 
> i search a website for users change itself the password

Hi,
you can hide the management of AD account, and only authorize the password change : Branding -> Use single Form mode. 
As it said in the application :  If this feature is activated, the Web App will be transformed into a form with the only purpose and functionality of changing the user password.

**Comment by postheimer** [comment]
Hello 

 

Thanks for your help

 

I have a last problem , when i import my certificate , the result is ok but nothing respond on 8686 port 

 

The 7575 is ok 

 

When i see log i have see the web server prefix is https://+8686/ 

 

???

 

11:04:15.396 INF >> [WebServer] [CW5wYcK6EEuS02ADNQzg2A] GET /startup/settings: "200 OK" sent in 192ms (0 bytes)

11:04:15.504 INF >> [WebServer] [lLpLnpQBxUCLD7sb303Tcw] GET /2.bundle.js: "200 OK" sent in 27ms (9429 bytes)

11:04:15.509 INF >> [WebServer] [Wyfyaay4O0C5s4iiUi/9lA] GET /11.bundle.js: "200 OK" sent in 35ms (6525 bytes)

11:04:15.516 INF >> [WebServer] [1dEy34Ur5U+YopDhuOuCPQ] GET /5.bundle.js: "200 OK" sent in 40ms (7862 bytes)

11:04:15.552 INF >> [WebServer] [iSSHb3uXDkSN1/PuDoevnQ] GET /6.bundle.js: "200 OK" sent in 74ms (3758 bytes)

11:04:15.942 INF >> [WebServer] [esfr8Gx5+UCOV9k5oc16+w] GET /startup/getLogo: "200 OK" sent in 8ms (0 bytes)

11:04:23.632 INF >> [WebServer] [KGW1Yp0i6kWd16tbyvSoeA] GET /api/certs: "200 OK" sent in 38ms (0 bytes)

11:04:28.175 INF >> [NetshProvider] netsh http delete sslcert ipport=0.0.0.0:8686 

 11:04:29.200 ERR >> [netsh] Suppression du certificatÿSSL r‚ussie

11:04:29.210 INF >> [NetshProvider] netsh http add sslcert ipport=0.0.0.0:8686 certhash=48BA53769A59633F069B36E0FF2B6898AEF8FE51 appid={adaa04bb-8b63-4073-a12f-d6f8c0b4383f}

11:04:29.308 ERR >> [netsh] Ajout du certificat SSL r‚ussi.

11:04:29.323 INF >> [WebServer] [IS+RFNGIJkOnEfn857T6Lg] GET /api/certsNew/48BA53769A59633F069B36E0FF2B6898AEF8FE51: "200 OK" sent in 1164ms (0 bytes)

11:04:52.447 INF >> [StartupService] Stopping service...

11:04:52.449 INF >> [WebServer] Cleaning up

11:04:52.474 INF >> [StartupService] Service was stopped.

11:04:57.977 INF >> [StartupService] Starting service...

11:04:58.053 INF >> [StartupService] Service is now running.

11:04:58.238 INF >> [WebServer] Running HTTPListener: Unosquare HTTP Listener

11:04:58.240 INF >> [WebServer] Web server prefix 'http://localhost:7575/' added.

11:04:58.240 INF >> [WebServer] Web server prefix 'https://+:8686/' added.

11:04:58.566 INF >> [WebServer] Started HTTP ListenerDe : fredericfleury <notifications@github.com> 
Envoyé : lundi 16 novembre 2020 08:48
À : unosquare/passcore <passcore@noreply.github.com>
Cc : postheimer <po@micro-center.be>; Comment <comment@noreply.github.com>
Objet : Re: [unosquare/passcore] Password change is very long and when it's done, I have a lot of error message (#600)

 

i have purchases the passcore pro too , but i dont understand , the website is a manager of ad for admin users

i search a website for users change itself the password

Hi,
you can hide the management of AD account, and only authorize the password change : Branding -> Use single Form mode.
As it said in the application : If this feature is activated, the Web App will be transformed into a form with the only purpose and functionality of changing the user password.

**Comment by jjblack** [comment]
This sounds like a duplication of #598
