### ISSUE TITLE
Cannot compile PassCore Visual Studio 2019

### ISSUE THREAD

**Issue by luciofassio** [unosquare/passcore#616]
just downloaded passcore-master.zip, installed node.js (LS version) and tried to compile but get these errors in VS 2019:

Could not find any Python installation to use	Unosquare.PassCore.Web	C:\inetpub\wwwroot\passcore-master\src\Unosquare.PassCore.Web\EXEC	1	

MSB3073	The command "npm install" exited with code 1.	Unosquare.PassCore.Web	C:\inetpub\wwwroot\passcore-master\src\Unosquare.PassCore.Web\Unosquare.PassCore.Web.csproj	53	
 
I'm a newbie with ASP.Net Core and i'm lost, may someone help?

Thank you in advance.

VS 2019 16.8.3
node.js   v14.15.4
dotnet    5.0.101

**Comment by geoperez** [comment]
you might need to install Python to fix the issue with npm.

**Comment by luciofassio** [comment]
Update: it turned out (as geoperez suggests)  that a step of node.js installation was missing, which among pther things installs Python. After doing that and rebooting machine the error becomes as follows:

Cannot find module 'C:\inetpub\wwwroot\passcore-master\src\Unosquare.PassCore.Web\ClientApp\node_modules\parcel-bundler\bin\cli.js'	Unosquare.PassCore.Web	C:\inetpub\wwwroot\passcore-master\src\Unosquare.PassCore.Web\EXEC	1	

MSB3073	The command "npm run build" exited with code 1.	Unosquare.PassCore.Web	C:\inetpub\wwwroot\passcore-master\src\Unosquare.PassCore.Web\Unosquare.PassCore.Web.csproj	59	

Thank you for your help.

**Comment by luciofassio** [comment]
Solved: you need to install parcel-bundler into teh project :
1. open a Windows prompt as administrator
2. cd to the ClientApp folder of your project
3. run: npm install parcel-bundler --save-dev
4. recompile the project
