### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by lucafabbri365** [unosquare/passcore#624]
Hello,

I'm writing for an issue related to .NET Core 5.0.1 and lastest PassCore version 4.2.4 hosted in Windows Server 2019 server.
I installed **.NET Core 5.0.1 Windows Server Hosting bundle**, as specified on PassCore project's page; however the website doesn't work and the error below appears on _Event Viewer > Application_ log:

Source: **IIS AspNetCore Module V2**
Event ID: **1027**
```
Could not find 'aspnetcorev2_inprocess.dll'. Exception message:
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      5.0.1 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.
```

I tried to change the handler inside the _web.config_ from **AspNetCoreModuleV2** to **AspNetCoreModule**:

```
<handlers>
  <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
</handlers>
```
...but I get the 500 - Internal server error.

So my question is: is really supported the .NET Core 5.0.1 or should I install 3.1.0 version ?

Thank you,
Luca

**Comment by unquietwiki** [comment]
Hey @lucafabbri365 the codebase was already mostly ready for .NET 5, so I finished updating what I needed & got that merged into source earlier today. If you did a git clone of the current master, you might be able to build it (step 3 on IIS install; I was doing a Linux install).

**Comment by lucafabbri365** [comment]
Hello @unquietwiki,
I'm going to clone it and build it. I'll give you feedback asap.

Thank you,
Luca

**Comment by unquietwiki** [comment]
Hey @lucafabbri365 did the build work out for you?

**Comment by lucafabbri365** [comment]
Hello @unquietwiki,
the build worked fine: last PassCore is now running with .NET Core 5.0.1.
However with this latest version I'm experiencing change password issues for an AD standard user having "_User must change password at next logon_" selected (**UseAutomaticContext** set to _true_). Old version (currently in production) is working fine. 
I have to investigate on the code.

Bye,
Luca
