### ISSUE TITLE
Spamming webhost and causing DOS.

### ISSUE THREAD

**Issue by BubbaGumper** [unosquare/passcore#629]
**PassCore Server**
- OS: Windows 2019
- Provider: Active Directory or LDAP

**Describe the bug**
When submitting password change, there is a huge delay in the responsiveness of the system. Hosting server has 4x CPU and 16 GB of RAM. IIS, .NET CPU usage maxes at 15%. When running a browser capture, there a thousands of POST events to https://[host]/api/password. These are called from 879505b3.js line 702. Every call submits the user details. Server begins to return 400s with numerous errors flashing across the user interface. Further, Wireshark captures of LDAP traffic is in the hundred thousands. 

**To Reproduce**
1. Fill out webform
2. Press F12
3. Click CHANGE PASSWORD
4. Watch the errors flood in (30,000+)

**Expected behavior**
Form should submit one request and await status. 

**Screenshots**

![image](https://user-images.githubusercontent.com/82162185/114040253-6fc6bb00-9851-11eb-8bdf-f456142a0bfd.png)

**Desktop**
 - OS: Windows 10 / Windows 2019
 - Browser Edge, Chrome
 - Version Latest

**Comment by yo2mno** [comment]
I have the same issue with the latest version. I downgraded it and the number of requests is reduced.

**Comment by simonai1254** [comment]
Also have a look at #605, I think it's the same thing
