### ISSUE TITLE
move from wwwroot to a custom directory

### ISSUE THREAD

**Issue by abyssvi** [unosquare/passcore#63]
In my install, I want to have PassCore in folder that isn't called wwwroot (specifically, I name my folders like 'password.domain.com') - the first time I tried to access it I got a placeholder site in wwwroot, so when I played around with it I found that it only worked when it was in wwwroot. My IIS is configured to serve from the password.domain.com, not wwwroot.

Am I missing a configuration option for this, is this a bug, or is this intended?

**Comment by mariodivece** [comment]
This is an installation problem. Please extract and install in the intended folder. I also run passcore from a folder called passcore.domain.com Please go through the setup instructions creafully.

**Comment by abyssvi** [comment]
I don't really understand what you mean. Following the exact instructions, and reading them carefully (unless it's changed), the "intended folder" is wwwroot.
