### ISSUE TITLE
HTTP Error 500.31 - Failed to load ASP.NET Core runtime 

### ISSUE THREAD

**Issue by TollerEmil** [unosquare/passcore#631]
**PassCore Server**
- OS: [Windows ]
- Provider: [Active Directory]

**Describe the bug**
Installed Passcore as provided in your documentation

Try to browse to the website the following error occured:

HTTP Error 500.31 - Failed to load ASP.NET Core runtime 

Common solutions to this issue: 
The specified version of Microsoft.NetCore.App or Microsoft.AspNetCore.App was not found. 
Troubleshooting steps: 
• Check the system event log for error messages 
• Enable logging the application process' stdout messages 
• Attach a debugger to the application process and inspect 

For more information visit:  https://go.microsoft.com/fwlink/?LinkID=2028526 

**Additional context**
- UAC is active
- Windows Server 2019
- IIS Config
![image](https://user-images.githubusercontent.com/83347304/116397491-edfdf800-a826-11eb-9bce-d931f3201261.png)
![image](https://user-images.githubusercontent.com/83347304/116397567-066e1280-a827-11eb-972b-b8a7e5343d6a.png)

**Comment by enzo-dis** [comment]
I had the same HTTP Error 500.31 error and found the solution in issue #615

 https://github.com/unosquare/passcore/issues/615

**Comment by jhallal** [comment]
Check the version of the hosting bundle, the version of the Windows Server Hosting and the Runtime should match:
Microsoft .NET 5.0.11 - Windows Server Hosting
Microsoft .NET SDK 5.*.*
Microsoft .NET Runtime - 5.0.11
Refer to this post: [https://jamilhallal.blogspot.com/2021/11/dotnet-core-deployment-iis-error-500-31-failed-to-load-aspnet-core-runtime.html](https://bit.ly/3ntQ8QJ)
