### ISSUE TITLE
feature request - restrict password change for accounts from a specific AD Organization Unit

### ISSUE THREAD

**Issue by matoy** [unosquare/passcore#64]
Hi,

all is in the title: would it be possible to add a configuration setting to limit the password change to some accounts only located in specificied OUs in the Active Directory.

thank you.
very usefull app.

**Comment by roaima** [comment]
Use a dedicated account to change users' passwords. But instead of giving it admin rights, use AD Delegation to give it rights only in the OUs it's allowed to manage.

**Comment by matoy** [comment]
well done; closing ticket.
