### ISSUE TITLE
Initial project setup does not include the Tether library to be part of vendor file

### ISSUE THREAD

**Issue by sab1990** [unosquare/passcore#65]
Initial project setup does not include the Tether library to be part of vendor file. Because of this the page fails to load successfully and throws error  -
```
Uncaught Error: Bootstrap tooltips require Tether (http://tether.io/)
    at vendor.min.js:58
    at vendor.min.js:58
    at vendor.min.js:58
```

**Comment by mariodivece** [comment]
Please try with the latest version and let us know if this is still a problem. Reopen the issue if necessary.
