### ISSUE TITLE
feature request: email to reset password

### ISSUE THREAD

**Issue by matoy** [unosquare/passcore#68]
Hi,

Another feature request that might be very interesting: a button that the user could use to send an email to   his/her email address (the one in the "mail" attribute on his/her AD account).

The email would have a link which would allow to reset the password without knowing it.

I know it would make a lot of changes (including storing data in a file or database) and would change the original philosophy of passcore but that would be a great feature.

Of course that would only work when using a service account and not when UseAutomaticContext=true.

Thank you for considering this suggestion.

Regards,

**Comment by geoperez** [comment]
It's possible but we have no plans to include it.
