### ISSUE TITLE
not load in windows server 2k12

### ISSUE THREAD

**Issue by YnievesDotNet** [unosquare/passcore#69]
I'm do it all the recomendations, in the MD file, but, when I try load https://pass.mydomain.com, the browser stay waitting for long time. not load nothing

HttpPlatformHandler 1.2
PassCore 2.0.2beta2
Windows Server 2012 R2

Thanks, Yoinier

**Comment by tnguyen952** [comment]
Did you ever get this up and running?  I'm having the exact same issue.

**Comment by tnguyen952** [comment]
I got mine to work after adding the name to our DNS.   Pretty straightforward instructions.

**Comment by ScottP-KPS** [comment]
I'm (a noob) and stuck at step 5 - Install HttpPlatformHandler from Web Platform Installer --> 
When I run this installer it prompts me to select an App from the Web Gallery (83 apps listed) none seem to match or not obvious s to what i select.

**Comment by mariodivece** [comment]
Please try with the latest version and let us know if this is still a problem. Reopen the issue if necessary.
