### ISSUE TITLE
No error message when typing wrong password

### ISSUE THREAD

**Issue by pellenord** [unosquare/passcore#7]
Hi,

First of all, thank you very much for a nice project.
After setting up PassCore, it works fine to change the password (as long you type in valid data).
I have an issue in case the user types in the old password wrong or a user that doesn't exist.
There's no error message shown. Basically nothing happens, the screen stays the same as before you press "Change Password".

Kind Regards
Per

**Comment by mariodivece** [comment]
Are you absoutely certain the validations are not shown? All validations are performed on the server. You should see something like the screenshot below -- fields highlighted in red plus error messages below each field. Are you using ASP.NET 5? This sounds too much like when I forget to set  <httpErrors existingResponse="PassThrough"></httpErrors> in my web.config at the application or IIS level. Could you try debugging the application and see if it does the same on IIS Express?
![image](https://cloud.githubusercontent.com/assets/351978/12919317/284ec360-cf09-11e5-9a90-67fb21b6b559.png)

**Comment by pellenord** [comment]
Hi,
It's not the validation I mean. It is when the user for example type the current password or username wrong. In this case the password change fails because the user is not authenticated.
Meaning the error message from the password change in Active Directory must be shown.

Cheers

**Comment by mariodivece** [comment]
An error message at the top should appear like this:
![image](https://cloud.githubusercontent.com/assets/351978/12921877/d8e5e70c-cf14-11e5-85f5-74e44c8e3d16.png)

**Comment by mariodivece** [comment]
Also, when you type in a bad password, it should show the following error message:
![image](https://cloud.githubusercontent.com/assets/351978/12922331/95d3b0f0-cf16-11e5-9727-57e553f436e7.png)

**Comment by pellenord** [comment]
Thanks for your quick reply.
Any of these messages don't appear for us.
It might be related to our Active Directory still running version 2003?
Do I have a chance to catch the error message received by PassCore?

**Comment by pellenord** [comment]
Hi again,

Now when I make a double check of the validation you mentioned in an earlier post I see that this is also not working.
If I skip to fill in the New and Re-enter passwords and click the "Change Password" button the form stays like before without highlighting the missing fileds.
Some issues with jQuery?

**Comment by pellenord** [comment]
Just some additional info after some investigation.
To me it seems that some js (jquery, angular) is not working properly.
I have tested on IE 9, IE 11 and Chrome. Same behaviour all over.
None of the machines (clients or server) have internet connection.

**Comment by mariodivece** [comment]
That may be a problem as some resources are pulled from the internet such as scripts, images, etc. (i.e. CDN) - For example reCAPTCHA stuff. You can observe the resources failing with F12 developer tools in the Network tab.

**Comment by pellenord** [comment]
Hi,
Checked the resources and I only get error messages for reCAPTCHA which I have disabled in the appsettings.json. I even commented out the script line for reCAPTCHA in index.html.
Anyway, using the developer tool in Chrome, I can see an error response from api/password if for example the password is not filled in, but the form never updates.
As well if I fill in the current password wrong I can see the error response, but again the form is not updating.

**Comment by mariodivece** [comment]
Yeah, you still need the reCAPTCHA stuff even if you disable it. It is still used in the app.min.js and I doubt it’ll work without it because AngularJS is bootstrapped along with it. You will need to edit the app.min.js file to drop reCAPTCHA support (or better yet, use the non-minified versions in order to remove all references and functionality to reCAPTCHA and merge them together into your own app.min.js). (https://github.com/unosquare/passcore/tree/master/src/Unosquare.PassCore.Web/wwwroot/scripts)

Also, You still did not post the response body. I need to see the response body to verify it’s a proper 400 error containing a JSON-encoded object.

**Comment by pellenord** [comment]
Hi,

That was it!
I got it running by commenting out grecaptcha.reset(); (Line 73 in the app-03-controllers.js).
Then the form updates based on the response that comes back from the server as well the validation works as it should.

Kind Regards
Per

**Comment by mariodivece** [comment]
In the next version I will change the code so it:
- Completely disables reCAPTCHA if disabled form the config file
- Does not reset the reCAPTCHA form unless it expires
- reCAPTCHA widget language is configured via config file

**Comment by mariodivece** [comment]
This has been implemented in the current Beta. Closing issue.
