### ISSUE TITLE
Letsencrypt Support

### ISSUE THREAD

**Issue by TankParts** [unosquare/passcore#72]
I would like to use letsencrypt to generate an ssl certificate for a passcore site. 

Letsencrypt needs to browse to "http://password.yourdomain.com/.well-known/acme-challenge/x" to verify that a specific extentionless file exists on the web server.

The issue is that passcore is redirecting back to to the web root "http://password.yourdomain.com/" instead of returning the file at "http://password.yourdomain.com/.well-known/acme-challenge/x". 

This results in the letsencrypt acme challenge failing and no ssl certificate being issued.

Is there something I can do in IIS to make this work or is it a limitation of passcore?

**Comment by TankParts** [comment]
Is HomeController.cs causing my issue?
https://github.com/unosquare/passcore/blob/84349e9663cffbcf43ed492c3dd66f8431eee68e/src/Unosquare.PassCore.Web/Controllers/HomeController.cs

**Comment by ismailyenigul** [comment]
Hi,

Here is my workaround for this issue. 
1. Stop passcore site
2. Create a new site in a different path with http(80) binding for your hostname.
3. Request a certificate for newly created site
4. Edit passcore site enable HTTPS only and start
