### ISSUE TITLE
Restrict password changes to certain OU

### ISSUE THREAD

**Issue by vsboost** [unosquare/passcore#73]
Hi there,

Is there any way to configure this tool to only allow password changes for users in a certain OU -- for example only "Accounting" and nobody else?

Thanks

**Comment by gbowers** [comment]
@vsboost  Just delegate the "service account" you are configuring in the "appsettings.json" file to only have access to via: https://www.petri.com/delegate-permission-reset-ad-user-account-passwords
or something along those lines.
