### ISSUE TITLE
localhost works fine, IP address only shows footer

### ISSUE THREAD

**Issue by clementinebuschtetz** [unosquare/passcore#75]
I was able to install the application fine, I am even able to use it by typing http://localhost:5000. However when I use the IP address or full qualified domain name of the server, I can only see the footer of the PassCore page. 
It feels like it's missing some code...

**Comment by mariodivece** [comment]
You don't seem to be missing code. Seems like a networking issue. Closing. Please reopen if there's additional info you can provide. (Chrome Console Log Messages maybe?)
