### ISSUE TITLE
ReCaptcha Issue

### ISSUE THREAD

**Issue by ekrizon** [unosquare/passcore#79]
Hi all,

Finally got this setup (whew that was fun!)

Without ReCaptcha works fine every time like a charm.

With ReCaptcha it sometimes will change users password and sometimes not. Even if you leave all the credentials filled in exactly the same and reverify the Recaptcha, then try again it will go through when the first time it doesnt.

Just wondering if anyone else was experiencing this.  When it doesnt work it just says unable to change password (no error code or anything)

**Comment by mariodivece** [comment]
Please try with the latest version and let us know if this is still a problem. Reopen the issue if necessary.
