### ISSUE TITLE
Noob, stuck at step 5. Install httpPlatformHandler install

### ISSUE THREAD

**Issue by ScottP-KPS** [unosquare/passcore#81]
I'm (a noob) and stuck at step 5 - Install HttpPlatformHandler from Web Platform Installer --> 
When I run this installer it prompts me to select an App from the Web Gallery (83 apps listed) none seem to match or not obvious s to what i select.

**Comment by mariodivece** [comment]
Please try with the latest version. Reopen if the problem still exists.
