### ISSUE TITLE
User can change their password regardless of password policy

### ISSUE THREAD

**Issue by vstyrna** [unosquare/passcore#83]
User can change their password regardless of password policy.
On windows server 2016 Password policy have been configured that each user can change his password one time per day but on appsettings.json we use special user for conntact with active directory. Main issue that we can change password any times per day that password policy does not work for that. How to configure passcore app that each user have pocibility to change his password with his permission and password policy work in this case. I used this link to download 2.0.2.beta.2 app https://github.com/unosquare/passcore/releases/download/v2.0.2.beta.2/passcore-2.0.2.beta.2-2016-03-14.zip

**Comment by mariodivece** [comment]
This is outside of the scope of PassCore. All PassCore does is call AD to change a password either on behlf of the user or on behalf of an AD admin. It does not read GPOs. Closing.
