### ISSUE TITLE
Question: Append domain name to username

### ISSUE THREAD

**Issue by mmr2017** [unosquare/passcore#86]
Greetings,

I just recently set up PassCore and am in the process of testing it out - very nice so far!

Another user asked a question (Issue #44) about automatically adding the domain name so the user only needs to enter their username (i.e. johnsmith) and not their "full"domain name (i.e. johnsmith@domain.com) in the Username field. Geoperez responded that you could modify the PasswordController.cs file to append the domain. Would line 84 itself need to be modified or would a line of code need to be added after line 84? What would the actual code be in order to make it work?

Thanks!
Mark

**Comment by geoperez** [comment]
Hi, You can add the domain like the following code before [line 84](https://github.com/unosquare/passcore/blob/master/src/Unosquare.PassCore.Web/Controllers/PasswordController.cs#L84):

```csharp
using (var principalContext = AcquirePrincipalContext())
                {
                    // You need to add a line to append the domain to current model username property
                    model.Username += "@yourdomain.com";
                    var userPrincipal = AcquireUserPricipal(principalContext, model.Username);
```

**Comment by mmr2017** [comment]
Thank you very much, Geovanni. That worked perfectly!

Mark
