### ISSUE TITLE
Unable to load (and run) project in Visual Studio 2017

### ISSUE THREAD

**Issue by cillgen** [unosquare/passcore#87]
Hi,

I have Visual Studio 2017 on my computer.
When I load unosquare/passcore project, it converts the project to new format "almost automatically".

But project can not run... there are a lot of error, specially with unsolved references.
I tried several solutions read on internet but none made project works...

Any suggestions ???

Thanks.

Best regards

**Comment by geoperez** [comment]
For supporting VS2017 please use the branch [NetCoreSupport](https://github.com/unosquare/passcore/tree/NetCoreSupport)

**Comment by cillgen** [comment]
Hi,

Still have a lot of error with branch NetCoreSupport and .NETCore 2.0 installed.

Any suggestions ? Thanks.

Best regards

**Comment by geoperez** [comment]
What kind of errors?

**Comment by cillgen** [comment]
A lot of NuGet errors while openning the project :

`Restauration des packages NuGet...
Le package Microsoft.Extensions.Configuration.Json 2.0.0 n'est pas compatible avec net461 (.NETFramework,Version=v4.6.1). Le package Microsoft.Extensions.Configuration.Json 2.0.0 prend en charge : netstandard2.0 (.NETStandard,Version=v2.0)
Le package Microsoft.Extensions.Logging.Debug 2.0.0 n'est pas compatible avec net461 (.NETFramework,Version=v4.6.1). Le package Microsoft.Extensions.Logging.Debug 2.0.0 prend en charge : netstandard2.0 (.NETStandard,Version=v2.0)
Le package Microsoft.AspNetCore.Server.Kestrel 2.0.0 n'est pas compatible avec net461 (.NETFramework,Version=v4.6.1). Le package Microsoft.AspNetCore.Server.Kestrel 2.0.0 prend en charge : netstandard2.0 (.NETStandard,Version=v2.0)
Le package Microsoft.Extensions.DependencyInjection 2.0.0 n'est pas compatible avec net461 (.NETFramework,Version=v4.6.1). Le package Microsoft.Extensions.DependencyInjection 2.0.0 prend en charge : netstandard2.0 (.NETStandard,Version=v2.0)
Le package Microsoft.Extensions.Configuration 2.0.0 n'est pas compatible avec net461 (.NETFramework,Version=v4.6.1). Le package Microsoft.Extensions.Configuration 2.0.0 prend en charge : netstandard2.0 (.NETStandard,Version=v2.0)
Le package Microsoft.AspNetCore.Server.IISIntegration 2.0.0 n'est pas compatible avec net461 (.NETFramework,Version=v4.6.1). Le package Microsoft.AspNetCore.Server.IISIntegration 2.0.0 prend en charge : netstandard2.0 (.NETStandard,Version=v2.0)
Le package Microsoft.Extensions.Logging.Console 2.0.0 n'est pas compatible avec net461 (.NETFramework,Version=v4.6.1). Le package Microsoft.Extensions.Logging.Console 2.0.0 prend en charge : netstandard2.0 (.NETStandard,Version=v2.0)
Le package Microsoft.AspNetCore.Mvc 2.0.0 n'est pas compatible avec net461 (.NETFramework,Version=v4.6.1). Le package Microsoft.AspNetCore.Mvc 2.0.0 prend en charge : netstandard2.0 (.NETStandard,Version=v2.0)
Le package Microsoft.AspNetCore.Hosting 2.0.0 n'est pas compatible avec net461 (.NETFramework,Version=v4.6.1). Le package Microsoft.AspNetCore.Hosting 2.0.0 prend en charge : netstandard2.0 (.NETStandard,Version=v2.0)
Le package Microsoft.Extensions.Logging 2.0.0 n'est pas compatible avec net461 (.NETFramework,Version=v4.6.1). Le package Microsoft.Extensions.Logging 2.0.0 prend en charge : netstandard2.0 (.NETStandard,Version=v2.0)
Le package Microsoft.AspNetCore.StaticFiles 2.0.0 n'est pas compatible avec net461 (.NETFramework,Version=v4.6.1). Le package Microsoft.AspNetCore.StaticFiles 2.0.0 prend en charge : netstandard2.0 (.NETStandard,Version=v2.0)
Le package Microsoft.AspNetCore.Razor.Runtime 2.0.0 n'est pas compatible avec net461 (.NETFramework,Version=v4.6.1). Le package Microsoft.AspNetCore.Razor.Runtime 2.0.0 prend en charge : netstandard2.0 (.NETStandard,Version=v2.0)
Le package Microsoft.Extensions.Logging.Configuration 2.0.0 n'est pas compatible avec net461 (.NETFramework,Version=v4.6.1). Le package Microsoft.Extensions.Logging.Configuration 2.0.0 prend en charge : netstandard2.0 (.NETStandard,Version=v2.0)
Un ou plusieurs packages sont incompatibles avec .NETFramework,Version=v4.6.1.
Le package Microsoft.Extensions.Configuration.Json 2.0.0 n'est pas compatible avec net461 (.NETFramework,Version=v4.6.1) / win7-x86. Le package Microsoft.Extensions.Configuration.Json 2.0.0 prend en charge : netstandard2.0 (.NETStandard,Version=v2.0)
Le package Microsoft.Extensions.Logging.Debug 2.0.0 n'est pas compatible avec net461 (.NETFramework,Version=v4.6.1) / win7-x86. Le package Microsoft.Extensions.Logging.Debug 2.0.0 prend en charge : netstandard2.0 (.NETStandard,Version=v2.0)
Le package Microsoft.AspNetCore.Server.Kestrel 2.0.0 n'est pas compatible avec net461 (.NETFramework,Version=v4.6.1) / win7-x86. Le package Microsoft.AspNetCore.Server.Kestrel 2.0.0 prend en charge : netstandard2.0 (.NETStandard,Version=v2.0)
Le package Microsoft.Extensions.DependencyInjection 2.0.0 n'est pas compatible avec net461 (.NETFramework,Version=v4.6.1) / win7-x86. Le package Microsoft.Extensions.DependencyInjection 2.0.0 prend en charge : netstandard2.0 (.NETStandard,Version=v2.0)
Le package Microsoft.Extensions.Configuration 2.0.0 n'est pas compatible avec net461 (.NETFramework,Version=v4.6.1) / win7-x86. Le package Microsoft.Extensions.Configuration 2.0.0 prend en charge : netstandard2.0 (.NETStandard,Version=v2.0)
Le package Microsoft.AspNetCore.Server.IISIntegration 2.0.0 n'est pas compatible avec net461 (.NETFramework,Version=v4.6.1) / win7-x86. Le package Microsoft.AspNetCore.Server.IISIntegration 2.0.0 prend en charge : netstandard2.0 (.NETStandard,Version=v2.0)
Le package Microsoft.Extensions.Logging.Console 2.0.0 n'est pas compatible avec net461 (.NETFramework,Version=v4.6.1) / win7-x86. Le package Microsoft.Extensions.Logging.Console 2.0.0 prend en charge : netstandard2.0 (.NETStandard,Version=v2.0)
Le package Microsoft.AspNetCore.Mvc 2.0.0 n'est pas compatible avec net461 (.NETFramework,Version=v4.6.1) / win7-x86. Le package Microsoft.AspNetCore.Mvc 2.0.0 prend en charge : netstandard2.0 (.NETStandard,Version=v2.0)
Le package Microsoft.AspNetCore.Hosting 2.0.0 n'est pas compatible avec net461 (.NETFramework,Version=v4.6.1) / win7-x86. Le package Microsoft.AspNetCore.Hosting 2.0.0 prend en charge : netstandard2.0 (.NETStandard,Version=v2.0)
Le package Microsoft.Extensions.Logging 2.0.0 n'est pas compatible avec net461 (.NETFramework,Version=v4.6.1) / win7-x86. Le package Microsoft.Extensions.Logging 2.0.0 prend en charge : netstandard2.0 (.NETStandard,Version=v2.0)
Le package Microsoft.AspNetCore.StaticFiles 2.0.0 n'est pas compatible avec net461 (.NETFramework,Version=v4.6.1) / win7-x86. Le package Microsoft.AspNetCore.StaticFiles 2.0.0 prend en charge : netstandard2.0 (.NETStandard,Version=v2.0)
Le package Microsoft.AspNetCore.Razor.Runtime 2.0.0 n'est pas compatible avec net461 (.NETFramework,Version=v4.6.1) / win7-x86. Le package Microsoft.AspNetCore.Razor.Runtime 2.0.0 prend en charge : netstandard2.0 (.NETStandard,Version=v2.0)
Le package Microsoft.Extensions.Logging.Configuration 2.0.0 n'est pas compatible avec net461 (.NETFramework,Version=v4.6.1) / win7-x86. Le package Microsoft.Extensions.Logging.Configuration 2.0.0 prend en charge : netstandard2.0 (.NETStandard,Version=v2.0)
Un ou plusieurs packages sont incompatibles avec .NETFramework,Version=v4.6.1 (win7-x86).
La restauration des packages NuGet a échoué.
Temps écoulé : 00:00:00.9045078
========== Fin ==========`

No need to try and compile the software. It will failed....

**Comment by Israel-94** [comment]
Hi cillgen, Have you try installing the .NET standard 2.0?

**Comment by cillgen** [comment]
After having :
 - update VS2017 to  15.4.2
 - install node.js
 - update package @angulare/core
 - elevate privileges of VS2017 (make it run as admin). 

.....I successfully opened the project in VS2017 and made it compile without errors (but with 132 warnings....).

Now I cannot run as it fails on a stupid error : "System.IO.FileNotFoundException: Could not find file: ~/index.html".
File is there but not sure that debbugger correctly deploy it....

Help needed !

Thanks.

**Comment by Israel-94** [comment]
Are you run it on Release or Debug mode?, try running on Debug mode.

**Comment by cillgen** [comment]
I'm already in debug mode

**Comment by Israel-94** [comment]
When you build or run the project in debug mode, a folder should be create `wwwroot/`, is where the app loads, if the folder is not created then something is happened in the process,  Could you check in the output when you build or run the project to see if there was any error?

**Comment by geoperez** [comment]
Hi @cillgen did you get the new version running?

**Comment by cillgen** [comment]
Hi all,

Sorry the this late feedback (I moved to another project...).

I did a checkout few days ago, on the basis of code source commited on Nov 7, 2017.
Without changing anything on my side, this version works fine.

Issue is solved but I will investigated to understand why previous version was not running.

Anyway, many thanks for your help !!
