### ISSUE TITLE
Ubuntu or other linux?

### ISSUE THREAD

**Issue by stevenmcastano** [unosquare/passcore#90]
Has anyone tried to get this to run under dotnet services under linux? I'd really love to do that a move it to a much smaller machine on a much better OS.... a whole Windows 2008 R2 server for this is a lot.

**Comment by geoperez** [comment]
We are trying to target to .NET Core but the LDAP support is still under development. So the solution can't work yet on Linux.

**Comment by stevenmcastano** [comment]
That’s great news though… just the fact that it’s headed in that direction is great, I’d love to see that happen.

I’m not the greatest coder ever, but I do run a few datacenters and have plenty of server resources. Would there be anything I could do to help development along? Build dev/test environments? Provide access to VMs? etc..?

**Comment by geoperez** [comment]
We already port some code from Novell to have a LDAP client working, but in order to change a password against Active Directory the connection must be secured by GSSAPI. We are still working on this.

If you have experience with GSSAPI, the LDAP client is located here: https://github.com/unosquare/swan

**Comment by ebekker** [comment]
You might be interested in #195.

**Comment by ebekker** [comment]
@geoperez -- is the LDAP support in SWAN a port of the original Java LDAP client from Novell, or from [this port](https://github.com/dsbenghe/Novell.Directory.Ldap.NETStandard) to .NET Standard.

The API looks very nice and clean -- do you know how well tested it is?

**Comment by geoperez** [comment]
Yeah, we took that port as a base, but we have been improving the code trying to use a more .NET-ish approach because it contains some Java things we don't like. For example using `GetEnumerator/obj.Next` instead of `foreach`, also the awful `ArrayList`.
