### ISSUE TITLE
Angular fails when run thru Juniper Pulse gateway

### ISSUE THREAD

**Issue by eLvErDe** [unosquare/passcore#91]
Hi,

Sadly your app does not work behing this gateway because it tweaks page content and breaks Angular routing:
https://github.com/angular/angular.js/issues/8905

muprhy85 suggests to add:

```
app.config( function( $httpProvider ) {
  $httpProvider.interceptors.push( function( $q, $rootScope ) {
    return {
      'request': function( config ) {
        // Convert request URL for Juniper Secure Web Access
        if ( typeof DanaUrl === "function" && !config.url.includes( '.html' ) ) {
          config.url = DanaUrl( config.url );
        }
        return config;
      }
    };
  } );
} );
```
which looks ok to me. Would you be kind enough to merge this ?

In the meanwhile, i'll try to add this myself and rebuild to see if it really fixes the issue for us.

Regards, Adam.

**Comment by mariodivece** [comment]
could you try with the latest release and instructions please?
