### ISSUE TITLE
Run with existing website

### ISSUE THREAD

**Issue by azmcnutt** [unosquare/passcore#92]
Hi Everyone.  Is there a way to run PassCore on an existing web site by adding the application?

For instance, we have https://web.domain.org.  In IIS can I install PassCore as https://web.domain.org/password

It runs fine if we put Pass Core in as its own website, but as an application added to an existing site, we only get Loading PassCore...

Thanks,
James

**Comment by mariodivece** [comment]
Duplicate of #71
