### ISSUE TITLE
IIS Installation Issue

### ISSUE THREAD

**Issue by KayGt3** [unosquare/passcore#93]
Hello, i'm new and i have a problem at point 2 of your guide: dotnet publish --framework net461 --output "<path>" --configuration Release

I put the passcore folder in <path> (Example: "C:\Passcore-3.0.0") but is return the error: MSBUILD: errore MS81003: Specify a project or solution file.

Cane you help me?

Thanks!
Marco

**Comment by hozuki689** [comment]
Hi there,

I'm new as well here, I think the instruction number 2 actually has 2 options, either you use the compiled version which is the Passcore-3.0.0 folder or you download the project files. The "dotnet publish" command will compile the project but the Passcore-3.0.0 folder is a version that is already compiled so if you use the Passcore-3.0.0 i.e the alternate option in instruction number 2, you don't need to use the "dotnet publish" command. Hope that helps!


Hope that helps!

**Comment by geoperez** [comment]
I updated the documentation step 2. Let me know if it is easier to understand.

**Comment by KayGt3** [comment]
I follow the documentation and now Passcore works!

Thank you!
