### ISSUE TITLE
HTTP Error 500.19 - Internal Server Error

### ISSUE THREAD

**Issue by rhart211** [unosquare/passcore#94]
I have followed your instructions as carefully as I was able; some of the instructions are a little confusing. 
However, I have it "installed" on a Windows 2012 R2 Standard Server with IIS 8.5. And I'm using PassCore 3.0.0. I have installed from the zip file created 13 days ago.

But I'm still getting the error: HTTP Error 500.19 - Internal Server Error
Where it lists the following;
Module	   IIS Web Core
Notification	   Unknown
Handler	   Not yet determined
Error Code	   0x8007000d
Config Error	   
Config File	   \\?\C:\PassCore\web.config
Config Source:
   -1: 
    0: 

I'm uncertain on how to proceed to resolve this issue.  

Thank you.

**Comment by TheVakman** [comment]
@rhart211 How did you fix this?
