### ISSUE TITLE
Stuck on "loading passcore..." page

### ISSUE THREAD

**Issue by hozuki689** [unosquare/passcore#96]
Hello all,

I followed the readme instruction except for the SSL part and I'm not sure why I keep getting the "loading passcore..." page. I'm using the Passcore-3.0.0 folder and I had a look on the issue #2 and noticed that the Passcore-3.0.0 doesn't have the "Unosquare.PassCore.Web/" folder. With this in mind, I downloaded the master/project version, compiled it and compared the output folder to Passcore-3.0.0 and doesn't seem to have any difference. With that in mind, I just used "dnu restore" in the parent folder that consist the wwroot folder and logs, downloaded dnx and dnvm, I still got the "loading passcore..." page. 

This is the log I got in the logs folder when I tried to access the site,

============================================
Hosting environment: Production
Content root path: C:\Passcore 3.0.0
Now listening on: http://localhost:16514
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://win-ded2i2hpj8f.passcoread.com:10005/  
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/index.html'. Physical path: 'C:\Passcore 3.0.0\wwwroot\index.html'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 126.4912ms 200 text/html
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://win-ded2i2hpj8f.passcoread.com:10005/assets/styles/indigo-pink.css  
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/assets/styles/indigo-pink.css'. Physical path: 'C:\Passcore 3.0.0\wwwroot\assets\styles\indigo-pink.css'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 12.1066ms 200 text/css
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://win-ded2i2hpj8f.passcoread.com:10005/styles.bundle.js  
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/styles.bundle.js'. Physical path: 'C:\Passcore 3.0.0\wwwroot\styles.bundle.js'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://win-ded2i2hpj8f.passcoread.com:10005/vendor.bundle.js  
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/vendor.bundle.js'. Physical path: 'C:\Passcore 3.0.0\wwwroot\vendor.bundle.js'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://win-ded2i2hpj8f.passcoread.com:10005/inline.bundle.js  
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/inline.bundle.js'. Physical path: 'C:\Passcore 3.0.0\wwwroot\inline.bundle.js'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://win-ded2i2hpj8f.passcoread.com:10005/main.bundle.js  
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/main.bundle.js'. Physical path: 'C:\Passcore 3.0.0\wwwroot\main.bundle.js'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://win-ded2i2hpj8f.passcoread.com:10005/polyfills.bundle.js  
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/polyfills.bundle.js'. Physical path: 'C:\Passcore 3.0.0\wwwroot\polyfills.bundle.js'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 13.9325ms 200 application/javascript
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 10.5974ms 200 application/javascript
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 11.8417ms 200 application/javascript
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 11.5233ms 200 application/javascript
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://win-ded2i2hpj8f.passcoread.com:10005/assets/fonts/Roboto/Roboto-Regular.ttf  
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 568.3365ms 200 application/javascript
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method Unosquare.PassCore.Web.Controllers.HomeController.Index (Unosquare.PassCore.Web) with arguments ((null)) - ModelState is Valid
info: Microsoft.AspNetCore.Mvc.Internal.VirtualFileResultExecutor[1]
      Executing FileResult, sending file as 
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action Unosquare.PassCore.Web.Controllers.HomeController.Index (Unosquare.PassCore.Web) in 66.5687ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 971.3812ms 200 text/html
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://win-ded2i2hpj8f.passcoread.com:10005/favicon.ico  
info: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[2]
      Sending file. Request path: '/favicon.ico'. Physical path: 'C:\Passcore 3.0.0\wwwroot\favicon.ico'
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 0.6821ms 200 image/x-icon

============================================

I'm not sure if I'm missing something, the readme instruction seems to be straightforward but I do not understand why I got the "loading passcore..." page, unless it really requires to use SSL certificate. Thank you

**Comment by pathade90** [comment]
Hello,

Same issue I am also experiencing. Everything works fine on Chrome and Mozilla only IE has problem.
Enabled all the JavaScript and other settings in IE but no luck.

I have also applied the SSL Certificate but issue remains same.

Kindly help.

**Comment by hozuki689** [comment]
Hello,

I didn't think about using other browsers, been using Internet Explorer to test it out. Thanks for that! And yes, it seems Chrome and Firefox are able to access the form page but not Internet Explorer. Trying to figure out by using older version of IE or disabling Compatibility view, but still not working either. So the issue remains the same on IE sadly.

**Comment by pathade90** [comment]
Hello,

Thanks for looking into.

While review few article found that IE have some issues with Angular JS 2/4 it might be related to same. Some have suggested to modify pollyfils.js which cant be located in Zip file might be pulled directly from Github online solution.

Regardless of any settings in IE it doesn’t seem to work.

Regards,
Amol.

**Comment by geoperez** [comment]
Let me take a look at IE support.

**Comment by geoperez** [comment]
@pathade90 and @hozuki689, can you test with the branch Issue96-IEStuckOnLoading?

**Comment by hozuki689** [comment]
Hello,

I have tested the branch Issue96-IEStuckOnLoading and it seems working fine on IE, Firefox and Chrome! Thank you for the help. I was wondering what polyfills does though, is it to enable using other libraries/features? Also is it only IE browser that normally requires this? Thanks!

**Comment by geoperez** [comment]
I'm going to merge and release a new build. Closing this issue.

**Comment by jpalcala** [comment]
Hi @hozuki689,  as the angular webpage explains :

> Angular is built on the latest standards of the web platform. Targeting such a wide range of browsers is challenging because they do not support all features of modern browsers. You compensate by loading polyfill scripts ("polyfills") for the browsers that you must support

Polyfills are scripts that allow old web browsers to support new features. IE (and others) does not support all the features that angular needs  so to compensate this we had to use a couple of polyfills.

**Comment by hozuki689** [comment]
I see, alright, thank you very much!
