### ISSUE TITLE
Can't change the password

### ISSUE THREAD

**Issue by bondit17** [unosquare/passcore#98]
Hi everyone,

First let me thank you for this great tool. Just one small issue. 
When i am trying to change a password for a user via the web portal, i am getting the error in the attached screenshot. 
![password change error](https://user-images.githubusercontent.com/30272472/34693800-01be9656-f493-11e7-80e6-751a7a999475.png)

I am able to change the password via ctrl+alt+del and via active directory users and computers. The user that i am authenticating the app with is a domain admin.

Anything specific that i can check?

**Comment by bondit17** [comment]
Silly me this is resolved. GPO issue.

However i did ran into another issue. Users will have to type in their domain username@domain.local
Is there a way to configure the app so the users will be able to type only their user name without the @domain.local part?

**Comment by geoperez** [comment]
You can edit the controller to append the domain in the username input.

**Comment by bondit17** [comment]
Thank you for the reply.
Which file would that be? the appsettings.json or vendor.bundle.js?

**Comment by geoperez** [comment]
I mean the API Controller.
